### ISSUE TITLE
HTML 5 video blocked? [1545823]

### ISSUE THREAD

**Issue by AMihail1** [ghacksuserjs/ghacks-user.js#695] opened 2019-04-19 10:54 UTC
As far as I can tell all the HTML5 player settings are on but I'm getting a infinite loading circle loop on some sites - can someone tell me which settings could possibly be related to this?

**Comment by crssi** [comment] 2019-04-19 11:07
URL?

**Comment by AMihail1** [comment] 2019-04-19 11:09
Seems to be these "Brightcove" players specifically

https://support.brightcove.com/brightcove-player-sample-are-you-still-watching

**Comment by crssi** [comment] 2019-04-19 11:39
Do you still need an answer? Did you tried on some other browser?

**Comment by AMihail1** [comment] 2019-04-19 11:40
I'm too stupid to understand why they're blocked :P

**Comment by Thorin-Oakenpants** [comment] 2019-04-19 12:15
What do you see when you go to https://www.youtube.com/html5 - I get seven out of seven ticks

Anyway
- Create a new temp profile and use that, will it play (if you don't want to mess around with profiles, just download a portable Firefox from https://portableapps.com/apps/internet/firefox_portable )
- Now add the user.js and restart. Does it play?

Once you've established that it's a user.js pref that causes the issue, then there are more steps you can take to [troubleshoot](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) it 

- first of all, make sure you are not blocking anything: e.g brightcove etc in uBlock Origin, or Firefox's Tracking Protection, etc

**Comment by AMihail1** [comment] 2019-04-19 16:21
> 
> 
> What do you see when you go to https://www.youtube.com/html5 - I get seven out of seven ticks
> 
> Anyway
> 
>     * Create a new temp profile and use that, will it play (if you don't want to mess around with profiles, just download a portable Firefox from https://portableapps.com/apps/internet/firefox_portable )
> 
>     * Now add the user.js and restart. Does it play?
> 
> 
> Once you've established that it's a user.js pref that causes the issue, then there are more steps you can take to [troubleshoot](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) it - just keep using the portable FF or test profile

I see 7 ticks too yeah. I've turned off all the adblocking stuff and the vids still aren't loading which leads me to believe it's user.js related ...

**Comment by AMihail1** [comment] 2019-04-19 18:41
Also seeing `AbortError: The fetching process for the media resource was aborted by the user agent at the user's request.` :S

**Comment by Atavic** [comment] 2019-04-19 20:38
[CORS and Brightcove](https://support.brightcove.com/concepts-cors)

**Comment by AMihail1** [comment] 2019-04-19 21:05
> 
> 
> [CORS and Brightcove](https://support.brightcove.com/concepts-cors)

Are you saying the solution is in here or it's a bug in Firefox itself?

**Comment by Atavic** [comment] 2019-04-19 21:08
It's brightcove multiplexing to some CDN. It means that you click on a link and your request goes to some 3rd party server that may - or may not - respect the CORS headers.

**Comment by AMihail1** [comment] 2019-04-19 21:11
> 
> 
> It's brightcove multiplexing to some CDN. It means that you click on a link and your request goes to some 3rd party server that may - or may not - respect the CORS headers.

Tbh I can't even get the player to load in a clean, blank FF profile - maybe I've broken something on a deeper level. Works in Chrome tho ...

**Comment by Atavic** [comment] 2019-04-19 21:23
I can confirm ungoogled chromium work fine. FF gives no video, if I click on the codepen link I get a cloudflare page with captchas (choose all the bikes).

**Comment by Atavic** [comment] 2019-04-19 21:24
I can confirm ungoogled chromium works fine. FF gives no video, if I click on the codepen link I get a cloudflare page with captchas (choose all the bikes).

**Comment by AMihail1** [comment] 2019-04-20 13:11
Reported to Bugzilla guys.

**Comment by Thorin-Oakenpants** [comment] 2019-04-24 14:26
Is there a bugzilla number?

**Comment by AMihail1** [comment] 2019-04-24 15:42
https://bugzilla.mozilla.org/show_bug.cgi?id=1545823

**Comment by Thorin-Oakenpants** [comment] 2019-04-24 16:08
Thanks. Since it's not a user.js issue, it's reproducible on nightly by someone else, I'll close this

**Closed by Thorin-Oakenpants** 2019-04-24 16:08 UTC
Labels: firefox bug
