### ISSUE TITLE
v59 - Questions and Suggestions

### ISSUE THREAD

**Issue by iWARR** [ghacksuserjs/ghacks-user.js#400] opened 2018-04-15 12:47 UTC
1) What do you think about this fixed `"data:application/json,{}"` value ?

`/* 0360: disable new tab tile ads & preload & marketing junk ***/`

	used:

`user_pref("browser.newtabpage.directory.source", "data:text/plain,");`

	new (to prevent browser console spam):

`user_pref("browser.newtabpage.directory.source", "data:application/json,{}");`

https://github.com/MrAlex94/Waterfox/issues/496#issuecomment-376914186

2) "**datareporting.healthreport.infoURL**" - value (URL link) is not empty

Although the main option is deactivated, clearing URL value would be welcome.
I think, the setting can be placed at the corresponded section (0333):

```
/* 0333: disable health report
 * [SETTING] Privacy & Security -> Firefox Data Collection & Use -> Allow Firefox to send technical... data ***/
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.healthreport.infoURL", "");
```

infoURL (default value): `https://www.mozilla.org/legal/privacy/firefox.html#health-report`

3) **Telemetry**. Should be cleared these default values also?

```
services.sync.telemetry.maxPayloadCount			500
services.sync.telemetry.submissionInterval		43200
toolkit.telemetry.infoURL				https://www.mozilla.org/legal/privacy/firefox.html#telemetry
```

Later this one has disappeared in some case (probably, after some general option was disabled):

`devtools.telemetry.supported_performance_marks`

value = `contentInteractive,navigationInteractive,navigationLoaded,visuallyLoaded,fullyLoaded,mediaEnumerated,scanEnd`

4) **Passwords**. This password settings are unclear, enabled and missed in the "ghacks-user.js" list.
Password settings are important, as well. What you can say about this (defaults):

```
services.sync.engine.passwords					true
services.sync.prefs.sync.browser.safebrowsing.passwords.enabled	true
signon.recipes.path						chrome://passwordmgr/content/recipes.json
```

If SB & TP are disabled (uBO will be used + stock FF pass management), which values for this settings should be the most safe? What are they mean? What are chrome passwords doing in FFox ?!

May be the next short guide will appear helpul for implementation:

**Disable Firefox Sync** (data stored on Mozilla owned servers):
https://www.stigviewer.com/stig/mozilla_firefox/2017-03-22/finding/V-57673

5) `pref("devtools.webide.autoConnectRuntime", false)`		- NOT EXISTING in the "ghacks-user.js" list (default = `true` and still enabled)

_Firefox silently installs "ADB Helper" and "Valence" Plugins (remote access to PC), when you open and close WebIDE in Developer tools for the first time. Also "adb.exe" background process running in the Task Manager. WebIDE’s main use case today is to connect to devices, and for this to function, the ADB Helper addon is downloaded when it is first opened._

_Removing "ADB Helper" and "Valence" Firefox Add-ons (don’t worry, they won’t be installed next time, even when you access WebIDE again):_

_1. Add-ons Manager -> Extensions
2. Uninstall "ADB Helper" and "Valence" add-ons, one by one._

http://techdows.com/2015/08/shocking-firefox-silently-installs-adb-helper-and-valence-add-ons.html

Сan be disabled by setting the following preferences:

```
pref("devtools.webide.enabled", false)				- OK (2611)
pref("devtools.webide.autoinstallADBHelper", false)		- OK (2611)
pref("devtools.webide.autoinstallFxdtAdapters", false)		- obsolete (2611, FF57)
pref("devtools.webide.autoConnectRuntime", false)		- NOT OK, NOT EXISTING in the "ghacks-user.js" (default = "true")
```

---------------------------------------------------

**Thank you for your Time & Power. The project is great.**

**Comment by earthlng** [comment] 2018-04-15 13:59
Hi,

1. that pref was removed in FF60 and we will move it to 9999 as soon as FF60 is released. Not worth changing the value anymore.
2. all the `*.infoURL`'s are the links behind "Learn more" links/buttons. Nothing is ever sent to that URL and unless you click the "Learn more" button(s) those URLs are never used. We want "Learn more" buttons to remain functional and there's really no reason to break them.
3. 
- maxPayloadCount and submissionInterval are irrelevant when telemetry is disabled.
- `toolkit.telemetry.infoURL` see point 2.
- `devtools.telemetry.supported_performance_marks` = [0 results for FF59](https://dxr.mozilla.org/mozilla-release/search?q=supported_performance_marks) ie not used anymore.

4.
- `services.sync.engine.passwords` allows Sync users to sync their passwords across devices. I know, sounds horrible but some people apparently like it. We don't disable anything to do with Sync because people who signup for it do so willingly and they should understand the potential risks.
- `services.sync.prefs.sync.browser.safebrowsing.passwords.enabled` - this syncs the state of the pref `browser.safebrowsing.passwords.enabled`. Again, we don't disable Sync-related stuff.
- chrome://passwordmgr/content/recipes.json looks to be some selectors which improve password field detection on those few sites. Seems useful for people who use the password manager. You can disable pw-storage with `0901`
> What are chrome passwords doing in FFox ?!

chrome:// urls are used to access certain files shipped with Firefox. It has nothing to do with Google Chrome.

5. `devtools.webide.autoConnectRuntime` should be covered by `devtools.webide.enabled=false`

**Comment by iWARR** [comment] 2018-04-15 15:58
@earthlng Thanks a lot for your attention. I'll make a correspondent notes in my own preffered settings. Happy to know, that everything is under control.

As I can see, you trust to the "general" switches of the relative blocks, while I prefer kill them all (in the most dangerous sections) one by one. Why?

- in the future, when you will have a quick look at all-done settings, searching "did I miss smth?" or "what kind of new spying options have been preperared for us this time", catching this ones will be easier. This is better "eye-catch" feature (for those, who don't read bugzilla and specs as much as you). 

Hope, you understand: Search <keyword> -> false, false, false, false, true.... (oops!), false...
(I know about mirror wording)

- general option may have been changed/reworked/replaced by other. It will start working again (and secondary active options will support the new one again). If you didn't catch this change in time, you'll get full spying for a long time. Look at Windows... My experience says that killing all dengerous in all different places is much more safe.

("Learn more" links are OK, now I'm understand why, thanks. If you say chrome:// urls  are ok, then I prefer do not disrupt "saving passwords", e.g. useful settings. I'm prefer "smart balance", but not too relaxed)

**Comment by Thorin-Oakenpants** [comment] 2018-04-15 16:03
^^ everything earthlng said except...

we use `data:text/plain,` in a few places, I've never seen anyone use `data:application/json,{}` before. This is not my area at all. I believe that what we have is fine - eg some pref overrides are blank/null, some are `data:text/plain,` . Earthlng is our resident expert on these (and from memory, the code behind some prefs barf at different values, or lack of them).

If there's nothing else to do here, then I think we can close this.

Oooh, and as I was about to post, @iWARR replied. Hi IWARR :) We fully understand the need for future-proofing and in the past the occasional master pref has been bypassed due to bug regressions. We already include a number of extra prefs that technically we do not need to (i.e to cover our asses and give peace of mind). We also pick up on every single change between versions (including system addons) - you can click on the "diffs" label in issues to see them all.

**Comment by Thorin-Oakenpants** [comment] 2018-04-15 16:05
> As I can see, you trust to the "general" switches"

Sorry, just to clarify, no we don't. ~~We~~ Earthlng actually digs into the code and checks it all out. And we do cover our asses in a few places where we strictly don't need to, just in case.

**Closed** 2018-04-15 16:26 UTC

**Comment by iWARR** [comment] 2018-04-18 09:57
Hello again. I have a small question about a name of the editor (didn't find any mentioning in the Wiki).

> It is recommended that you use an editor that supports syntax highlighting.

"For example, ........."

[Working with a user.js](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview), I like screenshot №2. 

1) What the name of THIS editor?
2) Are some special color highlightning settings needed to look exactly the same?

Thank you.

**Comment by Thorin-Oakenpants** [comment] 2018-04-18 10:08
It's Notepad++ https://portableapps.com/apps/development/notepadpp_portable

**Comment by Thorin-Oakenpants** [comment] 2018-04-19 10:09
@iWARR Settings>Style Configurator - theme is `Obsidian`, and font is `Hack` - https://github.com/source-foundry/Hack

**Comment by iWARR** [comment] 2018-05-08 19:06
**I NEED YOUR HELP!**

I don't want to open a new issue, because my trouble is... very-very strange.
I can't run frashy installed FF v59.0.3 normally. (2 installs - the same thing)

Seems like a big troubles with java. For example:

- In Violentmonkey Add-on properties i can't open "Settngs" page and "About" page. But the main works!

- In uBO Add-on properties i can't export my rules, when press "Export" button (nothing is happen, like "died" button). But "Import" works!

- Now (2-nd installation) I can't add script from https://greasyfork.org
  The button of the script-installation doesn't press....

What's going on?! May be it's my custom override rules? 
Have you any mention how to troubleshoot, what the setting to switch?
I tried many things, but nothing was helpful. WTF a shame...

**Comment by Thorin-Oakenpants** [comment] 2018-05-08 22:36
mozillazine is old and not maintained
