### ISSUE TITLE
RFP breaks photos.google.com [find the bugzilla]

### ISSUE THREAD

**Issue by bitpixl** [ghacksuserjs/ghacks-user.js#445] opened 2018-06-06 12:38 UTC
Hi,

this morning after trial and error I found out that RFP is causing some issues on photos.google.com.
When the main site loads it usually only show grey placeholder instead of the library. Sometimes it might work, but after a (couple of) reload(s) it breaks again. I've narrowed it down to being an RFP issue. When i set "privacy.resistFingerprinting" to false it works.

In your "Prefs vs Recommended Extensions: Co-Existance+Enhancement | Conflicts" I read up on how to set CanvasBlocker, but I can't seem to get it to work:

strategy:

    set CanvasBlocker to fake. Do NOT set to block as this will disable the API and you will not get the same result as RFP.
    block sites when prompted: RFP takes over and CB is never used
    allow sites IF you must: RFP allows CB to take over which will fake
    use a CB whitelist for sites that MUST have the real thing

I want to leave RFP on (for obvious reasons), but how do I allow only photos.google.com to not use RFP or even better set it in a less restrictive way?

First I put photos.google.com to the CB whitelist, while leaving CB on fake readout API
Then I also allowed "Extract Canvas Data" using the site permissions
And I tried "Allow only whitelist" in CB with the site set in whitelist.

Using Firefox 60.0.1 on Win10 and latest GHacks user.js, but also tested with a clean firefox profile and using a custom user.js that only has the "privacy.resistFingerprinting" set

**Comment by Thorin-Oakenpants** [comment] 2018-06-06 14:01
What version of CB are you using?

https://www.google.com/photos/about/ - I don't have a login account, so I'm not sure how I can test this. Is the problem once you log in and have created albums and uploaded photos or something? Sorry for my ignorance - but could you give a little more info on STR (I will set up an account if I have to)

**Comment by bitpixl** [comment] 2018-06-06 14:29
CB 0.4.5c (latest) and yes it requires an (google) account.

What happens is that the "main page" that loads shows an overview of the photos by date, but as all grey placeholders. When I switch to "albums" on the left it can also show up as grey or that works. Sometimes it requires flipping back and forth between "photos and albums" to show the albums pics. It's pretty weird imo, somehwat inconsistent. But it always works when RFP is off.

Not sure what you mean with STR?

**Comment by Thorin-Oakenpants** [comment] 2018-06-07 02:00
> Not sure what you mean with STR?

STR = Steps To Reproduce. I just wanted more precise instructions, which I now have. I'll set up an account and have a play

**Comment by fmarier** [comment] 2018-06-07 19:34
> this morning after trial and error I found out that RFP is causing some issues on photos.google.com.
When the main site loads it usually only show grey placeholder instead of the library.

If you can reproduce this problem reliably, I'd say it's worth filing a bug against Firefox directly. There's a team at Mozilla that's working to make that feature better.

To do that, here's a [direct link](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=DOM:%20Security) that will create a bug against the correct "Product" and "Component" (`Core`, `DOM: Security`).

**Comment by bitpixl** [comment] 2018-06-08 14:20
@fmarier thanks for your input. Is there any chance any of you already have an account at bugzilla.mozilla.org and is willing to report this?

**Comment by fmarier** [comment] 2018-06-08 15:43
You can sign into bugzilla with your GitHub account by the way, no need to create an account just to file a bug.

**Comment by bitpixl** [comment] 2018-06-08 16:12
@fmarier I don't know if it's just (the paranoid) me, but I'm not a fan of linking accounts on different platforms. I'll just create an account, might be useful again in the future.

**Comment by Atavic** [comment] 2018-06-08 18:51
^ Yes, that's a safer option. In the case one of the database accounts get hacked, all the other accounts may be lost.

**Comment by Thorin-Oakenpants** [comment] 2018-06-09 04:32
- FF60.0.1 (I will test nightly soon since some RFP canvas + extension things landed)
- Nilla profile

Albums seem to be fine regardless of RFP
![01-albums](https://user-images.githubusercontent.com/16656956/41187655-d4090872-6b9d-11e8-95e1-5a758438c808.png)

Pictures without RFP
![02-pics-rfpoff](https://user-images.githubusercontent.com/16656956/41187660-e72a58fc-6b9d-11e8-8007-9738c52eabc0.png)

Pictures with RFP
![02-pics-rfpon](https://user-images.githubusercontent.com/16656956/41187663-f1604408-6b9d-11e8-9fd3-b4f111fa9c36.png)

More to follow

**Comment by Thorin-Oakenpants** [comment] 2018-06-09 04:41
^^ Will test in Dev/Nightly. Not convinced it's a "Canvas" issue here

**Comment by Thorin-Oakenpants** [comment] 2018-06-09 04:51
I just tested in Nightly (the last update was about 2 days ago) and the same thing happened. But I forgot to test if allowing an exception made a difference, so I restarted - and without thinking, I also updated (because I wanted to get the Nightly version from Help>About). And now it looks like its fixed

Nightly 62.0a1 (2018-06-08) with RFP=true and no site exception, it's all working. NFI what bugzilla or change fixed this

**Comment by bitpixl** [comment] 2018-06-09 06:52
@Thorin-Oakenpants Thanks for testing and I'm glad to see you were able to reproduce the issue.
I'm also glad to see it's fixed in the latest Nightly :+1:

**Comment by Thorin-Oakenpants** [comment] 2018-06-09 08:55
I'd really like to know/find the bugzilla for this. Anything that affects RFP should be documented but I'm F'd if I can find it (and I can't believe anyone would be changing/coding it without Tor Uplift knowledge) - that's assuming anyone even realizes the bug existed and it didn't just fix itself due to something else being fixed or rolled back.

**Comment by tomrittervg** [comment] 2018-06-11 16:20
I reproduced this in 61.0b9 and 61.0b12.  b9 both were intermittently broken/working.

It doesn't seem related to canvas. I compared the HTML when it's working vs not and it's not loading the background image when it's not working. It's not even making the network request.

I tried using mozregression (https://mozilla.github.io/mozregression/install.html ) which is great for figuring out when Mozilla broke (or fixed) something - but found that I could reproduce it today in Nightly 2018-06-11

**Comment by Thorin-Oakenpants** [comment] 2018-06-11 23:03
Thanks Tom. Welcome to our little world. I'll leave this in your capable hands :)

Slightly OT: At some stage I suspect we're going to need a standalone barrage of tests to confirm RFP still always works as expected, as some regressions may be hard to spot

**Comment by Thorin-Oakenpants** [comment] 2018-08-17 08:45
Closing this. Mozilla know about it

**Closed by Thorin-Oakenpants** 2018-08-17 08:45 UTC
Labels: firefox bug
