### ISSUE TITLE
EvilCorp™ AMP

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#424] opened 2018-05-18 03:32 UTC
:tractor: :  @forteller said

No one has said anything about my comment above. IMO it's a very important privacy extension, so let me quote myself:

> I would like to recommend adding the extension  [Redirect AMP to HTML](https://addons.mozilla.org/firefox/addon/amp2html/) | [GitHub](https://github.com/da2x/amp2html) . Google is trying to gather as much information about everyones browsing habits as possible, and to eat up as many web services as possible. Now they've gone so far as to host other peoples content for them. This is very destructive to the web, and your privacy. Read more about it here: https://danielmiessler.com/blog/google-amp-not-good-thing/
> 
> This extension redirects you away from AMP, so you don't use it yourself and don't link others to it when sharing the link. It's very important to send the message to newspapers and everyone that we don't want Google to own the web, we don't want AMP.
> 

---

:small_airplane: @Thorin-Oakenpants said "does this actually increase privacy" - in other words, does this fit being in the repo

---

:ambulance: : @earthlng said

> @forteller thanks for mentioning it again, I totally missed your original comment.
> 
> AMP sounds absolutely appalling but what else can you expect from Google. I completely agree with everything written in your linked article. Thanks for the link
> 
> > This extension redirects you away from AMP
> 
> unfortunately only after you visit the AMP site because it has to get the non-AMP link from the source code. Still useful when you bookmark a site though, for example.
> 
> > and don't link others to it when sharing the link.
> 
> this is probably the main reason to use the extension. It's not just about mobile either, Pants.
> 
> github: https://github.com/da2x/amp2html
> 
> it's a single contentscript injected into all http(s) sites and runs at document-end.
> There are 3 parts to it:
> - redirect away from AMP sites
> - modify links on news.google.*
> - modify links on google search
> 
> I never use anything google and don't share a lot of links so I don't have much use for the extension but if it can help that potentially fewer people link me or anyone else to AMP and thus google servers, I'm all for recommending it. Anything we can do to fight back against the evil G gets a :+1: from me

**Comment by Thorin-Oakenpants** [comment] 2018-05-18 03:39
food for thought: Privoxy: https://old.reddit.com/r/privacy/comments/8k99c6/skip_googlecomamp_links/ - but... not everyone has privoxy, and its old (years since its been updated, not a good sign) and a PITA to be honest.

Anyway .. enjoy this issue about what to do with AMP. Do we create a new wiki page for "other interesting extensions", or try and sammich something into the existing page (clutter, feature creep?) - because AFAIConcerned, the extension doesn't fit what we're trying to do = i.e no real added privacy (it still connects to EvilCorp and edge cases of sharing links is probably minute, but growing)

**Comment by claustromaniac** [comment] 2018-05-18 04:02
What about Redirector? If what they say in that reddit post is true, I think a simple wildcard pattern will do the trick. Am I missing something here?

**Comment by Thorin-Oakenpants** [comment] 2018-05-18 04:06
Bit of a nuclear option (and we can have multiple solutions) - block links to AMP  - is this it? -> `google.com/amp/s/` - redirect or block. Must be something for uBO / uM, user scripts... 

Or could the script or extension be amended (as an option) so that it provides a "security dialog" before connecting (and maybe highlight AMP links if possible) - eg like uBO with its blocked page that still allows you to continue

Need some test links etc too

**Comment by Thorin-Oakenpants** [comment] 2018-05-18 04:11
Question: If I go to `example.com` (which uses AMP), does this mean the site automatically uses the AMP servers (google), i.e it doesn't have to be a link, it could be I typed it in, but the webpage uses the src=AMP or whatever. And if so, does the content show as coming from google (eg as 3rd party)?

Full disclosure: i an a noob

**Comment by Thorin-Oakenpants** [comment] 2018-05-18 04:46
why on earth is my post dated earlier after claustro's

![wottheheck](https://user-images.githubusercontent.com/16656956/40216478-69f48ba8-5a56-11e8-8995-a6d7e76d7935.png)

**Comment by forteller** [comment] 2018-05-18 10:10
> it still connects to EvilCorp and edge cases of sharing links is probably minute, but growing

People share links on Reddit, Twitter, Fb, Mastodon, etc _all the time_. I don't see how this is an edge case. AMP gets spread like wildfire, or we stop it at the source and noone else who sees the tweet or retweet or the like gets the "infection" or spread it ever further.

**Comment by claustromaniac** [comment] 2018-05-18 18:51
> redirect away from AMP sites

It does this after you connect to the server and fetch the page, which makes this mostly irrelevant from a privacy standpoint. I say _mostly_ because it will still help prevent users from sharing AMP links by showing the actual site in the URL bar, and it also helps prevent bookmarking AMP pages, as earthlng said.

> modify links on news.google.*
> modify links on google search

That's the most significant benefit. The _source_ of the problem, as @forteller called it. But it only helps if the user uses these Googe services in the first place (because the extension won't sanitize links anywhere else). 

So, if I understood correctly, this extension does more to protect everyone else's privacy than your own. If that's the case, I would only recommend this to Google users, which I don't think would be very effective since most Google users don't give a shit even about **their own** privacy. To prevent you from visiting an AMP page (shared by someone else) by "accident", you would need to take **other** measures. amp2html won't be of much help in those cases.

The reddit post :jeans: shared above mentions a failed attempt at protection using Skip-redirect + _"a site block add-on"_. I'm assuming Skip-redirect doesn't cover AMP's rather uncommon schema, and I don't know what's the "site block add-on" that guy tried, but if the AMP schema is always consistently `google.com/amp/s/*realsite*`, a Redirector or uBlock/uMatrix rule should be enough. We'll have to put this to test...

**Comment by Thorin-Oakenpants** [comment] 2018-05-18 19:25
> People share links on Reddit, Twitter, Fb, Mastodon, etc all the time. I don't see how this is an edge case. 

I said case*s* (plural), and I said growing (due to increase in mobile devices/users and uptake of AMP and google search engine). Personally I have never come across any AMP links, but I am just one person. So are you. Don't get me wrong, I think this is horrible, and it will grow. 

Here's how I see it: 99.9999% (at a guess) of the non-google provided links on the web aren't AMP. It's recently new'ish tech (about 2+ yrs?) and requires uptake from web sites. The extension still provides google with info

The problem is google. It dishes out the links to mobile users. The problem is all the users who share these links from google search etc. From a privacy standpoint, all we can do is BLOCK any such connections.

>  this extension does more to protect everyone else's privacy than your own

Exactly. And it won't have an effect IMO (google is too big) - it's like the cloudflare MitM BS'ery. Not much we can do about it except protect *ourselves*

**Comment by earthlng** [comment] 2018-05-18 20:00
https://encrypted.google.com/ was apparently killed April 2018.

found a couple links:

1. https://www.google.com/amp/ethereumworldnews.com/amp/cardano-price-400-increase-month-ada-headed

redirects me to https://www.google.com/url?q=https://ethereumworldnews.com/cardano-price-400-increase-month-ada-headed which in turn redirects to the non-AMP version of the article.

Maybe it's because google sees the Firefox user-agent and that's why I'm not getting the cached google version nor the AMP-ed version of the site itself.
Also note that the link doesn't contain `/s/` after `/amp/` so a Redirector rule would need to deal with that.

2. https://www.google.com/amp/s/www.usmagazine.com/celebrity-news/pictures/justin-timberlake-jimmy-fallons-bromance-through-the-years/amp/

redirects me directly to the non-AMP version at https://www.usmagazine.com/celebrity-news/pictures/justin-timberlake-jimmy-fallons-bromance-through-the-years/ (note the missing `/amp/` at the end).
So, again, not getting the google cached version nor the AMP-ed version.

3. AMP: https://www.washingtonpost.com/amphtml/news/post-nation/wp/2017/01/16/the-d-b-cooper-case-baffled-investigators-for-decades-now-scientists-have-a-new-theory/
non-AMP: https://www.washingtonpost.com/news/post-nation/wp/2017/01/16/the-d-b-cooper-case-baffled-investigators-for-decades-now-scientists-have-a-new-theory/

It seems to be mostly a mobile problem after all and mostly when people use google search or news.
And the extension does nothing to prevent hitting google servers for links to `google.com/amp/` so an additional Redirector or Request Control rule would be nice.

**Comment by earthlng** [comment] 2018-05-18 20:03
my attempt at a Request Control rule for skipping `google.*/amp/` links: http://pasted.co/435407db/fullscreen.php?hash=f74f7af9ad00b68a068385b91a5d7acd&toolbar=true&linenum=false

**Comment by crssi** [comment] 2018-05-18 22:03
Additional two samples:
[https://www.engadget.com/amp/2018/05/10/marvel-avengers-infinity-war-guardians-design/](https://www.engadget.com/amp/2018/05/10/marvel-avengers-infinity-war-guardians-design/)
[https://www.google.com/amp/s/www.forbes.com/sites/gordonkelly/2018/05/02/apple-ios-11-3-1-iphone-battery-problems-iphone-new-battery-ios-upgrade-ios-11/amp/](https://www.google.com/amp/s/www.forbes.com/sites/gordonkelly/2018/05/02/apple-ios-11-3-1-iphone-battery-problems-iphone-new-battery-ios-upgrade-ios-11/amp/)

Also note that, if there is `/amp/` in the URL, you mostly get mobile version of page (at least here its 100% hit), so it is really annoyance when opening URL on a desktop FF and getting the mobile version of it.

**Comment by claustromaniac** [comment] 2018-05-18 22:44
Thanks for the examples guys!

Here's my first attempt at a Redirector rule for this... it really made me wish that Javascript supported lookbehinds :crying_cat_face: 

**Include pattern:** `www\.google\.[^/]+/amp(?:/s)?/(?:(.*/)amp/(.*)$|(.*))`
**Redirect to:** `https://$1$2$3`

It covers all `www.google.*/amp*` cases mentioned above. I think I may end up using additional rules to cover different cases.

**Comment by earthlng** [comment] 2018-05-19 12:34
your pattern would not match the washingtonpost link when served by google.
And it's probably not really an issue but it would match www.google.foobar.com/amp/... That's why I prefer RC in this case because it has better and easy TLD support.
I didn't try to redirect to non-amp versions of links because IDK if it's mandatory that sites use /amp/ or /amphtml/ as names for their AMP sites. IMO the extension (or the script as a userscript) can deal with that more reliably if people want to always use non-AMP versions of sites. Using it as a userscript also makes it easy to exclude certain sites where people prefer the AMP version for whatever reason.

**Comment by Thorin-Oakenpants** [comment] 2018-05-19 13:05
Slightly OT: I *knew* it ... https://old.reddit.com/r/privacy/comments/8kjlft/google_removes_dont_be_evil_clause_from_its_code/ - so EvilCorp™ not even trying to hide the fact now

PS: I know I have things locked up, but that gizmodo link sucks donkey's balls - it keeps reloading every 2 seconds and races my CPU and my temps spike up into the 90's. I wonder what causes that (not, screw gizmodo)

**Comment by claustromaniac** [comment] 2018-05-19 18:33
@earthlng I know that. It would be easy to make it match the washingtonpost link and similar ones in addition, but I wanted to make it somewhat strict. I could use something like this instead:

    ://[^/]+/amp(?:html)?(?:/s)?/(?:(.+/)amp/(.*)$|(.*))

But that would be even more prone to match stuff that it shouldn't. I'd rather use multiple stricter rules, I think. 

I'll take a look at RC, anyway. Thanks :+1:

**Comment by Atavic** [comment] 2018-05-19 20:57
*Accelerated Mobile Pages* project lists [a few case studies](https://www.ampproject.org/case-studies/), one of them is `www.washingtontimes.com` that's redirected to `amp.washingtontimes.com`

**Comment by claustromaniac** [comment] 2018-05-19 21:32
Apparently, [the schema was updated a couple of years ago](https://developers.google.com/amp/cache/overview#amp-cache-url-format). I guess the samples mentioned here still work because they are older.

According to the official documentation the full schema nowadays goes like this:
`https://example-com.cdn.ampproject.org/c/s/example.com/amp_document.html`

This is starting to make me want to puke.

**Comment by Thorin-Oakenpants** [comment] 2018-05-20 13:43
OT: claustro: I need a regex that detects 3 instances of " - " in a string (thats: space hyphen space)

**Comment by Thorin-Oakenpants** [comment] 2018-05-20 16:03
^^ Sweet. FYI: It's a filename delimiter. Cleaning up someone else's music and they are meant to have either four fields or two (they spent months checking it all in their own time, and I have run scripts etc to check). I have stripped all tags. If they have four fields I can tag one way, then load the entire lot, remove those with tags, and tag the rest as two fields. (And yes compilation albums are in a different directory and have yet a third pattern)

I can just use [Everything](https://www.voidtools.com/downloads/) with the above regex, select all, drag n drop into mp3tag, and apply. Now everything left with no tag (I can reload the whole lot and sort by tag fields) should be two fields, select and tag them in one hit. Job done. And yes, I can spot check for mismatched fields - eg text in a trackno field :)

**Comment by claustromaniac** [comment] 2018-05-20 16:38
Ah yes, Everything. I've been using it regularly for quite some time :) It's a real time saver.

**Comment by claustromaniac** [comment] 2018-05-21 22:03
So... I've been reading on how this AMP thing works, and there seems to be no hard standard on how the URL schemes should be for AMP versions of webpages. Moreover, the [AMP HTML specification](https://www.ampproject.org/docs/fundamentals/spec#the-amp-html-format) doesn't require the existance of non-AMP webpages at all! 

The only 100% reliable way to retrieve the URL for the non-AMP version of webpages is by reading it from the canonical link tag in the AMP HTML document, which of course, if attempted programmatically, can only happen **after** the client hits the EvilCorp servers for the AMP document (and by then it's kind of late to worry about your privacy).

This means that the approach amp2html takes is, sadly, justified. The fact that the extension can't help much when dealing with links shared by others (or otherwise found anywhere else in the net), is not a design flaw, but rather the only reliable thing there is to do ATM.

The only way I can think an extension would be able to reliably redirect users without connecting to EvilCorp servers first, would be if it had access to a list (internal or otherwise) of AMP websites and their non-AMP counterparts (if any). This is _theoretically_ doable, but would be a pain to maintain, and it would take some serious brains to design such a list in a sufficiently efficient manner. I mean, one thing is to list a certain number of known tracking/advertising/malware _domains_, like blocklists do, and another thing is to list sites, or even webpages, of ANYTHING. Plus, the list will grow exponentially over time.

If someone can prove me wrong, **PLEASE** do it. I'm begging you.

**Comment by Thorin-Oakenpants** [comment] 2018-05-22 07:56
> It's not a design flaw

I was just interested in a uBO style block, which then lets you proceed if you wish to. That said, I never click on links without seeing where they're going first (FF's overlay info for hyperlinks when mousing over them), although I think some links can be hidden (i.e no info when mouse-over).

EvilCorp™ is abusing their power here (surprise!) since AMP pages get a rankings boost for being AMP.

It's disgusting that a handful of tech companies are hogging all the traffic and/or have their finger in almost every pie.  And then the data sharing/buying (not just all the data brokers, but the likes of FB *buying* information from eg retailers). Its like the last 6 or 7 years have been a free-for-all get-all-data-at-all-costs and 95% of the world doesn't give a :hankey: 

Anyway, where are we at?
- add the extension to the wiki? (I think its a waste of time *for us*)
- add a redirect rule? (it may catch most of it at least for now)
- give me a uBO or uM block rule godamnit!! <-- this is what protects **YOU**, screw everyone else, we can't save everyone

**Comment by earthlng** [comment] 2018-05-22 13:56
> only happen after the client hits the EvilCorp servers for the AMP document

AFAIK the AMP document is only served by EvilCorp cache servers for `google.com/amp/...` links.
If you visit https://www.washingtonpost.com/amphtml/news/post-nation/wp/2017/01/16/the-d-b-cooper-case-baffled-investigators-for-decades-now-scientists-have-a-new-theory/ directly and don't allow the 3rd party script from ampproject I don't see how EvilCorp servers would be hit.

My RC rule should reliably skip google-amp links and redirect directly to the site. After that, people who prefer to see the non-AMP version of that site can use the extension for auto-redirect, or just manually remove the /amp/ or /amphtml/ or whatever it may be from the URL.

AMP as a tech is not bad per se, only the caching and how EvilCorp up-ranks AMP sites is shady AF.
And of course the custom elements don't work when you block the 3rd party script so there's that too.

As for the link sharing, EvilCorp actually encourages browser devs to skip their shady links when sharing them, see fe https://bgr.com/2017/08/24/ios-11-features-safari-google-amp-links/
IDK if that means it will always copy the link to the non-AMP (canonical) version of a site or just remove the `google.com/amp/` part.

**Comment by claustromaniac** [comment] 2018-05-22 16:39
@earthlng OK I put together what I've been reading so far and it seems you're right and, if my understanding is correct, it also looks like EvilCorp is aiming to implement [some nice changes](https://amphtml.wordpress.com/2018/01/09/improving-urls-for-amp-pages/) this year. If they do what they say in that WP blog, we won't need to redirect requests because there won't be separate links for AMP content anymore.

I think what confused me the most is that they have made a lot of radical changes to this thing over time. But it seems I can relax for now. Thanks!

@Thorin-Oakenpants 
I think something like this would be good enough in uBO

    ||google.*/amp/*$document

earthlng's RC rule looks good too, and both of my Redirector rule examples get the job done, but the second one is theoretically more likely to produce unwanted results.

**Comment by claustromaniac** [comment] 2018-05-22 22:33
uBlock rule to block using a regex (more accurate than the above):

    /(?=.+\/amp\/)www\.google\.[a-z]{2,3}(?:\.[a-z]{2})?\/amp\//$document

I know... I'm a regex junkie.

**Comment by claustromaniac** [comment] 2018-05-28 18:17
OT: @earthlng, I gave RC a whirl and I have to say it's pretty amazing. It's not the most intuitive thing in the world, but it's well documented and the fact that the manual is so easily accessible is great. It has left me without reasons to keep using Redirector. 

I'm not sure why I didn't check it out earlier. Probably laziness (took a while to rewrite all my rules).

**Comment by crssi** [comment] 2018-05-28 20:13
RC is missing just one think from my point of view to be perfect, and that is the option to not, or only to apply the rule when source/destination is on same domain/subdomain.

**Comment by Thorin-Oakenpants** [comment] 2018-05-29 01:56
I'm shit at writing rules. But since FF56'ish I've had both Redirector and Request Control. Redirector is empty and been disabled the whole time. They both look very good, but since I don't really use them that much, as in develop rules for them, I have no idea of their respective powers. RC seems easier for me to use as a n00b

**Comment by earthlng** [comment] 2018-05-29 14:22
@claustromaniac 

> It has left me without reasons to keep using Redirector.

IMO both can be useful sometimes. What I like most about Redirector is the control over processing ("Process matches") which RC doesn't have (or rather RC does some of it automatically in some cases).
But so far I haven't come across a case where I needed that and atm I have no rules in Redirector.

A while ago Pants asked *Does Request Control offer anything that Redirector doesn't or vice versa?* and [this](https://github.com/ghacksuserjs/ghacks-user.js/issues/149#issuecomment-310841927) was my assessment at the time (a few things have changed since then fe console output can now be disabled in Redirector, RC now has import/export, etc)

**Comment by bitpixl** [comment] 2018-05-30 17:26
@claustromaniac I'm not using RC or Redirector atm and I'm trying to keep the extensions to a minumum.
does your custom uBO rule have the same effect as the Redirector one?

**Comment by claustromaniac** [comment] 2018-05-30 22:04
@bitpixl Not exactly. The last Redirector rule I posted takes you, for example, from any of the following:

    *anything*google.com/amp/canonical.com/real/path/
    *anything*google.com/amp/canonical.com/real/path/amp/
    *anything*google.com/amp/s/canonical.com/real/path/
    *anything*google.com/amp/s/canonical.com/real/path/amp/
    *anything*google.com/amp/s/canonical.com/real/path/amp/something/else/
    *anything*google.co.uk/amp/s/canonical.com/real/path/amp/something/else/
    *anything*google.etc/amp/s/canonical.com/real/path/amp/something/else/

to either `https://canonical.com/real/path/` or `https://canonical.com/real/path/something/else/` (where appropriate).

The uBO filter uses the same pattern, but blocks instead of redirecting. You'll get one of these messages (but with the appropriate description, etc):

![Sorry, I'm too lazy to take a screenshot](https://cloud.githubusercontent.com/assets/585534/8160013/14466ca0-133a-11e5-8d3c-28169288f35a.png)

**Comment by bitpixl** [comment] 2018-05-31 07:42
@claustromaniac Well I guess the uBO rule is out of the question then, as it will become a big annoyance.
I have noticed that Skip Redirect extention does take care of [https://www.google.com/amp/ethereumworldnews.com/amp/cardano-price-400-increase-month-ada-headed](url), so that leaves me with the url that contain /amp/. I'm wondering if the Neat URL extension can filter out /amp/.

**Comment by claustromaniac** [comment] 2018-06-09 16:19
> I have noticed that Skip Redirect extention does take care of https://www.google.com/amp/ethereumworldnews.com/amp/cardano-price-400-increase-month-ada-headed, so that leaves me with the urls that contain /amp/, something Skip Redirect can't handle sadly.

I tested this a while back and can confirm it. Considering AMP pages don't need to have canonical counterparts, you're probably better off using just Skip Redirect, anyway. You don't need an uBO/Redirector/RC rule if that's the case. 

Skip Redirect should be enough to prevent you from connecting to EvilCorp directly (as a first party). If you also want to avoid AMP pages because you're on desktop/laptop/whatever, the Redirect AMP to HTML extension is the best option for that. Using them together should give the best results.

After thinking it through, I can't recommend the Redirector rule as I wrote it. It's bound to break pages sooner or later. This should be safer:

**Pattern:**

    (?=.+/amp/)www\.google\.[a-z]{2,3}(?:\.[a-z]{2})?/amp(?:/s)?/(.*)

**Redirect to:** `https://$1`

However, I repeat: if you use Skip Redirect you don't need _any_ of the rules mentioned here.

**Comment by bitpixl** [comment] 2018-06-10 06:53
@claustromaniac thanks for the info. As I'm just not that skilled creating my patterns I'm going to follow the KISS (keep it simple stupid) rule and keep on using Skip Redirect. I'm guessing Skip Riderect does essentially the same and has those patterns and/or rules build in.

**Comment by crssi** [comment] 2018-06-10 10:20
@bitpixl if you prefer, as I do, the "kiss" method, then [Redirect AMP to HTML](https://addons.mozilla.org/firefox/addon/amp2html/) is the way to go, IMHO.
And "Skip Redirect", with a bit of tweaking, is also a must keeper.

**Comment by bitpixl** [comment] 2018-06-10 11:18
@crssi I've added the addon, thanks for the direct url. btw, you can't say "with a bit of tweaking, is also a must keeper" and then not explain it, thats just teasing ;)

**Comment by crssi** [comment] 2018-06-10 12:10
Doh, I have express myself wrongly. What I have meant is that it is a keeper as is and I have added/changed some parameters... [see here](https://github.com/crssi/Firefox/blob/master/user-overrides.js)

**Comment by Thorin-Oakenpants** [comment] 2018-08-17 08:30
Do we need to keep this open, or add anything to the wiki (scripts, extensions list etc). If I don't hear anything, I'll just close the issue.

**Comment by earthlng** [comment] 2018-08-17 17:25
Don't close it yet, I think this deserves some kind of resolution. I've hidden a couple of comments as Offtopic because there's has been a lot said and discussed in this issue.

I'll eventually summarize all the various solutions we've come up with and then we can decide if and where we want to link to it.

**Comment by Thorin-Oakenpants** [comment] 2018-08-22 16:45
Interesting read: https://digitalcontentnext.org/wp-content/uploads/2018/08/DCN-Google-Data-Collection-Paper.pdf

**Comment by Atavic** [comment] 2018-08-24 16:19
I'm watching [this extension](https://github.com/da2x/amp2html), has anyone toroughly tested/used it yet?

**Comment by crssi** [comment] 2018-08-24 17:32
@Atavic  I do, have no complaint. I works as it should and never noticed any side effects.

**Comment by Thorin-Oakenpants** [comment] 2018-08-24 18:00
but why? ^^ `https://github.com/da2x/amp2html/issues/7`

**Comment by Thorin-Oakenpants** [comment] 2018-09-07 23:19
FYI: some light reading
- Article: https://www.polemicdigital.com/google-amp-go-to-hell/
- Followup article (by someone else): https://sonniesedge.co.uk/posts/amp-urls/
- Reddit discussion: https://old.reddit.com/r/firefox/comments/9dudod/the_mysterious_case_of_missing_urls_and_googles/

**Comment by Atavic** [comment] 2018-09-08 18:11
Issues with AMP As a Publisher:
https://www.alexkras.com/i-decided-to-disable-amp-on-my-site/

**Comment by Thorin-Oakenpants** [comment] 2018-09-20 19:50
FYI: https://arstechnica.com/gadgets/2018/09/bing-starts-serving-amp-pages-as-google-prepares-to-reduce-its-control/

**Comment by Thorin-Oakenpants** [comment] 2018-10-09 14:46
earthlng said
> I'll eventually summarize all the various solutions we've come up with and then we can decide if and where we want to link to it.

Something to put in the wiki when you're ready

[gorhill source](https://old.reddit.com/r/firefox/comments/9mnkt3/seeing_more_and_more_amp_links_being_shared/e7g4s8j/)
> If using uBO, wholesale blocking ampproject.org should work too? Result is no redirection, benefit of AMP without needing AMP servers:
```
||ampproject.org^
||cdn.ampproject.org/v0.js$script,redirect=ampproject.org/v0.js
```

**Comment by Thorin-Oakenpants** [comment] 2018-10-09 19:06
Don't shoot the messenger bro :) Just dumping the info here for consideration. Maybe @gorhill can expand it, IDK - all over my head

**Comment by gorhill** [comment] 2018-10-09 20:10
> benefit of AMP

By this I mean a page not bloated by 3rd parties.

**Comment by gwarser** [comment] 2018-12-14 21:20
Thanks. Claustromaniac [message](https://github.com/ghacksuserjs/ghacks-user.js/issues/424#issuecomment-390796782) confirmed my assumptions - there is no way to reliably detect AMP by URL. Fortunately the biggest players follow some patterns (for now).

**Comment by publicarray** [comment] 2019-01-01 20:56
To confuse everyone scrips, Cloudflare has their own amp cache. https://www.amp.cloudflare.com

**Comment by Thorin-Oakenpants** [comment] 2019-03-27 05:42
[Everything Is AWESOME!!!](https://arstechnica.com/gadgets/2019/03/google-brings-amp-to-email-turning-your-inbox-into-an-app/) <sup>1</sup> /s

[1] https://en.wikipedia.org/wiki/Everything_is_awesome

**Comment by Thorin-Oakenpants** [comment] 2019-04-17 03:42
more BS from google - https://www.theverge.com/2019/4/16/18402628/google-amp-url-problem-signed-exchange-original-chrome-cloudflare - yeah, lets HIDE the real URL info

**Closed** 2019-05-07 11:41 UTC
Labels: needs jesus

**Comment by claustromaniac** [comment] 2019-07-16 15:22
https://reclaimthenet.org/google-uses-auto-generated-amp-pages-that-likely-reduce-the-likelihood-of-users-clicking-out-of-google/

**Comment by aesthicc** [comment] 2019-08-04 01:13
[A letter about Google AMP](https://github.com/amp-letter/amp-letter.github.io)
