### ISSUE TITLE
FPI + some site exceptions broken [depending on settings]: FF69+ [1556212]

### ISSUE THREAD

**Issue by seanob86** [ghacksuserjs/ghacks-user.js#783] opened 2019-09-03 15:57 UTC
Thorin: read https://bugzilla.mozilla.org/show_bug.cgi?id=1556212

---

In 68 I blocked all cookies but maintained a list of domains to either allow cookies or allow as session only. This was achieved in the FF built-in preferences.

In my overrides I simply block all cookies via this pref: `user_pref("network.cookie.cookieBehavior", 2);`

Just updated to 69 and the per domain cookie permissions to either allow or per session seem to be broken. What I mean by this is the following:

68 behaviour: create a cookie permission to allow session only cookies for facebook.com. I am able to log in to facebook.

69 behaviour: same permission as the above but facebook now prompts me that I need to enable cookies. In the 'i' button to the left of the url bar and viewing the 'cookies' option to see what is being blocked and allowed, and I can see that although I have created a permission to allow session cookies for facebook FF is showing that the cookies are being blocked for fb where in 68 it would show as allowed.

For now I have reverted back to the user.js default in blocking all third party cookies.

**Troubleshooting:** 
Fresh nilla profile with no user.js. and set up the prefs manually to just block all cookies and set up a test permission to allow cookies. This worked as per 68 but as soon as I restored the user.js the cookie permissions were being ignored again.

Found this bugzilla which seems to suggest it's linked to FPI. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1556212

I will test (in a moment) whether disabling FPI resolves this issue

EDIT. FPI set to true seems to be the cause.

**Comment by seanob86** [comment] 2019-09-03 16:08
**Confirmed:**

On nilla profile block all cookies and set a site permission for reddit.com to allow session cookies.

<img width="654" alt="Screen Shot 2019-09-04 at 01 04 08" src="https://user-images.githubusercontent.com/45988261/64189894-b9c11100-ce64-11e9-9e74-3e65676b915b.png">

<img width="685" alt="Screen Shot 2019-09-04 at 01 04 17" src="https://user-images.githubusercontent.com/45988261/64189910-c2194c00-ce64-11e9-9b9f-18dca84477d1.png">

FPI disabled as per nilla default:
<img width="364" alt="Screen Shot 2019-09-04 at 01 02 23" src="https://user-images.githubusercontent.com/45988261/64189943-d52c1c00-ce64-11e9-8875-10b813c65e7b.png">

Enable FPI - reddit.com cookies being blocked despite the cookie permissions i set earlier.
<img width="362" alt="Screen Shot 2019-09-04 at 01 03 53" src="https://user-images.githubusercontent.com/45988261/64190012-f7be3500-ce64-11e9-84af-132f2b78d7cb.png">

**Comment by Thorin-Oakenpants** [comment] 2019-09-03 16:19
Set the cookie  permissions when FPI is on, because they are OA'ed (origin attributed)

**Comment by seanob86** [comment] 2019-09-03 16:32
So I created a brand spanking nilla profile to avoid any gotchas to test the OA theory.

- As soon as the new profile loaded I went to about:config and enabled FPI.

- Then into preferences and set the cookie permissions to block all cookies and set a site permission for reddit.com. So i'm assuming that the new permissions should by then be associated to FPI i.e OA.

- Browsed to reddit.com but the cookies are still being blocked.

**Comment by seanob86** [comment] 2019-09-03 16:55
Not sure if this is what I should be looking for... But in the nilla profile I created in my example above (after setting the permissions after enabling FPI), I opened the `permission.sqlite` file and in the `moz_perms` table I can see the following entry `https://www.reddit.com^firstPartyDomain=reddit.com`

**Comment by Thorin-Oakenpants** [comment] 2019-09-03 17:13
`https://www.reddit.com^firstPartyDomain=reddit.com` <- yeah, that's what I'm talking about.

I haven't updated, so if the problem still exists, then f&*^k ... I'll have to have a play when I get there, and also test in 70 to see if it's fixed. Suggest you just sit tight on 68

**Comment by Thorin-Oakenpants** [comment] 2019-09-03 17:40
@tomrittervg Edge case not picked up? when all cookies are blocked `network.cookie.cookieBehavior` = `2`, and FPI is enabled, and site exceptions are blank, and then site exceptions are added (FPI is on), seems like site exceptions are not being respected in FF69. Or something that has been fixed in subsequent patches?

**Comment by tomrittervg** [comment] 2019-09-03 17:46
[Per-Domain Cookie Permissions (and a few other similar oddball permissions) are broken with FPI enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1556212)

**Comment by earthlng** [comment] 2019-09-03 17:48
I did some testing as well and it seems to work if I set the permission via the Page Info panel but only if I choose "Allow" instead of "Allow for session".

**Comment by Thorin-Oakenpants** [comment] 2019-09-03 17:57
^^ Both `allow` and `allow for session` work for me (I did not use reddit). I added the exception via the site info panel.

here's allow for session
![success](https://user-images.githubusercontent.com/16656956/64196750-137d0780-ce74-11e9-874e-7cb25f846772.png)

here's what is added to the exceptions list in the options UI
![stored_exception](https://user-images.githubusercontent.com/16656956/64196764-1841bb80-ce74-11e9-840b-442a9dac5953.png)

I have not tested by adding in the exceptions panel via the options UI

**Comment by seanob86** [comment] 2019-09-04 02:35
Thanks for testing guys!

So I have hacked the sh** out of my `permissions.sqlite` file to get this working the way it used to pre FF69 (obviously took a backup first just in-case it bites me later down the track!).

I changed all my `allow` and `allow for session` rules as per this template directly in the sqlite file >> `https://www.reddit.com^firstPartyDomain=reddit.com`

What I found is that if I add the site exception via the UI (Preferences -- on mac > Privacy & Security > Cookies and Site Data > Manage Permissions and then open the sqlite file, the rule is added without `^firstPartyDomain=xyz.com` for the type `cookie`. Interestingly for `storageAccessAPI` type the rule is added with `^firstPartyDomain=xyz.com`. See below (rule added via UI - Manage Permissions)

<img width="447" alt="Screen Shot 2019-09-04 at 11 18 45" src="https://user-images.githubusercontent.com/45988261/64221163-68903c00-cebb-11e9-9d8e-9c5f5f3afc0d.png">

Manually modifying the above `cookie` rule with the correct OA format is a workaround that seems to be working a treat (so far).

Alternatively, if I try to add the firstpartyDomain rule format directly in the preferences/options UI, it appears in the list as per the below and fails to accept cookies for the desired rule I attempted to add.

<img width="671" alt="Screen Shot 2019-09-04 at 11 31 32" src="https://user-images.githubusercontent.com/45988261/64221417-59f65480-cebc-11e9-9a61-02b113950e7e.png">

**Comment by crssi** [comment] 2019-09-20 08:07
^^My kid is using `https://scratch.mit.edu/` and I am almost 100% sure that in previous versions of FF I have used user.js with "only" WebGL enabled, but now I need to also disable FPI.
Where I can download previous versions of FF for testing?

**Comment by Thorin-Oakenpants** [comment] 2019-09-20 08:14
`has caused quite some regressions` .. gk is so idiomatic at times

**Comment by Thorin-Oakenpants** [comment] 2019-09-20 20:13
> Where I can download previous versions of FF for testing

Depending on the version, you'll want to open them off-line and disable the app update

- https://ftp.mozilla.org/pub/firefox/releases/
- https://sourceforge.net/projects/portableapps/files/Mozilla Firefox%2C Portable Ed./

**Comment by Thorin-Oakenpants** [comment] 2019-10-18 09:37
I don't use containers, and thus I do not use TC in a hardened mode, which I know some of you do

https://bugzilla.mozilla.org/show_bug.cgi?id=1589608  - enjoy ... now your site permissions will per contextid and you'll never remember them when you revisit a site - at least that's how I'm reading it.

**Comment by crssi** [comment] 2019-10-18 11:25
^^ that is not convenient. 😢

**Comment by Thorin-Oakenpants** [comment] 2019-10-21 02:26
OK, so I finally updated from 68 (to 69.0.3) : PS @tomrittervg FYI re dupes and what happened after I removed them

The only items in permissions.sqlite I have are
- type cookies, for a few websites
- moz-extension stuff

🛩 cookies
- so all I did was revisit each of my sites and re-apply the same site exception from the urlbar `i` icon. This adds the proper `^firstPartyDomain=*` notation, and I end up with duplicates
![manage](https://user-images.githubusercontent.com/16656956/67171604-67ea3100-f3a7-11e9-8255-1cec7cc72f29.png)
- With these duplicates, as a test, I deleted one of the non-FPI ones, and my auto-login for the site broke (I didn't test logging in). I might test some more later, but at the end of the day, I only have like 10 exceptions, and I never change any of them, so I'll live with 10 cookie permission dupes for a while

🚚  moz-extension: part 1
- FF68: five extensions, all with three perms: WebExtensions-unlimitedStorage, indexedDB, persistent-storage
- FF69: ended up with lots of different mixes of duplicate entries
   - e.g uBlock Origin duped unlimitedStorage
   - Violentmonkey duped indexedDB
   - Note Taker duped indexedDB and persistent-storage
   - etc
- I removed the newest duplicates, with FF closed using an external app) and restarted and the dupes did not come back, and everything seems to be working fine (but see part2 below)

here's a pic
![WE-dupes](https://user-images.githubusercontent.com/16656956/67172067-6d487b00-f3a9-11e9-97a6-e68871af2069.png)

🚗 moz-extension: part 2
- FF68: two extensions with storageAccess permissions (Window Resizer, Group Speed Dial)
- FF69: those permissions were gone
- everything seemed to work fine though: not that I did any editing/changes
- after I cleaned out the moz-extensions dupes (external app), on the next FF restart I suddenly got those two permissions back, but this time with FPI added, **and** I got a third one, for Violentmonkey

---

Anyway, AFAICT all my extensions (and site permissions which are only cookies and never change) are working

**Comment by seanob86** [comment] 2019-10-21 07:23
> so all I did was revisit each of my sites and re-apply the same site exception from the urlbar i icon. This adds the proper ^firstPartyDomain=* notation, and I end up with duplicates.

It seems on macOS that there is no way to add exceptions via the `i` icon from the urlbar - That or I'm doing something wrong. There are no options within that `i` site information window (on macOS) to add exceptions. I can only view what cookies are being blocked but can't create an exception directly from it. The only other options within that `i` pop up are launching the `Permissions` Preferences or `Content Blocking` Preferences. Therefore the only way on macOS is to open the `Privacy & Security` within preferences and enter the exception manually. The annoying thing is that you cant directly enter `^firstPartyDomain=*` notion as part of the exception as per my previous comment further up on this issue.

**Comment by Thorin-Oakenpants** [comment] 2019-10-21 07:28
does mac not have this?
- click `i` icon (or shield, as the info icon will merge into that)
- click the `>` arrow to the right of the connection
- click `more info`
- click `permissions` tab

I'm still probably going to test why I need duplicates, because when I did [my quick test](https://github.com/ghacksuserjs/ghacks-user.js/issues/783#issuecomment-527569924) earlier in 69 dev, I didn't.

**Comment by seanob86** [comment] 2019-10-21 08:05
> does mac not have this?

OK so it was just me 🤣 I see it now!!!

**Comment by Thorin-Oakenpants** [comment] 2019-10-29 15:52
Note that in FF70+ the `i` info icon is gone. I saw a ticket that said it was merged with the shield. Anyway .. click the `padlock/key` icon
![70](https://user-images.githubusercontent.com/16656956/67784681-093a4c80-fa64-11e9-8677-17c97e68656e.png)

**Comment by Thorin-Oakenpants** [comment] 2019-12-10 22:10
closing this... 69 was two releases ago

**Closed by Thorin-Oakenpants** 2019-12-10 22:10 UTC
Labels: FYI, firefox bug
