### ISSUE TITLE
AMO Add-ons won't install, fake User Agent is locked by RFP

### ISSUE THREAD

**Issue by iWARR** [ghacksuserjs/ghacks-user.js#419] opened 2018-05-09 10:36 UTC
### ISSUE

**addons.mozilla.org** won't install add-ons and asks for a newer version of Firefox.

When RFP is enabled, it forces spoofed UA to FF v52 (the real one is FF v59)
So AMO restricts installation of a new Add-ons.
Troubleshooting with (2662) and (4503) doesn't work.

[Same issue](https://support.mozilla.org/ru/questions/1211549)

### Add-ons Auto-Updates are under the quesion

Probably, Add-ons auto-updating will not work also... This is a big problem.
(Yes, I want have auto-updates turned ON for an Add-ons, instead for the FF itself (notification only).

### TEMPORARY FIX

Disable RFP when istalling Addons.

Test UA: 	[BrowserSpy.dk](http://browserspy.dk/useragent.php)

--------------------------------------------

**P.S.** I didn't saw a "right" discussion on Bugzilla, probably, devs don't undersand how are RFP, UA, AMO interacting in this issue. If you participated user on Bugzilla, you may give them a relevant info.

Note: This issue is not relative to "ghacks-user.js" itself, it's a completely epic fail of Mozilla.
But if you know how to hack this terrible issue, please let me know.

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 11:38
> ~~TEMPORARY FIX~~
> ~~Disable RFP when istalling Addons~~

Just right click on the disabled `Add to Firefox` button and "Open Link in New Tab" . You can also just drag the button to the urlbar

> Probably, Add-ons auto-updating will not work also...

No issues here. Addon updating/checks work perfectly fine (as does application updates/checks).

Mozilla have known about this for a long time. Some genius TOLD them [https://bugzilla.mozilla.org/show_bug.cgi?id=1333933#c2](over a year ago) that this would happen. Anyway, there is a bugzilla for it - [1394448](https://bugzilla.mozilla.org/show_bug.cgi?id=1394448)

Note: since the UA spoof uses the current ESR, FF60-66 will spoof as 60. Due to most web extensions being FF57+, this is significant regards the number of extensions that AMO says you can't install (in fact it should eliminate most of them). That's not to say that some extensions can still be marked as incompatible due to UA spoofing (I think extension developers can set minimum version numbers in their manifest or something)

**Closed by Thorin-Oakenpants** 2018-05-09 11:38 UTC

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 11:53
> it's a completely epic fail of Mozilla.

No it's not. The fix is not trivial (if it was, it would have been done). It's just not high priority. The RFP pref is not front facing (no UI), has not been pushed/advertised by Mozilla, and has not had a proper trial (shield study: well there was one in which it was tested as part of a dozen prefs they looked at overall for privacy), and has not even been flipped on in PB Mode

in other words .. if someone wants to change a pref that Mozilla themselves aren't ready to, then that's on them to know the consequences: although the user.js does not specifically mention this issue with AMO, it clearly states the UA Spoof, which you found - and the red warning message on AMO is a dead giveaway - in fact you found a workaround after asking for one :)

PS: welcome to the world of testing stuff .. along the way we've had canvas issues, extension problems, keyboard key issues

**Comment by iWARR** [comment] 2018-05-09 12:35
> its called bleeding edge for a reason

Yeah... After reading ~1 month about FF (? I'm feeling like a supid ?) and prepearing my prefs (instead of the project's great work done), I see now that FF is an "always-brolken-browser". But I'll never back to Opera, becouse it is chromium, so this mean it's a spying combine on the "fields of gold" (C), during harvest time of people's minds.

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 12:40
> I'm feeling like a s(t)upid

There's 3000+ prefs. Web tech is complicated. There's a million+(?) lines of code. I only know what I do because I've been digging into this stuff for years, and I'm only scratching the basics :)

> I see now that FF is an "always-broken-browser"

wot? No it's not. Its standards compliant.

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 12:52
> There's a million+(?) lines of code

https://www.openhub.net/p/firefox/analyses/latest/languages_summary  - ok, so its more than that

**Comment by iWARR** [comment] 2018-05-09 12:56
I'm not going to argue. I will use FF, because I don't see another powerwul and highly customizable alternative I can organise in a safe way. But, remember, I have a "fresh look" at all the things (that is good in most cases). 

Also I'm happy to meet new friends here and VERY appreciated to you for your help and attention. :+1:

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 13:25
We never argue here, its all discussion :+1: 

IMO, a browser is probably the most important application on a computer (on a smart phone, not so much). It's what most people use for emails (web mail), shopping, banking, new/information, socializing etc. *Most* people (think of all those old people crssi helps) probably use it only for emails and a few websites. The younger generation though have had 20+ years to get used to it (and older people die off)

Lets face it, a browser is massive - complexity, standards, security, etc - gazillions of issues and lines of code etc - always changing. And it connects to the internet (OMFG!) .. where danger lies (here be dragons!). So in all honesty .. your choices are limited to those who can deliver on all that

(in no particular order) Firefox, Chrome, Opera, Safari, Edge (and Tor Browser Bundle for the dark web) - that's your choices. And then, maybe forks if you're game (or custom builds of your own). Firefox, hands down, offers an incredible choice of prefs, etc, yada yada yada and is the ONLY choice when it comes to privacy. Nothing else comes close.

Just keep singing out if you have problems, just [RTFM](https://en.wikipedia.org/wiki/RTFM) first :smiley:

**Comment by iWARR** [comment] 2018-05-09 13:39
> Just keep singing out if you have problems, just RTFM first

I'm always pushing RTFM. And try resolve a things with searching (broadly speaking, it's faster).
Trying speak about issues I can't resolve by myself.
I'm not a machine, so, please, be patient to newcomer :)

**Comment by Atavic** [comment] 2018-05-09 13:57
[Linux Kernel](https://www.openhub.net/p/linux/analyses/latest/languages_summary) has less lines.

**Comment by iWARR** [comment] 2018-05-09 14:08
You may put something like that at the head of sticky: extensions #294 thread until FF60+ will come
(feel free to fix my weird English)

> FF57+ : If you experience problems installing Add-ons from the AMO: `addons.mozilla.org`, just right click on the disabled "Add to Firefox" button and "Open Link in New Tab". You can also just drag the button to the urlbar.
> 
> This is an old known issue relative to RFP "privacy.resistFingerprinting" pref and spoofing User Agent to wrong FF version.

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 14:10
> until FF60+ will come

But FF60 is already here. It's listed on the RFP sticky by the way

**Comment by iWARR** [comment] 2018-05-09 14:17
> But FF60 is already here.

Oh! Good news! Checked yesterday, I miss that. Thanks. :)
Playing with troubles take a lot of time...

**Comment by iWARR** [comment] 2018-05-09 16:20
I can add to this issue that "Open Link in New Tab" trick is not working.
"Drag disabled button to urlbar" - works.

Hope, I'll find this solved in FF60.

**Comment by Thorin-Oakenpants** [comment] 2018-05-09 16:49
what extension did "open link in new tab" not work - I came across this before when I was installing a legacy extension on ESR for someone else's troubleshooting - so I suspected it was something else (eg max version number or some other flag) - this is a different issue

gimme the extension link and I'll test my theory

**Comment by iWARR** [comment] 2018-05-09 18:58
You are right, not all of them have installation troubles (for example uBO have no issues at AMO).

I've experience issues with the next ones:

[Cookie AutoDelete](https://addons.mozilla.org/ru/firefox/addon/cookie-autodelete/) , 		[Decentraleyes](https://addons.mozilla.org/ru/firefox/addon/decentraleyes/) , [searx.site](https://addons.mozilla.org/ru/firefox/addon/searx-site/)

Also, I don't see any searX options I expected to have and miss it "as extension" at about:addons page. The install procedure proceeded in some ugly way for me, so I don't know is there no options "by design" or it's the AMO issue. Author (**scroom**) wrote that his extesion based on older one (by **Svetlana Tkachenko**).  The main goal of that (older) extension was controlling options of the searX just through the browser (that supported in the native web UI).

(I'm continue discovering extensions also for my Search Engines issue, but this is offtop here. Soon I'll start posting there. I have a lot of new debloating settings that works successfully. Just for the short info.)

**Comment by Thorin-Oakenpants** [comment] 2018-05-10 07:30
### FF59.x with user.js

Note: i had a test nilla profile one already set up with the user.js, so this is more than just RFP

https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/
^^ This add-on requires a newer version of Firefox (at least version `56.0`). You are using Firefox `52.0`

https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/
^^ This add-on requires a newer version of Firefox (at least version `56.0a1`). You are using Firefox `52.0`

For both: right click > open in new tab, switch to new tab, see message
"Firefox prevented this site from asking you to install software on your computer"
- Note: you can just select the urlbar and hit enter (on the new tab with the notification)

Not 100% sure what causes this. I suspect that dragging the button to the urlbar already knows and has a reference to AMO being open (same tab), whereas open in a new tab loses that reference and blocks it, but on a refresh loads it since the first attempt now has an AMO reference. I have no idea what this is called or caused by, or its some CSP thing or an SRI or black magic wizardry or what.

### FF60.0b16 with RFP (did not load the entire user.js)

No issues at present, because we're spoofing as 60 now and that meets the threshold for those two extensions. BUT, we can still get the issue in future if the extension ups its minimum version for a particular release: eg Decentraleyes (currently requires `56.0a1`) might change that *in the future* due to Web Ext API changes etc to `64` but we still spoof as 60.

---

in FF59 + 60, with or without RFP/user.js

https://addons.mozilla.org/en-US/firefox/addon/searx-site/
^^ does not have any warning but button disabled

right click > open in new tab
- see pic
![searx](https://user-images.githubusercontent.com/16656956/39856957-4840b1c0-5421-11e8-8591-01988b98208a.png)

Whatever is going on with this is not related to the RFP spoof

**Comment by Atavic** [comment] 2018-05-10 19:49
>Install searx as a search engine on any version of Firefox! (javascript required)

The xml shoiuld be added under *options > search*

**Comment by Thorin-Oakenpants** [comment] 2021-12-05 21:56
for example if you go to add Multi-Account Containers, the current version requires FF94 or higher, but we are spoofing as ESR91

**Comment by Thorin-Oakenpants** [comment] 2022-10-11 19:56
RFP no longer spoofs version on desktop FF102+
