### ISSUE TITLE
windows size not remembered [solved RFP, use the 4502 prefs]

### ISSUE THREAD

**Issue by TheWildWolf3** [ghacksuserjs/ghacks-user.js#579] opened 2018-12-09 03:48 UTC
Hello, I have an issue with firefox being vertically condensed, even after resizing it, it becomes condensed again after I restart it. This only happens with your user.js. How can I fix this?

**Comment by claustromaniac** [comment] 2018-12-09 04:16
Possibly a duplicate of #220
See also #449 and #453. Is that what you are referring to?

**Comment by Thorin-Oakenpants** [comment] 2018-12-09 09:19
am on a closing spree ... first post is a little vague (condensed?). Feel free to reopen if your problem is nothing to do with RFP setting browser size on new windows

**Closed by Thorin-Oakenpants** 2018-12-09 09:19 UTC
