### ISSUE TITLE
GM scripts + uBo WE cause stand-alone images to not load etc

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#245] opened 2017-09-26 19:20 UTC
FF and Waterfox v55
GM v13.4

scripts:
Clear window.opener
Conceal window.name
Conceal history.length

when these scripts are enabled some images will not load

ex: http://robertb.blog.is/users/96/robertb/img/acf3e41.jpg does not load for me (blank page)

if i disable all 3 scripts AND clear my cache AND reopen the URL in a NEW tab, then the image loads

i'm also noticing a similar problem that is not caused by GM however, especially in WordPress but also elsewhere, in that, if edit a page in WP and then click a link in the sidebar to go elsewhere, or sometimes even if i just try to log out, the URL in the address bar changes to the page expected, but the document in the viewport does not change

i have no idea what's causing this yet, but i am troubleshooting it

**Comment by mazesy** [comment] 2017-09-26 19:42
All I can say right now is that I have the 3 scripts you mention running as well and that the jpg image appears normally. 

Have you tried disablin one script at a time?

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:05
Roll back GM to 13.11

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:09
https://github.com/greasemonkey/greasemonkey/issues/2524

This is a GM and Mozilla issue .. or a GM & uBo issue or something

**Comment by mazesy** [comment] 2017-09-26 20:13
GreasMonkey 3.14 here together with uBO 1.14.10 legacy (Firefox) not WebExtension.

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:16
Question - can you VIEW any web stand-alone image? such as https://i.redd.it/mwsk0plng9oz.png

I only ask because I had this issue 3 or 4 weeks ago when uBo updated to hybrid. SOme of my issues stemmed from a FF bug fixed in 56. Some stemmed from GM clashing with uBo - I saw several times the solution was about AAK-Cont. In uBo untick the AAK-Cont blocklist. It is going to be discontinued or something.

I have also read of numerous issues with GM - 3.12->3.13->3.14 in the space of a few days. Stick with 3.11 mate until later

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:27
See also
- https://github.com/greasemonkey/greasemonkey/issues/2562
- https://github.com/greasemonkey/greasemonkey/issues/2554

which leads us as well to 
- https://github.com/gorhill/uBlock/issues/2930
- https://github.com/EFForg/privacybadger/issues/1653

The uBo link specifically mentions AAK script (sorry about my post above mentioned uBo's list, but I did read that somewhere I think, probably a red herring)

So the issue is a script if it contains something will clash with uBo WE. What they all have in common, I have NFI.

As I said in my first comment - roll back GM to 3.11 and wait. Personally I am on the verge of going to VM - however VM is such an old version on AMO that I'm waiting for that as well - can't win

**Comment by mazesy** [comment] 2017-09-26 20:29
`Question - can you VIEW any web stand-alone image? such as https://i.redd.it/mwsk0plng9oz.png`
If you're asking me the answer is yes, I can view that Test - view with DDG.

If -- if -- uBO is part of the problem it could be uBO hybrid/WE and not the good old legacy add-on.
Those webextensions are really problematic when it comes to updating complex add-ons.

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:31
No - all my comments are directed @atomGit because he is the one with the reproducible problem

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:34
@mazesy - yes the issue is when you have uBo WE

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 20:43
> seems to have had the @run-at document-start which created this problem

Someone talking about AAK Reek script. I think the 2 wiki scripts we have are fine. It's something else IMO. But the issue is legacy addon + web extensions and come 57 this particular issue won't be a problem.

In a few days when I upgrade to 56, I will go uBo webext-hybrid, then full on webext. I am hoping this doesn't happen again. It may be a case of locating offending scripts by testing each one on its own - and disabling them until 57.

**Comment by atomGit** [comment] 2017-09-27 12:03
> Question - can you VIEW any web stand-alone image? such as https://i.redd.it/mwsk0plng9oz.png

apparently not - i can only view images that are embeded in a page it seems - i tested both the example links you gave

i also noted that uBO and uM both played a part in my case and disabling them from their UI didn't work - i had to have them disabled at the browser level (about:addons) but, as you noted, that isn't the only problem - hope this WebExt stuff gets sorted out

i'll leave it up to you if you want to close this

**Comment by Thorin-Oakenpants** [comment] 2017-09-27 16:26
I had the same problem as you, described in those 4 links at ubo, eff, gm etc. The stand-alone image was one item, another was uM & uBo couldn't update their lists/hosts, and I had issues with XHR etc.

I simply rolled back to uBo 1.13.8 and am waiting to see what happens with 56. If the same issue arises, which I think it will, then I will troubleshoot the scripts one by one for peace of mind. But long term I will just ditch GM and go with VM. VM does not have this issue (but damn I wish they would update the version on AMO)

I suggest you do the same, because clearly the current setup is broken. I will leave this open so I can add anything I find when I upgrade uBo under 56

**Comment by atomGit** [comment] 2017-09-27 16:39
i had the same problem with uB not updating filter lists - i've reverted to old versions several times and did so again now to the 1.13.x

**off-topic**: JS crypto-miners running on websites - dunno if you want to [make a special mention of this](http://12bytes.org/articles/tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs#a-special-note-about-cryptocurrency-miners) somewhere - i think this might EXPLODE

**Comment by Thorin-Oakenpants** [comment] 2017-09-27 16:44
uBo includes blocks for crypto miners now by default. Might pay for us to confirm that

**Comment by atomGit** [comment] 2017-09-27 16:47
yeah i know, and AV vendors are jumping on it also apparently - i [added this filter list](https://github.com/hoshsadiq/adblock-nocoin-list) to uB

i don't know this is a bad thing - i see it as a way for us little people to gen revenue and i think it might be ok if the web-admin makes it opt-in

**Comment by atomGit** [comment] 2017-09-27 16:47
maybe you can inject it on github.com and make a fortune LOL

**Comment by earthlng** [comment] 2017-09-27 16:52
Well good luck with trying to block that based on lists. The only real way to stop it is to block JS.

**Comment by atomGit** [comment] 2017-09-27 18:23
luck may not be needed, at least in the case of Coinhive - i like what these guys have to say, their ethics and their privacy policy 

read: [The Pirate Bay and its cryptocurrency mining script – why this might be the best thing since DOOM | 12Bytes.org](http://12bytes.org/10227/the-pirate-bay-and-its-cryptocurrency-mining-script-why-this-might-be-the-best-thing-since-doom}

**Comment by Thorin-Oakenpants** [comment] 2017-09-28 23:35
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt

is this right, with the line break and the new lien starting with `/`
```
||edgeno.de^$script,third-party,domain=~edgemesh.com
/edgemesh.*.js$script,domain=~edgemesh.com|~edgeno.de
```
^^ is not the whole list - see link above

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 02:17
See [reddit thread](https://www.reddit.com/r/firefox/comments/73ak7p/another_reason_to_use_ublock_origin_over_adblock/)  and the new `uBlock filters - Resource abuse`

I'm still on 1.13.8 (legacy) on 55. I did a purge and update all, but it hasn't shown up yet

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 09:05
So far
- Updated to FF56 (this way I lose no counters!)
- Disabled ALL greasemonkey scripts - I just want to get uBo up to date and as a WE
- Closed
- Backed up profile
- Started FF, downloaded 1.13.10 from AMO, the hybrid version and installed from disk
- Quick tests
   - can see standalone images and update filters in uBo and lists in uM
   - all my filters & rules are there, along with counts
   - my custom blocking filters do not seem to work at all - yikes (haven't tested much more)
- Closed, restarted
- uBlock Origin icon vanished, not under customize - so instead I updated the extension to the latest 1.14.10 - icon is back
- Note: I also now have the new "uBlock filters – Resource abuse" filter automatically ticked - this is the coin mining etc
- Closed, restarted

:exclamation: this is very important - ***cookies control IDB access***. Since I block all cookies I need to set an exception
- go to about:debugging>add-ons .. scroll down to uBlock Origin and click the manifest.json
- you will get something like `moz-extension://b334a4fa-1146-4489-ac23-2f92fcaa7ef3/manifest.json`
- copy that string
- go to Options>Privacy & Security>History>custom settings>Cookie Exceptions
- Paste in `moz-extension://b334a4fa-1146-4489-ac23-2f92fcaa7ef3` - ie drop the `/manifest.json` part and `Allow`, and then click `Save Changes`

Then
- I closed and restarted and now I have a uBo cached assets in IDB storage .. cool
- counts still exist, can see stand-alone images, can purge and update lists and filters etc
- uBlock doesn't seem to be blocking my cosmetic filters
- yet to test the rest eg other blocks etc, and what happens with GM + scripts etc - will report back later

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 09:54
Oooh .. everything is sweeet (yet to test GM scripts clash) - my filters not working just so happened to be on a site that just tweaked it's code - I visit cracked.com maybe 2 or 3 times a week - reapplying a cosmetic filter via the element picker showed the element has had a name change eg `www.cracked.com###socialShare` (i think it was that one) to `www.cracked.com##.socialShareModule`. A quick loading of some other sites which are in my cosmetic filters show they are working.

Next up: I will update GM, then turn on scripts one by one (I have 8 of them)

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 10:49
OK, so with GM+uBo I can replicate part of the previous problems from in 55.
- I do not have the update issues from prior such as losing counters
- I do not lose any of my settings or filters or rules
- I do not have any issues updating lists or filters
- SOME stand-alone images are blocked
   * I distinctly remember imgur being one that did not work, but that is now ok, so it's a different root cause

ANY of our three scripts cause the image blocking - I can view standalone images for https://i.imgur.com/BNsl9Ei.png but not https://i.redd.it/mwsk0plng9oz.png when I have ANY of
- clear window.opener
- conceal history.length
- conceal window.name

These are the only scripts I have that have `// @include *  ` . The others are all google ones for pagination, dual columns, stripping tracking, utms, and removing all the crap etc - and they seem to be working fine.

Someone (in my comments above) when they mentioned a clash with AAK-Cont script they said "seems to have had the @run-at document-start which created this problem" - @earthlng - what does that mean?

I shall backup and update GM from 3.11 to latest 3.16

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 10:57
Done - updating GM to 3.16 fixed those three scripts (and I assume other scripts on the net like them eg AKK-Cont script). Everthing is working fine. Retesting updating filters in uBo, lists in uM, other uBo stuff, loading stand-alone images = everything is peachy

I now have more Extensions that Legacy Extensions .. yeeeehaa

@atomGit - let me know when I can close this

**Comment by earthlng** [comment] 2017-09-30 11:59
Why don't you just add exceptions to those scripts instead of disabling them?

**Comment by atomGit** [comment] 2017-09-30 12:04
try Violentmonkey - i personally don't like the GM privacy policy anyway

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 12:17
I would use VM but it has a LOT of issues current and closed and the AMO is like 3 months old

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 12:20
Adding exceptions for potentially hundreds of sites ... no way. If they work in VM then I'll switch.

I just fired up a nilla 56 and added Gm and the three scripts and am testing them without uBo. Forgot the jodonym needs an exception, so popped back in here to get it.

The only one of the three with run-at document start is the windows.name, and without it, it fails. The other two work in GM without uBo

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 12:51
OK - so in a nilla profile

- added GM, added the three scripts (including the `http://ip-check.info/?lang=en` exclusion for windows.name - so the landing page will let you load the test)
- tested all three scripts (not sure if windows.opener worked, as not sure on what those test links are meant to do. All links opened in a new tab, so I guess that means it worked and the current tab is not hijacked)
- stand-alone images on both imgur and reddit worked
- added uBo and closed and restarted
- added some uBo 3rd party filter lists including `AAK-Cont Filters For uBlock Origin`
- purged and updated all filters
- and everything WORKS

So I'm going to say that it is something in one of the 3rd party list? I will go thru and do comparisons of my current uBo and the nilla one - export settings, import etc

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 14:01
Weird. If you restart with the three GM scripts disabled. Everything works

- if you enable window.opener and history.length - everything still works until you restart, then its broken again
- if you enable windows.name (the only one with run-at document-start) then it breaks immediately
- so testing requires zilla restarts !!
- it's all crazypants and nutshakes ...

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 14:08
In my nilla FF, I have imported all my uBo stuff - settings, 3rd party filters (and updated them), including custom 3rd party, rules, whitelist - the lot. It all works perfectly with GM and the three scripts - even after closing and restarting after changes for testing.

I guess the fix is to uninstall uBo (after exporting your stuff), restarting and reinstalling. I'll try that

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 15:29
I've had it with this. I removed uBo. I even cleared out the left over files in my profile: some 2bytes in a file in a uBlock0@raymondhill.net, a "staged folder" for uBo, the old ublock0.sqlite, a swag of left over prefs in about:config about the cloud and syncing - wiped it clean as a whistle.

Reinstalled from scratch, added cookie exception to the extension, manually updated default lists, manually added my whitelist (making sure all the defaults were there), imported & appended my rules to the two that already existed in default, manually added a custom 3rd party filter (BarbBlock) and a new custom 3rd party filter called `AakList (Anti-Adblock Killer)` added itself, and manually added my filters.

Everything works perfectly (with the 2 scripts disabled). Its brand spanking new. It's IDENTICAL to the one in my nilla FF testing. Except in the nilla I have GM+Scripts + uBo working nicely. In my real FF, the shit still happens.

The ONLY thing I can think of, is order of installing makes a difference. But I am done with this
 ------------- BYE BYE GM .. HELLO VM

I think I should remove GM from our recommendations and the scripts page, and replace it with VM.

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 16:43
I disabled GM, installed VM, added a cookie exception to the extension, and created the 3 scripts - at run at document start, which ALL three are (I do not know why I said only one was) - they ALL FAIL. They do not cause the image issues which GM did, but they FAIL in the tests (I can only assume window.opener fails as I am not sure what to check for)

I changed them all in VM to run as default (options are default, document-start, document-idle, document-end - and there is no setting I can find for the default). THEN they worked .. except

- Open a tab, load ten different websites in the same tab so `tab history` exists
- Paste in JoDonym [landing page[(http://ip-check.info/?lang=en) and hit the test
   * `Tab name` (windows.name) and `Tab history` should be green and Protected
- Paste in [Browserspy](http://browserspy.dk/document.php) into the **same tab**
   * Number of pages visited in History should fail and show the number 10 (which is our limit in preferences)

I will go back to GM and change the scripts to not run at document-start and see what happens

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 17:29
Conclusion: disable GM and see what the Web Extension version does. Install VM and use that.

Closing this - see #251 for a follow up on fixing the wiki recommendations and scripts

**Closed** 2017-09-30 17:30 UTC

**Comment by Thorin-Oakenpants** [comment] 2017-09-30 17:40
Actually now that I finally put this to rest, and disabled GM one more time, and re-enabled VM with my 3 scripts ... I find VM is failing as well without `@run-at document-start` ... I give up

**Comment by Thorin-Oakenpants** [comment] 2017-10-01 16:35
The issue is caused by legacy GM + web extension uBo. The problem will go away when 57 lands
