### ISSUE TITLE
browser.cache.offline.enable = false causes about:preferences#privacy to not function on FF55

### ISSUE THREAD

**Issue by ZeGentzy** [ghacksuserjs/ghacks-user.js#81] opened 2017-04-14 00:58 UTC
Hello, 
I have recently been experiencing some issues with ghack. This is the first of many.

Steps to reproduce:
1- Get latest firefox nightly on Arch Linux.
2- Try to go to 'about:preferences#privacy' and notice how everything is blank an empty
3- Click on an other tab
4- Try clicking on the privacy tab and notice how the tab doesn't change.

Solution:
Remove 1004.

**Comment by earthlng** [comment] 2017-04-14 13:01
Hi, thanks for the report. Did you notice it in FF52 and then also test it in nightly, or why the discrepancy between the title and the steps to reproduce?

They had the same problem years ago:
https://bugzilla.mozilla.org/show_bug.cgi?id=795764
https://bugzilla.mozilla.org/show_bug.cgi?id=1218263

But I can't find a current ticket that it is still (or again) a problem. Can you file a bug report with mozilla?

I can't reproduce it with an older FF55 nightly (2017-03-20) on Windows either.

We'll keep an eye on it in coming stable releases and will add a note to 1004 when the problem shows itself in a stable version.

> This is the first of many.

Keep them coming :) thanks

**Comment by Thorin-Oakenpants** [comment] 2017-04-14 14:47
> The first of many

That there is your problem. You're using FF55 and things are breaking and you're saying this user.js, which is marked as 52 compliant, is breaking many things. Nightly is the least stable, it's 3 versions away. It's bleeding edge. You're also on Linux which may be a factor in this particular issue you seem to have.

Developer Edition handles user.js differently. Any syntax error and the entire user.js is ignored. I suspect this may be the same in Nightly, but I'm not sure. Either way, you can easily just set one off preferences via about:config

Have you created downloaded the latest nightly, created a brand new vanilla profile, gone to about:config and changed that ONE preference, and restarted it.

Have you downloaded FF52, created a new profile, and only amended the one preference?

**Comment by earthlng** [comment] 2017-04-14 15:00
@Thorin, this guy is using Arch Linux so I'm pretty sure his bug report is correct and he knows what he's talking about.

**Comment by zymase** [comment] 2017-04-14 15:16
The title mentions Firefox 52 and the steps to reproduce include latest firefox nightly (on Arch Linux).

**Comment by crssi** [comment] 2017-04-14 16:46
Just a typo on title, some admin can correct it?...
I think those reports can prepare you better for the future releases and you need guys like @ZeGentzy

**Comment by zymase** [comment] 2017-04-14 21:33
We all need someone, but when that someone isn't clear in a thread's title and ends with a radical comment such as

> Solution:
> Remove 1004.

one can wonder if a whitlow is worth cutting a hand. Radical.

**Comment by Thorin-Oakenpants** [comment] 2017-04-14 22:08
I'm searching now and can find nothing about this causing issues with `about` pages other than what Earthlng dug up. The offline cache was/is used by websites (not internal chrome pages) to store elements tagged with rel="offline-resource" in the offline cache to provide offline browsing capabilities to devices, to improve the performance of important resources, and to reduce server load.

https://bugzilla.mozilla.org/show_bug.cgi?id=1020651 is another bug that shows similar behavior - the cause was BOTH `browser.cache.disk.enable` AND `browser.cache.memory.enable` as false (which the ghacks js both set as such). All these type bugs came from 32/33 and the fix was to catch the exceptions. The basic UI pages haven't changed in ages. Maybe there is some change to

Hope @ZeGentzy pops back and confirms that the title 52 was an error and he meant 55 nightly. Shame I don't have an arch linux setup. Could always load a live cd... I'm also wondering if it affects any other about: pages or parts of the options UI

@zymase : I think he probably means comment out, rather than remove (or add a warning for (Arch) Linux)

**Comment by Thorin-Oakenpants** [comment] 2017-04-14 22:11
https://bugzilla.mozilla.org/show_bug.cgi?id=1355795

**Comment by zymase** [comment] 2017-04-14 22:37
Whatever (a typo on title, commenting out rather than removing) seems much must be done to get things clear.

My very first reaction when reading @ZeGentzy 's comment was similar to yours, @Thorin-Oakenpants , when you wrote above,

> That there is your problem. You're using FF55 and things are breaking and you're saying this user.js, which is marked as 52 compliant, is breaking many things. Nightly is the least stable, it's 3 versions away. It's bleeding edge. You're also on Linux which may be a factor in this particular issue you seem to have.

It's just not possible to anticipate 3 versions ahead and as I understand it, the route plan her is for the present release linked to the very next one, only. Well, I say that I say nothing, I'm not the boss around here.

I certainly do hope @ZeGentzy pops in to bring more substance to his extra quick shoot.

**Comment by Thorin-Oakenpants** [comment] 2017-04-14 23:04
It's already logged as a FF55 Linux bug ( https://bugzilla.mozilla.org/show_bug.cgi?id=1355795 ) which is a regression from bug 795764 (see comment 4: https://bugzilla.mozilla.org/show_bug.cgi?id=1355795#c4 ). I have already renamed the title to say it is FF55 specific and a FF bug.

**Comment by ZeGentzy** [comment] 2017-04-15 00:10
My apologizes for the typo and the extreme propopsed solution, I was rushing onto a plane. I was actualy refering to FF55.

> Have you downloaded the latest nightly, created a brand new vanilla profile, gone to about:preferences#privacy and it is working?
Yes

> Have you downloaded the latest nightly, created a brand new vanilla profile, gone to about:config and changed that ONE preference, and restarted it.
Yes and it stops working.

@Thorin-Oakenpants
Yes, it does apear to be bug #1355795.

Again, I do apologize for this as it was extremly unprofesional.

**Closed** 2017-04-15 00:11 UTC
Labels: firefox bug

**Comment by Thorin-Oakenpants** [comment] 2017-04-15 00:30
@ZeGentzy No problems :)  You mentioned other breakage? Feel free to dump them here for a quick perusal, although if they're 55 nightly / arch linux, then proabbly not much we can do, but would be nice to know

**Comment by Thorin-Oakenpants** [comment] 2017-04-18 19:15
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1355795 is now verified fixed
