### ISSUE TITLE
cache tracking techniques

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#436] opened 2018-05-24 04:00 UTC
@vertigo220 said

> Article: https://robertheaton.com/2014/01/20/cookieless-user-tracking-for-douchebags/
> PoC: http://cookieless-user-tracking.herokuapp.com/
> Source: https://github.com/robert/cookieless-user-tracking
> 
> BTW, here's another, unrelated cache tracking technique you may or may not be aware of which, AFAICT, can't be defeated except by periodically clearing the cache. Thought you might find it interesting.

**Comment by Thorin-Oakenpants** [comment] 2018-05-24 04:02
:jeans: said
> can't be defeated except by periodically clearing the cache

Or by not having any disk or memory cache. Or by Temporary Containers in a hardened mode. Or by not running JS (for that example, PoC). Edit: Also PB windows (since we start in normal mode) will beat this (i.e when all PB mode windows are closed, all persistent data is wiped).

You could do this as well with a unique image name, no JS required. All driven server side.

**Comment by claustromaniac** [comment] 2018-05-24 04:54
> You could do this as well with a unique image name, no JS required.

I initially thought this should be possible but I wonder if it really is. It certainly should be possible with Javascript, but I wonder if it can be done without it. I'm thinking it may be harder to pull off than it sounds, maybe with redirections or something...

**Comment by Thorin-Oakenpants** [comment] 2018-05-24 05:13
probably :shutup:

**Comment by vertigo220** [comment] 2018-05-24 14:44
@Thorin-Oakenpants said:

> Or by not having any disk or memory cache. Or by Temporary Containers in a hardened mode. Or by not running JS (for that example, PoC). Edit: Also PB windows (since we start in normal mode) will beat this (i.e when all PB mode windows are closed, all persistent data is wiped).

You sure do know how to take the fun out of things 😛 Ok, ok, what I _meant_ to say was there's no way to defeat it via an addon or some other means that doesn't require completely shutting the doors on it, i.e. cutting our own legs out from underneath us to do it. And not running JS is only a partial solution since, IME, many sites don't work properly with some 3rd-party JS and some don't even load at all with JS completely disabled. As for disabling cache, that's not an option I like for my relatively slow connection, so having uM clear it occasionally so far seems the best solution, but maybe this discussion will stir up some better ideas.

> You could do this as well with a unique image name, no JS required. All driven server side.

So then disabling JS _isn't_ even a complete solution. This is what I thought he was actually talking about, just using an image or even a tracking pixel.

As for the thread's name, perhaps "Cache tracking techniques?"

@claustromaniac said:

> I'm pretty sure it's not a practical approach at all. It's easy to serve a specific client a specific resource using javascript when you already identified the client in question, but the problem with these tracking mechanisms is that you don't know which client you're serving data before you identify them, and if you already know which client you're dealing with, then you are already set.

I very well could not be fully understanding the technique, but it seems the first time someone loads a page with the tracker on it, it will download and cache it, along with a unique identifier the server creates, and from that point on the server will see that it's been cached and won't send another one, instead using the cached one to determine the user's identity (not quite clear on _how_ it does that part). So it seems to me it doesn't matter if the server knows who the client is beforehand.

As for your HE function, would preventing scripts from being cached be enough, since images, etc could be used for this? Or is it ultimately a script that provides the server with the user's ID?

**Comment by claustromaniac** [comment] 2018-05-24 16:13
Thinking this through, it might be possible to use other cached elements like images as unique IDs. A hidden unique image with a generic name, for example, may still work as a unique ID. I wonder if JS supports native functions to read images or other files as binary data. If that was the case, the same technique may be achievable by hashing the cached image's binary data.

**Comment by claustromaniac** [comment] 2018-05-25 14:09
Allow me to summarise the mess that I've made of this thread.

The article describes a way for servers to leave files in the user's cache indefinitely, and the PoC shows a way to leverage that method for the purpose of tracking. It does so by generating a unique ID and assigning it to a variable in a one-line script that will be cached by the user's browser. That's all it needs.

What I've researched so far tells me that said method is only useful when caching scripts or json files, especifically. I haven't yet confirmed that no other types of cached resources can be used instead, but so far everything seems to indicate that only those two represent a risk. For those cases, the HE rule example that I posted above should help, but it will only _prevent_ the browser from caching scripts and jsons, it won't remove already cached scripts and jsons from the cache.

I will keep investigating. I'm not a web developer and I only have a little experience with javascript. I don't know :hankey: about PHP or Ruby, or Node.js, etc, so I'd love to know what others think.

**Comment by Thorin-Oakenpants** [comment] 2018-05-25 15:02
There is a solution. Disable all cache (disk and memory). It's kinda one of those things where, at the end of the day, if it's really critical .. use TBB on TAILS or something. I'm not sure of the cost of this thing, but I think most of the web has already got its hands full of lowest hanging fruit (eg from the FB/etc users giving shit away and all those billions of browsers with cookies, storage, GA, google DNS, etc etc .. not to mention apps).

**Comment by earthlng** [comment] 2018-05-25 15:13
re: your custom function: Caching everything except JS + JSON makes you pretty unique I reckon. Almost all sites use JS but most of them probably don't use this technique to track you so I doubt the usefulness of this.
IMO the best solution is the Temporary Containers addon because it kills many birds with one shot (including this one).

**Comment by Thorin-Oakenpants** [comment] 2018-05-25 15:18
^^ agreed. Everything but TC in hardened mode or disabling all cache is an incomplete solution IMO. Clearing cache every x minutes is OK, at least revisiting a site hours later doesn't track you this way.

I think we could add some info to pref 1003 and then close this. Also add the PoC to the wiki

**Comment by earthlng** [comment] 2018-05-25 15:23
By far the best solution to deal with Ads + tracking etc is NOT TO BUY THEIR SHIT.
They do all this tracking shit "to sell you stuff you don't need, with money you don't have, to impress people you don't like". (I love this quote! whoever came up with this is a genius)
Boycott every company that heavily advertises, don't buy brands produced by child labor in China etc etc! Boycott-Divest-and-Sanctions! Hit them where it hurts :)

**Comment by Thorin-Oakenpants** [comment] 2018-05-25 15:27
But I never see any ads.

Actually, I disagree. I'm not assuming anything about the tracking - for all I know it could be to unmask me when I do all my illegal shit. I treat all tracking the same, just like I want to treat all web sites, and all traffic the same. They are all assumed guilty until proven innocent

**Comment by claustromaniac** [comment] 2018-05-25 15:55
> Caching everything except JS + JSON makes you pretty unique I reckon.

I get the argument, but wouldn't servers normally expect the users' cache to be incomplete every now and then, given the dynamic nature of it? Unless someone actively looks for this pattern, I doubt anyone would notice, and this tracking technique may not be well known, but it's efficient and stupidly easy to implement.

I agree that there doesn't seem to be any solution as complete as clearing the cache periodically or conditionally (like with the TC extension), though. There's always going to be some sort of trade-off.

**Comment by claustromaniac** [comment] 2018-05-25 15:58
@Thorin-Oakenpants would disabling memory cache really be necessary? Honest question, you surely know more about the relation between the two different types of cache than me.

**Comment by Thorin-Oakenpants** [comment] 2018-05-25 16:21
^^ I'm no cache expert. AFAIK, disk cache simply means when the browser is closed, it can still use the cache when you reopen it. Everything is shoved into RAM anyway at some point (but gets released when more memory is needed). So disk cache can be bigger, and backs up memory cache as far as I'm concerned. Not to be confused with the "page memory" which is something about pages in ram after they've been rendered/painted or something (and that's probably all changed with WebRender). I also have no idea about GPUs.

But yes. If you do the etag or this PoC with both disk and memory cache disabled, the tracking is defeated. I can actually browse with no noticeable drop in performance (but obviously an overhead somewhere - power consumption? don't care about bandwidth) with both off. But its not the solution I *want*

**Comment by vertigo220** [comment] 2018-05-28 00:05
WRT TC vs FPI, I've seen discussions elsewhere where it was said (including by Pants, IIRC) that FPI is basically TC on steroids and that TC is essentially pointless when using FPI. Is that not the case? It seems both would allow this tracking to work, but if I'm not mistaken FPI is persistent and TC isn't, so with TC when you close the tab for the site it wipes the cached content from it, whereas FPI would keep it around. Is that correct?

**Comment by claustromaniac** [comment] 2018-05-28 08:09
@Thorin-Oakenpants (regarding memory cache) it was my understanding that disabling disk cache **only** would be enough to protect us from all kinds of cache tracking techniques **between browser sessions**, without having to sacrifice the performance benefits of the memory cache. That's why I asked.

I suspect that disabling both memory and disk cache wouldn't make anyone much less unique than preventing the browser from caching JS + JSON specifically. I don't think many people do that either.

Personally, I was looking for a way to defend myself against this tracking technique without giving up my disk cache because I do care about my bandwidth. That's why I wrote that function, but I slept on it and I guess I'll settle for TC for random browsing + permanent containers for sites I login into. It seems like the best compromise in my position, and has some added benefits.

Thanks :jeans: and @earthlng for your input, and thanks again @vertigo220 for bringing this up :+1: 

> FPI is persistent and TC isn't, so with TC when you close the tab for the site it wipes the cached content from it, whereas FPI would keep it around. Is that correct?

If by TC you mean the Temporary Containers extension, I think that is correct.

**Comment by vertigo220** [comment] 2018-05-28 14:50
@Thorin-Oakenpants - Not WRC. WRT (with respect to).

Guess I need to take another look at TC...

**Comment by Thorin-Oakenpants** [comment] 2018-05-29 02:54
>  it was my understanding that disabling disk cache (but not memory cache) would be enough to protect us from all kinds of cache tracking techniques between browser sessions, without having to sacrifice the performance benefits of the memory cache. That's why I asked.

Sorry. Did I misunderstand something? Disk cache is "permanent", memory cache is discarded when the app needs to release it or the app is closed

**Comment by claustromaniac** [comment] 2018-05-29 17:38
> Did I misunderstand something?

I don't think so. You said that one of the options to defeat these tracking techniques is to disable both disk and memory cache. What I tried to say - put in different words - is that in practice, disabling disk-cache _only_ (leaving memory cache enabled) should be as effective as enabling `privacy.clearOnShutdown.cache`. 

I didn't put it that from the beginning because I wasn't sure of it. There could've been other reasons for disabling memory cache that I wasn't aware of, that's why I asked instead. Sorry about the confusion.

**Comment by Thorin-Oakenpants** [comment] 2018-08-17 08:28
reminder

> I think we could add some info to pref 1003 re this & etags, and then close this. Also add the PoC to the wiki

**Comment by Thorin-Oakenpants** [comment] 2018-08-25 08:25
- [x] add PoC to wiki :heavy_check_mark:

**Closed** 2018-08-28 08:27 UTC
