### ISSUE TITLE
Disabling section 2800 and replace with cookie autodelete addon

### ISSUE THREAD

**Issue by fu8765** [ghacksuserjs/ghacks-user.js#810] opened 2019-10-05 02:12 UTC
I would like for some sites to keep cookies to avoid having to log in.
Would it be fair to say that an extension like Cookie autodelete would perform a similar job (if not better, as the unwanted cookies are deleted straight away, rather than at shutdown) as section 2800 while allowing me to keep some cookies? and given that first party isolate is on it should not be much of an issue?

**Comment by fu8765** [comment] 2019-10-05 02:37
this did not allow me to keep logged in to sites whitelisted in "cookie autodelete"

**Comment by Thorin-Oakenpants** [comment] 2019-10-05 06:04
Options > Privacy tab > Cookies and Site Data section. There is an option to "delete cookies and site data when Firefox is closed" - with a "manage permissions" button where you can add exceptions.

First, this option may be disabled (it is for me). I'm not 100% sure what controls it. Secondly, the "manage permissions" is AFAIK meant to be kept - so it doesn't wipe a whitelisted cookie (not sure how it handles indexedDB etc and other quota data). Third, this is broken since 68 [1584986](https://bugzilla.mozilla.org/show_bug.cgi?id=1584986)

I'm not sure when or how they will merge the "clearing on close" (2800 section) UI items with the "cookies and site data" UI. I've steered clear of the later because it's been years in the making with next_gen local storage and has had lots of teething problems.

Also, as data is tied together (quota), it seems as if clearing come items on close, now clear others. e.g if you clear cookies (I think I confirmed this the other week, but its hazy), it also clears IDB - or it may have been the other way round.

If you can't find an extension that fits (and I would make sure it cleans cookies on startup as well, since you can close the browser quickly and leave pending extension cleanups, or close it with tabs open), then perhaps you can **set all cookies to be default session only** - this is pref 2703, set `network.cookie.lifetimePolicy` as `2` - and add exceptions to sites you want to keep as cookie *allowed*. **But** be aware of #783

**Comment by Thorin-Oakenpants** [comment] 2019-10-05 06:06
PS: session cookies have a slight consequence (last time I checked), they break shared and service workers. It's in the section 2700 header notes

**Comment by Thorin-Oakenpants** [comment] 2019-10-06 10:56
Also FYI re default session cookies: https://bugzilla.mozilla.org/show_bug.cgi?id=1530755

**Closed** 2019-10-07 16:22 UTC

**Comment by fu8765** [comment] 2019-10-08 01:16
Apologies for not responding earlier.
I was talking about using the extension "cookie autodelete" which within seconds of a tab being closed, it can wipe all cookies and local storage.

If this is the case, is it possible to remove all cookie/storage deletion at closure, from user.js? and how to do this?

**Comment by Thorin-Oakenpants** [comment] 2019-10-08 01:27
> is it possible to remove all cookie/storage deletion at closure, from user.js? and how to do this?

Yes. Options > Privacy&Security > History ... you change the dropdown from Firefox will `remember history` to `use custom settings`. This then will provide more options in the UI, including one to "Clear history when Firefox closes", and a "Settings" button

See section 2800 in the user.js
