### ISSUE TITLE
Decentraleyes is currently broken in FF63beta + 64nightly [1489882]

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#498] opened 2018-09-09 12:39 UTC
Issue: `https://git.synz.io/Synzvato/decentraleyes/issues/313`
Testpage: https://decentraleyes.org/test/

edit: bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1489882

ps
> Microsoft is acquiring GitHub. Decentraleyes is leaving GitHub. Welcome to its new home!

new home: https://git.synz.io/Synzvato/decentraleyes

**Comment by earthlng** [comment] 2018-09-09 13:07
@gorhill, redirecting in uBO is probably also affected

**Comment by gorhill** [comment] 2018-09-09 17:53
It's working fine on my Nightly as far as I can tell -- the redirection to neutered scripts are working fine.

**Comment by Thorin-Oakenpants** [comment] 2018-09-09 20:31
thanks re new home: updated wiki links

**Comment by earthlng** [comment] 2018-09-10 11:54
Thanks @gorhill for checking. Interesting that it works in uBO and not in Decentraleyes. I suspect the problem is that he uses `.js.dec` file extensions

**Comment by Thorin-Oakenpants** [comment] 2018-09-13 00:54
https://bugzilla.mozilla.org/show_bug.cgi?id=1489882 was WONTFIX ... IDK where that leaves DC

**Comment by Atavic** [comment] 2018-09-13 21:50
:-1: for Gijs on the bugzilla, his replies confirm the cold war on the webextenison devs by Mozilla. He's `gijsk` on GH.

**Comment by Atavic** [comment] 2018-09-13 21:51
:-1: for Gijs on the bugzilla, his replies confirm the cold war on the webext-devs by Mozilla. He's `gijsk` on GH.

**Comment by Thorin-Oakenpants** [comment] 2018-09-13 22:27
There's no such cold war. It's a regression that affects one extension (or only one extension that we care about). Everyone has different views, reasons and desired outcomes. We don't always have to like Mozilla's decisions - but you should at least respect them, IMO.

**Comment by Atavic** [comment] 2018-09-13 23:41
Ok, comment deleted and I'll refrain to comment about bugzilla in the future.

**Comment by B00ze64** [comment] 2018-09-14 00:26
You guys should read the bug before commenting here. Mozilla decided that FF would now validate files injected into web pages using their filename/extension. If you ask me this is pointless since file extensions mean nothing, but what do I know, maybe it helps. In any case, Decentraleyes has been forced, since a long time, to use a custom file extension for the files it injects BECAUSE of the LINTER. That is to say, the problem is not with Firefox at all, it is with the script that runs and validates addOns when they are uploaded to AMO. THAT is where a bug report needs to be opened (couldn't they just assign the current bug to the AMO team instead of closing it as wontfix?) Anyway, it's not a FF bug, it's an AMO bug...

**Comment by B00ze64** [comment] 2018-09-14 00:31
Maybe a bug needs to be opened on [Linter GitHub](https://github.com/mozilla/addons-linter/issues) if it takes too long to validate Decentraleyes...

**Comment by Thorin-Oakenpants** [comment] 2018-09-16 06:31
> I'm happy to say that a fix has been deployed. Upgrading to v2.0.8 should restore all functionality

**Closed by Thorin-Oakenpants** 2018-09-16 06:31 UTC
Labels: FYI, firefox bug
