### ISSUE TITLE
dom.event.contextmenu.enabled - description needs updating?

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#61] opened 2017-03-16 13:24 UTC
i'm not aware of 'dom.event.contextmenu.enabled' breaking JS context menus - rather the JS context menu is placed under the default FF context menu, so you have both - if you want to use the JS menu, press Esc once

current descrip:

'[WARNING] This will break sites' functionality such as Dropbox'

might want to change that to reflect what i stated above?

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 13:29
can u give me an example site, maybe a snapshot?

**Comment by atomGit** [comment] 2017-03-16 13:41
dropbox: https://imgoat.com/uploads/9f0f895fb9/7149.png

if i click Esc, the FF menu would close leaving only the JS menu - Esc again and that too closes

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 14:52
But right click scripts can do whatever they want. Just because Dropbox or Google Docs is nice about it, doesn't mean others are.

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 14:54
I'm not closing this, and we already brought this up in another issue, about whether or not to move it (and disable it - deferred for now). Now I'm going to have to find example of where it's being used by a-holes. :)

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 14:55
Also not sure about Shift-right-click

**Comment by atomGit** [comment] 2017-03-16 15:06
> But right click scripts can do whatever they want. Just because Dropbox or Google Docs is nice about it, doesn't mean others are.

i may have misled you - my point was that setting 'dom.event.contextmenu.enabled' to 'false' doesn't prevent the context menu - that SS i gave you is with the pref set to 'false'

so it it's 'being used by a-holes', and 'false' doesn't prevent this, then maybe we have a bigger problem?

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 16:23
Ahh, sweet

[TEST] https://swisnl.github.io/jQuery-contextMenu/demo.html
With `dom.event.contextmenu.enabled`->true, the right click does brings up the JS menu **only**

With `dom.event.contextmenu.enabled`->false, the right click does brings up the browser's menu (but, weird, it has the JS menu underneath, and to make the browser one disappear, I just click to another tab and then back again, and voila JS menu).

^^^ so based on THAT test and they are only using onContext events (not onclick, onmouse, up/down whatever) (or at least that's what I think they are doing, or at least that's what the pref covers), then the description is correct

Set true, it dictates the context menu and controls it completely and the browser context menu is not shown
Set false: the browser context menu is shown

The whole thing needs more cowbell

**Comment by atomGit** [comment] 2017-03-16 17:22
> [...] to make the browser one disappear, I just click to another tab and then back again, and voila JS menu

you can just press Esc to hide the FF menu and expose the JS menu - i didn't test all the examples though, just the first one on that page

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 17:51
All the examples there (when you disable JS control on context menu), allow the browser menu, with the JS one underneath. ALL. THE. EXAMPLES. :)

When this pref came out (it goes back to like FF3.6 and maybe earlier), it probably did what it said (but I have seen bug tickets which say otherwise) as in it stopped most sites disabling the right click menu entirely (isn;t that what that add0on "right to click" did?). But now we are 10 or 11 years on or whatever, and web tech has changed. Whatever is being used to trigger those menus is not fully covered by this pref any more. I have a feeling (but lack the right term here) that I read about this being an onSomething event (and its not a mouse one) and that its easily bypassed.

Its been decades since I worked with events (and even then it was a nightmare - on key up/down/press mouse move/up/down/click/double-click, left-middle-right .. on enter, on exit, on focus)

NOTE: Shift-Right-Click leaves the JS menu off, just giving the browser one

**Comment by Thorin-Oakenpants** [comment] 2017-03-16 17:55
I think we need someone to test this in their Outlook.com mail thing (who was it who had that), and other sites that like google docs or gmail. I'm not sure which other sites have featured right clicks. I also wouldn't mind a couple of examples of a-hole sites abusing it.

So I set it to true, and I can bypass a JS menu with shift-rightclick, same in false

**Comment by crssi** [comment] 2017-03-16 18:09
Outlook Web Access (Exchange server on-premises):
TRUE
Right click = JS context menu
Shift Right click = FF contect menu

FALSE
Right click or Shift Right click is the same... always shows both, JS and FF, but FF menu is overlapping JS,

I will stay on TRUE. ;)

**Comment by Thorin-Oakenpants** [comment] 2017-03-17 02:01
just throwing it out there

```js
/* 2201: disable website control over browser right-click context menu [SETUP]
 * [NOTE] Shift-Right-Click will always bring up the browser right-click context menu
 * [WARNING] This will break sites' functionality such as dropbox,  google docs, etc
 * where JS context menus are used for extra features or core components.  ***/
   // user_pref("dom.event.contextmenu.enabled", false);
```

**Comment by earthlng** [comment] 2017-03-17 17:57
It sounds like it doesn't work at all anymore?! Do we really need a [SETUP] + [WARNING] for something that does jack-shit?

**Comment by Thorin-Oakenpants** [comment] 2017-03-17 18:12
Good point. how's this

```js
/* 2201: disable website control over browser right-click context menu
 * [NOTE] Shift-Right-Click will always bring up the browser right-click context menu
   // user_pref("dom.event.contextmenu.enabled", false);
```

**Comment by Thorin-Oakenpants** [comment] 2017-03-17 18:12
a quick thumbs up and I can close this

**Closed** 2017-03-17 18:20 UTC

**Comment by Thorin-Oakenpants** [comment] 2017-03-17 18:23
@atomGit Thanks for bringing this up, excellent. Now we've learned/confirmed Shift+Right-Click override and improved website compatibility. Thanks :)
