### ISSUE TITLE
the open cookie jar [1447935, 1433700, 1207775]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#489] opened 2018-08-17 04:27 UTC
This issue is really just for myself, and FYI - I'll fix the title one day when I get the time to read the docs etc and understand what is going on

- Article: https://www.bleepingcomputer.com/news/security/academics-discover-new-bypasses-for-browser-tracking-protections-and-ad-blockers/
    * Bypasses are new, not used in the wild yet
- ghacks article: https://www.ghacks.net/2018/08/18/browsers-have-cookie-and-anti-tracking-enforcement-issues/
- Website: https://wholeftopenthecookiejar.eu/
- Github: https://github.com/DistriNet/xsr-framework
- Paper: https://wholeftopenthecookiejar.eu/static/tpc-paper.pdf

Discussions
- r/firefox: https://old.reddit.com/r/firefox/comments/97racx/academics_discover_new_bypasses_for_browser/
- r/privacy: https://old.reddit.com/r/privacy/comments/97rare/academics_discover_new_bypasses_for_browser/
- r/uBlockOrigin: https://old.reddit.com/r/uBlockOrigin/comments/97tzw9/academics_discover_new_bypasses_for_browser/
- Schneier on Security: https://www.schneier.com/blog/archives/2018/08/new_ways_to_tra.html

I had a quick skim of the reddit link and article last night, and
- 1. gorhill has us covered, assuming your config is "right" (good gorhill, good boy!) :kiss: 
- 2. I'm not worried personally, as I lock down basically all persistent storage

My assumption has always been that any persistent storage of website data **can** and **will** be used against you. Hence why the default user.js essentially blocked everything (until recently where we allowed first party cookies). Anyway, that's all for now

PS: I do not care about ABP, Disconnect, SafeScript etc, I only care about uM, uBO (and Firefox)

@gorhill Thanks, feel free to chime in **if and when** you have time (and feel it necessary), just don't like talking behind yer back :)

**Comment by earthlng** [comment] 2018-08-17 14:19
I also wanted to make a post about this but you beat me to it :)

It's nice to see that Gecko-based browser did far better than the rest (at least for the most part). Good job mozilla! I mean we already knew that or we wouldn't be using FF in the 1st place but it's nice to see it confirmed once again.

One problem in FF and other Gecko-based browsers was this:
> Contrasting to extensions of other browsers, almost every Firefox-based extension could be bypassed in the HTML category. In most cases, this was caused by a <link> element, which rel attribute was set to "shortcut icon". By further analyzing this case, we traced back the cause of this issue to an implementation bug in the WebExtension API. We found that the onBeforeRequest event did not trigger for requests originating from this link element. Although abusing this bug may not be straightforward, as it is only sent when a web page is visited for the first time, it does indicate that browsers exhibit small inconsistencies, which may often lead to unintended behavior.

This is bad because apparently it can leak cookies and could also be abused for tracking fe with ETAGs. But the good news is that this issue was (allegedly) fixed in FF63. Probably worth checking if that's really the case.

Another problem they also mentioned is that extensions are prohibited from seeing requests from other extensions. I was already aware of that and it's one the things that bugs me the most with the current WE-APIs. Hopefully they'll change that behavior sooner rather than later but I won't hold my breath :(

**Comment by earthlng** [comment] 2018-08-17 14:40
> Same-site cookie - No bugs were found for Firefox’ implementation of this policy.

:1st_place_medal: :+1: 

> Most of the browsers that we evaluated have built-in support for **suppressing cookies of third-party requests**. Our results show that only the Gecko-based browsers (Firefox, Cliqz and Tor Browser) manage to do this successfully.

:+1: :+1: 

although for 3rd-party cookie blocking FF still lacks (/leaks ?) in *Redirects*:

![1](https://user-images.githubusercontent.com/25846669/44271656-3ff2c100-a22a-11e8-8d60-2e66556cf9eb.png)

But if FF is used with uBO their Table 2 shows that *Redirects* makes "no request".
@gorhill is there something in uBO that blocks redirects or strips cookies from such requests? I'm not aware that there is such a thing.

**Comment by Thorin-Oakenpants** [comment] 2018-08-17 15:47
^^ so the uBO pass mark was a false positive?

**Comment by gorhill** [comment] 2018-08-17 15:50
Not a false positive, a deserves pass mark -- see for yourself and try to navigate to `https://adition.com/report/?leak=any`, they used that server to run their tests. (you may have missed my update in my comment above yours).

**Comment by Thorin-Oakenpants** [comment] 2018-08-17 16:01
^^ Ahhh .. good gorhill :+1: I saw the edit, but misinterpreted the entire post (yup, I admit it, I'm an idiot).

**Comment by earthlng** [comment] 2018-08-17 16:08
> Not a false positive, a deserved pass mark

it sounds like Redirects *can* be problematic depending on how a site uses it, and you said this yourself:

> According to the tests you can execute from their site, uBO would fail the "Redirects" category.

I'd say the 1st line of defense is to enable 3rd-party cookie blocking in FF because that will stop everything in these tests except Redirects. Add uBO to that and Redirects should be covered in some or most cases. But it's not 100%, right?
What also remains problematic AFAIK is the issue with favicons but that should be solved in FF63 when extensions are given the ability to see these requests and be able to strip ETAGs for example or block favicons requests to 3rd-parties or strip cookies from such requests or whatever else extensions want to do.

**Comment by gorhill** [comment] 2018-08-17 16:17
> But it's not 100%, right?

Well if a tracking server is not in one of the list then uBO's strict-blocking won't kick in.

**Comment by fmarier** [comment] 2018-08-17 18:26
> is there anything you're allowed to tell us in regards to what you and your guys make of these results and maybe plans to fix those issues?

Our plan is to fix the existing bypasses and then flip the default so that all requests go through TP unless specifically exempted (e.g. Firefox update). The details are in https://bugzilla.mozilla.org/show_bug.cgi?id=1207775.

**Comment by curiosity-seeker** [comment] 2018-08-18 10:37
@gorhill 

> Well if a tracking server is not in one of the lists then uBO's strict-blocking won't kick in.

Hm - I'm not sure if I understand. The [Strict Blocking wiki site](https://github.com/gorhill/uBlock/wiki/Strict-blocking) says that "uBO will block the web page served by a server found in one of the malware list". But a tracking server is usually not on a malware list - so how could it trigger strict blocking? I'm confused. Or is that wiki site not up-to-date?

**Comment by Thorin-Oakenpants** [comment] 2018-09-16 11:13
FYI: not sure when, but [1447935](https://bugzilla.mozilla.org/show_bug.cgi?id=1447935) is no longer access denied

**Comment by crssi** [comment] 2018-12-12 08:51
> gorhill has us covered, assuming your config is "right"

What is the right config for uBO?

> I'm not worried personally, as I lock down basically all persistent storage

How do you lock down all persistent storage?

**Comment by Thorin-Oakenpants** [comment] 2018-12-12 09:02
> What is the right config for uBO?

Nothing for you to do. Just config uBO however you like.

> How do you lock down all persistent storage?

Cookies control cookies, localStorage and IDB - and I block all cookies by default. appCache is disabled. SW's are disabled (and "web workers" in uMatrix is default block). And I clean on close, which most likely clears other shit, like cache, sw cache (if I had any), and other things

**Closed** 2019-05-07 11:39 UTC
Labels: firefox bug

**Comment by Thorin-Oakenpants** [comment] 2020-05-26 07:36
updated OP
