### ISSUE TITLE
Pictures / Content load slowly and only step by step [solved: privacy.trackingprotection.enabled]

### ISSUE THREAD

**Issue by Utini2000** [ghacksuserjs/ghacks-user.js#327] opened 2018-01-05 11:29 UTC
Hey there,
due to compatibility and performance issues I decided to switch from Parabolas Iceweasel (Linux) to stock Firefox + ghacks-user.js.

Things are a lot better now except a few issues that I fixed by googling + changing them myself.

How ever, there is still one issue I noticed yesterday:
Pictures, or sometimes web content in general, load slowly and only step by step. As an example:
When browsing/scrolling down the list "people" on linkedin.com, then the user pictures load slowly and only step-by-step as I scroll further down. 
In the past all those pictures were already loaded and I could scroll down + work faster. 

Could you tell me which settings are causing this? 

Thanks in advance!

**Comment by crssi** [comment] 2018-01-05 11:50
I would dig into section 1000.

Cheers

**Comment by Thorin-Oakenpants** [comment] 2018-01-05 14:04
> Pictures, or sometimes web content in general, load slowly and only step by step

Does this happen with a new profile and no user.js - because when items are displayed is handled by Firefox's rendering/compositor/whatnot (which we don't mess around with) ..  and it does things like this to speed up first page display etc. You said you have only just moved to FF - hence why I am asking if this happens in a brand new profile.

**Comment by Thorin-Oakenpants** [comment] 2018-01-05 14:11
A typical example for me is cracked.com (eg http://www.cracked.com/photoplasty_2474_warning-labels-products-should-be-required-by-law-to-display/ ) - sample is a photoplasty .. as soon as it loads, scroll down as fast as you can go and you'll see images etc not loaded, but as soon as you force the elements into view they fill in (they are also being downloaded in the background anyway, you're just forcing the pace).

Another one seems to be news sites landing pages .. the Verge is another one - https://www.theverge.com/ - same thing, you can **see** the images getting filled in as you bring elements into view. THIS is normal behavior AFAIK - I guess it depends on your connection speed/transfer rate and the site (JS code can definitely not load pictures until in view AFAIK)

**Comment by Utini2000** [comment] 2018-01-05 14:17
@Thorin-Oakenpants you are describing exactly my "problem". Best example for me was linkedin.com as I never had the "profile pictures" missing (and waiting to be loaded) when scrolling through a list of people.

As you are 100% certain that the user.js cannot be the cause of this, it must be related to my ISP provider then. It is just weird that I noticed it right after applying the user.js

I installed Firefox ~7 days ago and since then used the newly created profile. I just applied the user.js to this profile 2 days ago.

Btw for disk caching: 
I use a 5120GB SSD and 16GB RAM. I often have several windows with a total of 80-100 tabs opened. Would it be better to enable disk caching in that case?

**Comment by Thorin-Oakenpants** [comment] 2018-01-05 14:37
I didn't say it wasn't the user.js - but it's been my experience for years, and this is how rendering is meant to be done (loading and displaying items in priority) - I am on a shitty ADSL connection in a fifth world country, in a remote outpost.

> It is just weird that I noticed it right after applying the user.js

Can you try it in a new profile. You can download a portable FF57 from here: https://portableapps.com/apps/internet/firefox_portable . Run the exe to unpack the portable version and run `FirefoxPortable.exe` - this will create a new profile under the data folder. Load a site like linked in, login, save password if you want, bookmark the site. See how long the avatars or whatnot take to load

Then clear all data (Ctrl-Shift-Del), set time range to everything, check everything, and clear it (especially cache). Close FF, add the user.js as IS, no changes, from here. Go to your linked in bookmark, login in, see if there is a difference.

---
In your main FF profile, you could maybe also try changing hardware acceleration `2508` - comment out the pref in the user.js, go to [SETTING] Options>General>Performance>Custom>Use hardware acceleration when available and check it.

**Comment by Thorin-Oakenpants** [comment] 2018-01-05 14:42
> I use a 5120GB SSD and 16GB RAM. I often have several windows with a total of 80-100 tabs opened. Would it be better to enable disk caching in that case?

Up to you. Personally, I just think of all the hundreds of thousands of writes to disk and cringe - but SSDs are meant to last longer than is practical these days. I think ArsTechnica killed a couple and it took years of continuous writes - at the rate we use the space and our computers, you'd be on a new machine a decade before it burnt out.

RAM, depends what you have loaded I guess (not just FF, but other programs) - but ram use is good. Also 80 to 100 tabs is nothing really, unless its all audio/video/gaming. It really comes down to what works best for you

**Comment by Thorin-Oakenpants** [comment] 2018-01-05 14:52
Also, thinking about it, you're also handshaking numerous times with SSL session ids - resetting `1203` `security.ssl.disable_session_identifiers` to false might speed things up a lot

**Comment by Utini2000** [comment] 2018-01-05 15:43
@Thorin-Oakenpants Thank you for all the suggestions. I will try to answer all of them one by one:

1. I set `security.ssl.disable_session_identifiers` to false again.
2. I kept disk caching off. I just thought 16GB RAM might not be enough for so many tabs and slow down FF in the end.
3. HW acceleration was already commented out (so it is enabled).

As I am on Archlinux using firefox portable isnt that handy.
What I did instead was to create a new profile with `firefox -no-remote -ProfileManager`.
I then tried linkedin with the new profile and it was loading pretty fast (I still saw the pictures loading as I scrolled but it was nearly instant).
I then cleared all data, closed FF, added the user.js and started the profile again.
This time linkedin was again really slow.
I would see names and then 2-3 seconds later finally the image was visible as well. 
Way longer than without the user.js

**Comment by ArchangeGabriel** [comment] 2018-01-05 15:48
@Utini2000 Did you then try adding just the user.js to your new profile to rule out extension or anything else? For instance [ClearURLs is currently killing my browser](https://github.com/KevinRoebert/ClearUrls/issues/26).

If so you should start looking at https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting. You can use `--profile` option also when running from a terminal to specify a specific path.

**Comment by ArchangeGabriel** [comment] 2018-01-05 15:51
Note on debugging, my exact procedure:
1. `mkdir /tmp/temp`
2. `firefox --new-instance --profile /tmp/temp` (`--new-instance` is so that I can keep my currently running Firefox)
3. Check that everything is OK.
4. `rm -r /tmp/temp/*`
5. Copy the testing `user.js` to `/tmp/temp/`. Typically I would use the halving method (=dichotomy) for the `user.js`.
6. Check whether the issue is present.
7. Until you’ve found the culprit, loop starting from 4.

**Comment by Utini2000** [comment] 2018-01-05 16:14
Hello @ArchangeGabriel , how is thermald running on your Haswell CPU? :)

I can rule out extensions because on the new profile it worked fine, until I added the user.js. 
The only change was the user.js.

So it must be something inside the user.js... I just don't know what it could be.
I worked twice through the complete file but I cannot find anything that I can connect to a slower loading of images when browsing a website?

**Comment by ArchangeGabriel** [comment] 2018-01-05 16:27
Well it’s not running at all since the Haswell CPU has been sleeping for 10 months now. ;)

Then just go for the halving method until you can find the culprit.

**Comment by earthlng** [comment] 2018-01-05 17:12
could be HTTP2, prefetch stuff, workers or maybe InterSectionObserver.

**Comment by Utini2000** [comment] 2018-01-05 18:16
@ArchangeGabriel oh lucky you :P 
@earthlng I will try them out tomorrow, together with @ArchangeGabriel recommended debug method.

**Comment by Thorin-Oakenpants** [comment] 2018-01-06 12:43
This is not very scientific, but here goes

 - First of all, I have a side-issue where in the last 3 weeks I have a lot of interrupts and my CPUs heat up, even on light'ish tasks - I think I need to check my PSU / RAM. PC is 7 yrs old (AMD Black Panther Uber-Something, 8GB RAM, dual out NVidia something - bought the parts, built it myself - was almost state of the art 7 yrs ago - **Skyrim ran like a dream, until I took an arrow to the knee** - and except for heavy tasks). OS install is also 7yrs old but almost nothing is installed - its all portable. It runs damn well, sits in my German precision made enclosed 32ru server rack and has 4 fans and a ton of venting etc. It does get noisy and heat up a little when I do things like rip a music CD or play a 1080 video - which is rare.

In the last 3 or 4 weeks (I don't think it was when I updated to 57, and I skipped 57.0.1 but may have been 57.0.2) and it is not related to the above problem (of interrupts, eg on a reboot they do not really exist which is what I just did with these tests below), Firefox has become slow to load...

...Firefox has become slow to load web content (so thanks to OP for bring this issue up) - for example, connecting to my local news site takes 3 seconds or so, and THEN it starts to render. Connections seem slow, and CPU spikes etc. I'm almost ready to reinstall the OS (and test my RAM first from a hirens boot).

### Control nilla profile in a FF57.0.4

- Added uBlock Origin and configured it the same as current FF profile and for the three sites (see below) to work
- Tweaked a few things to match my current FF profile - eg disk cache off (which it is in portables anyway), mem cache on, custom processes = 1
- Removed system addons, bookmarked the 3 test sites
- set up Ctrl-Shift-del to clear everything (so I can reload a page to gauge timings)
- set everything possible to clear on close

### Test sites
- my local news site (not telling ya what it is)
- [The Verge](https://www.theverge.com/) - the landing page has loads of squares for images, and you can scroll really fast to the bottom to outrun the rendering/DL'ing
- A Cracked.com [photoplasty](http://www.cracked.com/photoplasty_2474_warning-labels-products-should-be-required-by-law-to-display/) with 28 entries - ctrl-end to outrun the images etc

### current FF profile (slow!)
- news site: 2 to 3 seconds to connect (I can see lower right bottom in status overlay the text saying `looking up`, `connecting to`, `waiting for`, `performing handshake..`, `transferring`, etc) and THEN it displays nice and speedy like
- Verge: similar - noticeable delay before anything renders as it connects. This one has loads of picture element placeholders, and it takes a while to fill them all in - I quick ctrl-end to the bottom and wait for the black squares to fill in - maybe 3 to 5 seconds
- cracked: ditto as verge etc - slow connection - due to more images, even easier to outrun the images

### control nilla profile (speedy!)
- the news site connected and starting displaying almost instantly (a quarter of a second?)
- verge & cracked: connects instantly - less lag in pics catching up

### control nilla profile with user.js added
- not as good as the nilla control profileand nowhere near as bad as my current setup - maybe 1 second, not 3 seconds - I'll have to go reopen it and post back (haven't got concurrent profiles enabled right now). I've hard-loaded those sites so many times I can't remember now

### conclusion
- There's definitely something slowing down initial connections (not the actual rendering). I will dig deeper. HTTP2, FPI, RFP, SSL Session tickets, etc - **maybe collectively they're causing it**. The connections for images (eg verge connects to 3rd party vox, cracked to crackedcdn - linked in profile images to?) being yet another DNS and domain and handshake may explain the delay there
- I can disable all my extensions bar uBlock and see if the speed in my current FF matches the nilla control with user.js (It should) - maybe the excessive gap (an extra 2 seconds) is caused by an extension

soz for the messy and long writeup of my test

**Comment by Thorin-Oakenpants** [comment] 2018-01-06 12:59
OK.. I just nailed the 2+ second diff on my load times - its an extension - ClearURLs, its really hampering load speeds (especially noticeable on my local news site, not so much elsewhere) @ArchangeGabriel , @KevinRoebert  - see https://github.com/KevinRoebert/ClearUrls/issues/26 - yes, all tests done with the new version released earlier today which fixed issue 26

**Comment by Utini2000** [comment] 2018-01-06 13:38
@Thorin-Oakenpants I am glad that you figured out what cause your problems.

Unfortunately for me it is not an extension that causes the slow down.

**Comment by Thorin-Oakenpants** [comment] 2018-01-06 14:00
^^ I know. Eliminating my shitty CPU interrupts, eliminating that one site massive difference (and do doubt it impacts others in different degrees), I still see a slight diff in loading speeds - but I'm done testing for today :)

Tomorrow I will try combos of things affecting connections

**Comment by Utini2000** [comment] 2018-01-08 09:27
Using @ArchangeGabriel testing method I found the problem. And it is really weird and I do not understand how this command can cause so much troubles but for me it does:

`privacy.trackingprotection.enabled`

If set to "true" then pictures will need 2-3 seconds to load.
If set to "false" (default) then everything works instantly.

**Comment by Thorin-Oakenpants** [comment] 2018-01-08 11:26
0420 is inactive in the user.js, although we did have TP on for all windows at one stage

If you want you can @fmarier from Mozilla who works on TP/SB etc and raise an issue

**Comment by earthlng** [comment] 2018-01-09 15:23
@Utini2000 thanks for reporting back.
I've added `privacy.trackingprotection.enabled` to the new troubleshooter script and updated the title.

**Closed by earthlng** 2018-01-09 15:23 UTC

**Comment by Thorin-Oakenpants** [comment] 2018-01-09 23:08
FYI: the ClearURLs issue has been resolved - seriously, the `lag` was like an extra 2 to 3 seconds on that troublesome site of mine, which Kevin Röberts analyzed. 1: its not a great design in terms of efficiency (all the js is linked in the header - I assume this is what delays the render due to the extension having to parse it all) 2: it's fairly heavy (number of elements) 3. I do not have a super-computer or super-fast connection

turns out using `async` is really slow (even though Mozilla recommend it) - anyway, after the latest ClearURLS, I now cannot tell the difference. After the first page loaded from the site (in about a second), all subsequent pages are near instant. No doubt many other sites suffer the same issues - so overall everyone should get speed improvements.

Other than that, since I do not have TP on in normal windows, I have not noticed any other slowdowns
