### ISSUE TITLE
Addressing default search engine privacy

### ISSUE THREAD

**Issue by RoxKilly** [ghacksuserjs/ghacks-user.js#88] opened 2017-04-24 23:19 UTC
One of the biggest [privacy exposures](https://www.cnet.com/news/aols-disturbing-glimpse-into-users-lives/) users face on the web is definitely the history of their searches.  Yahoo is Firefox's default search engine (Google was default until 2014). We all know about Yahoo's security and privacy history in recent years. In a word: deplorable.  

What do you guys think of replacing Yahoo with a privacy friendly option such as DuckDuckGo which [fetches Yahoo results](https://www.ghacks.net/2016/07/01/duckduckgo-yahoo-partnership/) behind the scenes?  A [javascript-free version](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-lite/) is even available on AMO.

Alternatively, if you think users would rather see Google results, [Startpage](https://addons.mozilla.org/en-US/firefox/addon/startpage-https-privacy-search) proxies the searches and stores no logs so Google can't track users or even know who is performing those searches.

If the default search engine cannot be set via `user.js` file, one possibility is to add a reference to private alternatives the way you make reference to addons that should be used to supplement the configs.

**Comment by Atavic** [comment] 2017-04-24 23:56
I remove the search bar and use a local home page with links to search engines.

**Comment by Thorin-Oakenpants** [comment] 2017-04-25 04:04
This. IMO, falls outside the scope of the project (via the user.js). For starters, setting the default engine requires it to be present, and different builds will have different default engines. It's also problematic from a language perspective. We have no right to impose/change someone's search engine. For those who have no idea that their search history per engine (bing, yahoo, google etc) is being collated (via a half dozen points, such as IP, SSL session ticket ids, cookies, wifi location data etc), well, 2000 called and want their village idiot back.

That said, if someone wants to add to the wiki with alternative search engines and tips and tricks, go for it. But it opens up a slippery slope of expanding beyond our mandate - what next, alternatives to gmail? A list of web email services? A list of hsts blocklists?

Will we then be expected to provide more and more OpSec info eg how to daisy chain VPNs, or use TOR over VPN vs VPN over TOR, or how to use tails, or how to buy a burner phone and avoid camera surveillance... or how to stick tiny pebbles in your shoes to hide your gait from biometric sensors

Look, I totally get that the search engine is a part of Firefox, and has controls. But who the hell are we to tell people what service(s) they can and can't use. I WILL not do this in the user.js (no arguments - at the very least it would be commented out, but I am totally against it period), but am open to a wiki page.

I am also open to listing these search engines from AMO (never used any myself, I used Add To Search Bar, which can be done manually anyway, so I actually have zero "installed" or default engines)

**Comment by RoxKilly** [comment] 2017-04-25 05:12
>  But who the hell are we to tell people what service(s) they can and can't use

Im perplexed by this. I may be mistaken but didn't you disable the Pocket service at some point? Or Adobe's Encrypted Media DRM service?

> This...falls outside the scope of the project. I WILL not do this in the user.js

OK.  It just occurred to me that using the default search bar is one way a lot of privacy gets exposed in FF's default configuration and I understood your objective to be to harden FF settings for privacy and security so I thought I should bring it up here. Thanks for reading and considering.

**Comment by Thorin-Oakenpants** [comment] 2017-04-25 05:36
There's a slight difference between removing services entirely (DRM) and dictating what service to use

**Comment by earthlng** [comment] 2017-04-25 10:26
Hi, I agree with OP that search engines are a major problem. But I also agree with Pants that nowadays everyone should know about that. Heck, even my mother knows not to trust Google.
But since we also recommend Addons I think we can recommend some search engines, or even host some opensearch.xml files directly. DDG is one of the built-in search engines and we could add a pref (commented out maybe) that sets that engine as the default. 
`user_pref("browser.search.defaultenginename", "DuckDuckGo");`

BUT the builtin engine also has some tracking parameters and a link for suggestions. So it's not ideal but still better than using the builtin in yahoo engine (which also has those parameters)

```xml
  <Url type="text/html" method="get" template="https://duckduckgo.com/" rel="searchform">
    <Param name="q" value="{searchTerms}"/>
    <MozParam name="t" condition="purpose" purpose="contextmenu" value="ffcm"/>
    <MozParam name="t" condition="purpose" purpose="keyword"     value="ffab"/>
    <MozParam name="t" condition="purpose" purpose="searchbar"   value="ffsb"/>
    <MozParam name="t" condition="purpose" purpose="homepage"    value="ffhp"/>
    <MozParam name="t" condition="purpose" purpose="newtab"      value="ffnt"/>
  </Url>
  <Url type="application/x-suggestions+json" template="https://ac.duckduckgo.com/ac/">
    <Param name="q" value="{searchTerms}"/>
    <Param name="type" value="list"/>
  </Url>
```

We could sanitize that file and host it here, but it's not possible to overwrite an engine with the same name as the default ones, so we would also need to change the engine name.

**Comment by Thorin-Oakenpants** [comment] 2017-04-25 11:12
Lets not get too involved with this. As I already said it's problematic in the user.js, and as I already said I am fine with some sort of wiki page (eg explain how to manually add sanitized engines, and/or point at some on AMO)

There is not only `browser.search.defaultenginename` there is also `browser.search.defaultenginename.US`, as well as `browser.search.isUS`. And then, how do we handle all the other locales/language builds? Has anyone looked at those? Do they need to be considered?

Disabling a service/feature/protocol (hello, webgl, DRM) is not the same as changing someone's choice of a service (which can't be disabled, at least not via the user.js) - so please don't compare them. IMO it is pointless adding anything to the user.js itself.

-slightly OT
As for the search box, I am currently using CTR to force the searchbox dropdown to itemize with an icon + text of the engine. With a default FF, it instead displays buttons only - I find this is terrible from a few angles (but I have until 57 to work it out) - when you select a button, it auto-searches, with CTR or old behaviour it does not. Nothing happens until I hit the enter key or the search icon. (I may have to do some more testing, its been a while)

example:
- google engine: type in sans quotes "dwarf tossing", hit enter
- change to wiki engine and blam! it auto searches wiki
- what I wanted to do was simply change engines as I was about to search wiki for SOMETHING ELSE
- even if the search field is empty, it still loads a search (eg google home search page)
- I do not want to auto-clear the search field after searching, as I often need to search the same term on several sites

How do you make the default searchbar controls NOT DO ANYTHING unless you hit enter or click the search icon?

**Comment by earthlng** [comment] 2017-04-25 11:25
> And then, how do we handle all the other locales/language builds?

Yes, that does seem to be a problem. The searchplugins in the omni.ja are in a "en-US" subfolder so they are likely localized and DuckDuckGo is maybe called PooPooHoo in Thailand or something ;)

> How do you make the default searchbar controls NOT DO ANYTHING unless you hit enter or click the search icon?

good question - no idea. I basically only use the searchbar for the indicator when an opensearch.xml is detected. Otherwise I copy and paste the search term and search with "s dwarf tossing" for startpage and then "x dwarf tossing" for ixquick etc. Definitely not ideal but I never bothered to search for a better way to do it.

**Comment by Thorin-Oakenpants** [comment] 2017-04-25 11:33
> good question - no idea

We have until 57, and from some early mockups it looks like the list MAY be back (there are some definite u-turns on UIX)

**Comment by Thorin-Oakenpants** [comment] 2017-05-01 19:25
I added this to the sticky wiki as an item to keep track of. When or if someone drafts up a wiki article (it's just github markup you can use in here), and we finalize it, then I can add the pref to the user.js with a note about the engine name having to exist, etc, AND link to the wiki article

wiki ideas:
- list of search engines
- list of AMO search engines
- list of sanitized code
- how to manually add these engines
- make sure we build in keywords
- maybe provide a zip bundle for zip profile\searchplugins

**Comment by atomGit** [comment] 2017-05-14 13:18
re: 

* list of sanitized code
* how to manually add these engines

i use the [XML Search Engines Exporter/Importer](https://addons.mozilla.org/en-US/firefox/addon/search-engines-export-import/) add-on to export the engines, both default and those i add, and then sanitize them and dump them in `/searchplugins` folder (you also have to delete the `search.json.mozlz4` file and restart the browser to get them to register)

btw, one of the best privacy-centric meta-search engines i've found is [searx](https://searx.me/) - it uses, or can use, a whopping pile of 3rd party engines and is very customizable - rather than overloading searx.me however, please consider using one of the many other privately hosted [sear instances](https://github.com/asciimoo/searx/wiki/Searx-instances)

unfortunately, other than the big boys, there seem to be very few alternative indexes that actually crawl the www looking for content - DDG, Startpage, searx, etc., all pull their results from Google, Bing, Yahoo, etc., which means their results are also open to censorship

[YaCe](http://yacy.net/en/index.html) is a notable exception in that it is an indexer and also a distributed P2P search engine, but it's index is still very small - you can [find a demo here](http://search.yacy.net/)

**Comment by atomGit** [comment] 2017-05-15 11:02
> I added this to the sticky wiki as an item to keep track of. When or if someone drafts up a wiki article (it's just github markup you can use in here), and we finalize it, then I can add the pref to the user.js with a note about the engine name having to exist, etc, AND link to the wiki article
> 
> wiki ideas:
> 
> * list of search engines
> * list of AMO search engines
> * list of sanitized code
> * how to manually add these engines
> * make sure we build in keywords
> * maybe provide a zip bundle for profile\searchplugins

i'd like to contribute to this if you want but i don't know how - is the wiki done through pull requests or do i just comment here?

i can lay out the basics regarding how to add and sanitize search engines and list some engines i think are good as far as results and respecting privacy

**Comment by Thorin-Oakenpants** [comment] 2017-05-15 12:26
You could create a wiki page in your repo - or paste a draft in here. Or you could do an article on your 12bytes blog, and we'll reproduce it here, and credit you and link back to 12bytes - or we can all collaborate together to come up with a three/four page search wiki section (and you could repost em at 12bytes as a joint author). All a wiki is, is basic markup. I forgot to add to that itemized list that we need to make sure we have unique base64 icons (eg google vs google images etc - yes I still think we should provide sanitized google ones).

Collaborators with "write" access I think can edit the wiki. Otherwise users can fork the repo, and do a mockup in their fork.

eg sample draft

```
### Search Engines

1. AMO
- [DuckDuckGo](https://blahblah.com/) - **h**ttps://blahblah.com
```

---
I think we should decide the structure. I would like to store all the sanitzied xml files unzipped in a folder, but list them in the wiki. So we could have something like

:small_orange_diamond:  Search Engines
- 4.1 Into (written by @RoxKilly), list of engines (make a new topic and list all engines), their AMO, and a sanitized XML (stored in searchplugins root folder here in repo)
- 4.2 How to maintain/edit (eg rename them, change the base64 icon, change keyword, how to not clash with existing installed engine names)
- 4.3 How to use the search bar without unintentionally leaking/searching (note, I use CTR which restores the "list" rather than just icons - without CTR I cannot properly control searching when changing engines - any touch of the icon to change engines makes a new search, even if the field is null), eg tips on key word searching etc

We could easily get page 4.1's list of engines done, then decide on keywords, then create sanitized XMLs and upload them all, and then do a 4.2 on how to add/edit/maintain them.

**Comment by Thorin-Oakenpants** [comment] 2017-05-15 13:13
Step 1: see #118 for the initial page 4.1 list of search engines, info on them, page link
Step 2: write a wee intro on page 4.1
Step 3: add in links to AMO
Step 4: decide keywords, build sanitized XUL versions for all of them (upload to root subfolder on repo)
Step 5: write 4.2 - how to remove all your installed engines, add all our sanitized ones, then pick and choose what to keep and change the order
Step 6. write 4.3 - how to edit/create xml engines (eg site specific) and how to make a base64 icon etc
Step 7. have a beer

**Comment by earthlng** [comment] 2017-05-15 15:37
I would volunteer to do step 7 please

**Comment by Thorin-Oakenpants** [comment] 2017-05-15 16:43
^^ My take is we provide a zip or individually ALL the xml files (base64 icons inside). Instructions on say wiki page 4.2
- Open FF, delete ALL your search engines
- Close FF, stick in ALL the search engine XML files you want in the dir
- Open FF, go to search options, change the order to hearts content
- ^^ might need to also assign keywords

Wiki page 4.3 would be how to make your own - eg site specific ones. Site Specific search engines should be the first choice, but we ain't gonna list all of those. I frequently use about a dozen non general search engines, just to stay off google (and no, the other engines suck at finding what i am after).

**Comment by earthlng** [comment] 2017-05-15 16:53
I don't think it works that way. Once the search.json.mozlz4 exists, the searchplugins folder is ignored.

**Comment by Thorin-Oakenpants** [comment] 2017-05-15 16:55
I'll have to play. I migrated all my engines that way before.

**Comment by earthlng** [comment] 2017-05-15 16:56
yes, it used to work but not anymore.

**Comment by atomGit** [comment] 2017-05-16 11:05
> afaik it doesn't work that way. Once the search.json.mozlz4 exists, the searchplugins folder is ignored.

and ...

> yes, it used to work but not anymore. Also if you change/edit an xml file in searchplugins it won't update it.

my understanding is that the searchplugins folder isn't ignored entirely - if you add an engine and delete search.json.mozlz4, the new engine becomes available in your search drop-down - i think what's happening is the new engine is imported into search.json.mozlz4, but i'm not entirely sure - for example, i added the Trove engine and the Searx engine, but only Trove shows up in search.json.mozlz4 - why this is, i don't know, but both are available from the search bar

as far as having to delete search.json.mozlz4, i believe this was the case before the move to this file (i forget the file name of the old one ... searchengines.json or something?) - even with the old file, you still had to delete it to refresh the available engines in the search bar

... and i think you're going to need some help with step 7 - luckily i'm available to collaborate regarding this issue :)

**Comment by earthlng** [comment] 2017-05-16 13:19
@atomGit can you remove the image shenanigans in your [article](http://12bytes.org/articles/tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs), please?
We link to it from our Readme and it's not great that I can't even see the images without enabling JS and allow the redirect on sync.1dmp.io, or use a custom userscript to fix it in-place. Ideally host the images on your own domain and use the img src path instead of data-src, so it works without Javascript. IMHO it's a bit paradoxical to write an article about blocking/controlling 3rd party resources and JS while using those exact same practices. I'm only asking to change it for that one article. If you keep doing it that way on all your other articles I don't care.

**Comment by atomGit** [comment] 2017-05-16 15:46
i thought that lazy-load plugin i was using worked when JS was disabled - it didn't, so i just switched to another one

as for self-hosting the images, that's something i intended to do and then forgot about it - i don't have a lot of time to fool around, but i'll get that done at some point

> edit: holy shit man ...

lol - yeah, that's something i've been studying for a pretty long while now - try the quiz if you didn't already

**Comment by earthlng** [comment] 2017-05-16 16:14
Thanks mate. 100% in the quiz, but I had to take a wild guess on the forgeries. I knew 3, 5 + 6 were definitely forgeries but had not seen the originals for the other ones. And I wasn't sure about Q8.

**Comment by earthlng** [comment] 2017-05-16 16:22
The images are still redirected via 1dmp.io to postimg.org. Do you get money from that or do the plugin devs get money from that? It would be great if you could host them directly or at least use the postimg urls until you have the time to upload them to your own domain.

**Comment by atomGit** [comment] 2017-05-17 01:19
if you want to talk further you can comment on my site or send me your email from my contact form - i'd be very interested in hearing your POV

sorry for going astray :)

**Comment by atomGit** [comment] 2017-05-17 01:24
AH HA! you edited your comment i see LOL

100% eh? i got your original comment in my reply notification email :)

good for you, but keep in mind that "they" are victims too

sorry to all others here as i am now way out of bounds and an order of magnitude off topic

**Comment by Thorin-Oakenpants** [comment] 2017-05-17 01:40
WTF r u two talking about? Where's this quiz? I wanna see if I can beat earthlng's 100%

**Comment by atomGit** [comment] 2017-05-17 01:59
ok, but i warn you ... your world view might be very disrupted :)

the [quiz](http://12bytes.org/articles/history/test-your-holocaust-knowledge)

**Comment by Thorin-Oakenpants** [comment] 2017-05-17 02:06
Sweet .. got 6 out of 10 using the monkey on a typewriter approach

**Comment by atomGit** [comment] 2017-05-17 02:07
noob

**Comment by earthlng** [comment] 2017-05-17 09:06
Well, fuck me, you got that via email huh?! shit
I felt I had to censor myself because I didn't know how Pants felt about it and didn't want to negatively impact this project. Unfortunately I also live in country where we don't have free speech and instead "the right to remain silent" so to speak. Well at least the emails you all undoubtedly received are not public, but now I have even more incentive to keep my real identity hidden because you guys could have me arrested. Please don't ;)
So how does that work with the email notifications? Do you get emails for every change made or only new posts? Could I write a "bump" comment and then edit it to say illegal things and subscribers wouldn't see that?

**Comment by earthlng** [comment] 2017-05-17 09:52
Since the jig is up, I guess I can admit it now - yes, I got 100% correct in the quiz because I'm a naughty boy and have researched all kinds of things.
But make no mistake, I'm not a racist - I hate everyone equally :)

**Comment by atomGit** [comment] 2017-05-17 10:49
> So how does that work with the email notifications? Do you get emails for every change made or only new posts? 

i assume notification mails are sent immediately after you publish a comment, so if you publish, then edit and re-publish, it seems 2 mails would be sent

**Comment by Thorin-Oakenpants** [comment] 2017-05-17 11:51
>  I didn't know how Pants felt about it

I don't care. I'm not the internet PC police. I'm with [Wonko the Sane](http://hitchhikers.wikia.com/wiki/Wonko_the_Sane) on this one.

>  Unfortunately I also live in country where we don't have free speech 

Have you considered impeaching him yet? Or an uprising? Maybe a trek north and seeking asylum in Canada.

**Comment by Thorin-Oakenpants** [comment] 2017-05-21 04:26
OK gals, I have just cleaned up and removed the last 8 or so comments from 4-5 days ago which were OT, just to keep things clean. Am now afraid earthlng has been captured by the acronyms, it's so quiet in here (sing out if you can earthlng, just not like a canary!)... this comment will self destruct in 5 seconds

**Comment by Thorin-Oakenpants** [comment] 2017-09-09 05:23
#118 can handle the task for doing the wiki pages - closing this

**Closed by Thorin-Oakenpants** 2017-09-09 05:23 UTC
