### ISSUE TITLE
FYI: user_pref("dom.webnotifications.enabled", false); can cause site breakage

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#256] opened 2017-10-09 09:15 UTC
user_pref("dom.webnotifications.enabled", false);

prevented an online shop to display product images.

It took me a while to troubleshoot this issue so I decided to share. I thought this pref has nothing to do with image content loading. The URL is not popular internationally, so I won't share it. Pants you can have it via email if you're interested.

**Comment by Thorin-Oakenpants** [comment] 2017-10-09 09:47
Sure - email it to me - is it sensitive for some reason .. have you been looking at buttplugs and gimp suits? Or are you afraid it might give away your country? Honestly, I'm okay with the sexual fetishes, I don't even mind if it's a MLP specialty site, or even Donald Trump's merchandise for overpriced bottled water and cheap-ass useless university degrees. I am not here to judge, bro .. just sayin' :grin: 

Any reason I can't post it here if I need help from others? Let me know in the email

**Comment by Just-me-ghacks** [comment] 2017-10-09 17:29
Hilarious! Please check your inbox.

**Comment by Thorin-Oakenpants** [comment] 2017-10-11 01:31
OK, got it. Soz for the delay - I am a bit swamped for the next few days. Not even what I can do, but will get around to it

**Comment by Thorin-Oakenpants** [comment] 2017-10-31 06:36
Two issues:
1. you said the site requires dom storage and webnotifications to function properly (display images)
2. you asked if it's OK to have dom webnotifications enabled permanently

### 2
I am not 100% sure on all this workers stuff. I thought (and the documentation said so) that there was some sort of chain here: "Push and web notifications require service workers, which in turn require workers." (from the user.js). But I have seen youtube behave differently when just service workers was allowed - see #234 (so clearly dom.workers does NOT control service workers). Maybe the same applies to notifications.

See 2304 in the user.js - you can allow site exceptions - so there is no need to default allow. As for whether of not this works without allowing serviceworkers, IDK. There are 2 prefs listed and the `dom.webnotifications.serviceworker.enabled` implies by its name that it has a dependency on serviceworkers being enabled. As for `dom.webnotifications.enabled`, IDK. I also have no real idea on what the site exception option "receive notifications" refers to - as my default seems to be "always ask" - I think this UI may be broken a bit like Maintain Offsite Storage (IDB) is, which BTW is removed in 58.

Add to this the fact that dom.push.* notifications (2305) and dom.webnotifcations* (2304) are somehow linked - it's somewhere in the list of links in the 2300 section header, that one is obsolete or controlled by the other. I can't seem to find it.

At the end of the day - workers SUCK from a control and privacy perspective. They have their own permissions for IDB and their own caches and all sorts. Nightmare .. and a bit of a mystery (to me).

### 1
see next post

**Comment by Thorin-Oakenpants** [comment] 2017-10-31 07:01
### 1

* Setup: new profile in FF56
* Note: dom.storage is default inactive in the user.js, so is assumed to be allowed - only really looking at the workers stuff
* Note: only 1st party cookies allowed
* Note: I am not blocking any JS or third party content (cept 3rd party cookies) - no NoScript, no uBo, no uMatrix
* Note: images are coming from a 3rd party: akamaized

:small_orange_diamond: when I reset
- close the site
- clear **everything** via ctrl-shift-del (yes this clears the IDB entries)

:small_blue_diamond: test 1
- load site, works fine
- creates IDB entires for site and also creativecdn
- creates a cookie for site

:small_blue_diamond: reset between tests & tests 2+3+4+5+6+7
- each of these prefs were done in individual subsequent (accumulative) tests
- test 2: set `dom.workers.enabled` => false
   * note: no IDB entries anymore - interesting that workers, like service workers, seems to allow IDB
- test 3: set `dom.serviceWorkers.enabled` => false
- test 4: set `dom.webnotifications.enabled` => false
- test 5: set `dom.webnotifications.serviceworker.enabled` => false
- test 6: load site and deny cookies via site exceptions & reset & test
   * I assume you would want cookies anyway if you were to login and buy something
- test 7: set `dom.storage.enabled` => false
- load site, works fine

### Conclusion
Well I disabled everything (everything workers, local storage - in fact all storage including IDB) and it works for me. I even killed cookies on the site (and blocked all 3rd party cookies).

I do not think the issue is what you think it is - I cannot replicate the problem. I suggest you look at uBo, uM logger details for what happens with requests to akamaized (which serve the images)

**Comment by Thorin-Oakenpants** [comment] 2017-10-31 07:09
^^ I also just applied the user.js to this profile on top of the above changes/tests (so `dom.storage.enabled` is still false), and it still works

**Comment by Just-me-ghacks** [comment] 2017-11-01 15:18
Pants, you can not replicate the problem because the site has been updated. It's a pity, because we won't understand what dom.webnotifications.enabled has to do with image loading unless we find another site with the same issue.

I tested it properly 23 days ago. Brand new profile + user.js, no plugins, no port blocking, etc.

**Comment by Thorin-Oakenpants** [comment] 2017-11-02 00:28
> Pants, you can not replicate the problem because the site has been updated

Well .. poop! 

> It still requires dom.storage to be enabled otherwise categories and product browsing doesn't work (FF52).

Well, I clicked around, including product browsing (not sure if I got a category, but the menus on the left seem to indicate that's what they were - yes I read you original email about going into categories), and it seemed to work for me without dom.storage - but that's OK, we allow this in the user.js as the setting is inactive

> It's a pity, because we won't understand what dom.webnotifications.enabled has to do with image loading unless we find another site with the same issue.

Maybe some more reading on the spec will give some insight into what this can do

**Comment by Thorin-Oakenpants** [comment] 2017-11-04 00:34
@Just-me-ghacks

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

I will assume from this, that since it can load/store data into IDB, then these resources become available for for the domain?

**Comment by Just-me-ghacks** [comment] 2017-11-05 11:26
Maybe. However that means user_pref("dom.webnotifications.enabled", true); bypass user_pref("dom.indexedDB.enabled", false); which is strange.

**Comment by Thorin-Oakenpants** [comment] 2017-11-05 11:57
> However that means user_pref("dom.webnotifications.enabled", true); bypass user_pref("dom.indexedDB.enabled", false); which is strange

Did you test that? Or did I say that? I am getting confused. The whole storage thing is doing my head in and I've almost had enough of it :) . Like I said, seems workers have their own storage rights - eg see that YT issue where I was trying to work out how IDB entries were being created. It might become more clear when Storage Manager is finished

It's all getting too confusing TBH .. I wonder if cookies denied blocks IDB for workers? (probably not? but then PB mode denies IDB - so does IDB=false deny worker's ability to write to IDB?

**Comment by Just-me-ghacks** [comment] 2017-11-05 15:30
> Did you test that? Or did I say that?

No, no, it's just a (logical) assumption - I have indexedDB disabled by default. The site required **dom storage** and **webnotifications** to display images. So how can `user_pref("dom.webnotifications.enabled", true);` store data into indexedDB when indexedDB is disabled?

The site in question has been updated. The issue is not common, so I suggest we just close this thread until we find another site that loads images / content via webnotifications.

**Comment by Thorin-Oakenpants** [comment] 2017-11-06 03:38
> No, no, it's just a (logical) assumption. I have indexedDB disabled by default. The site required dom storage and webnotifications to display images. So how can user_pref("dom.webnotifications.enabled", true); store data into indexedDB when indexedDB is disabled?

Yup: assumption. my observation of IDB being used is from the technical docs example. In other words, it needs a test, and because the site code changed there is no way to tell if it actually used IDB

I'll leave this open to remind me to do a couple of test re workers & IDB

**Comment by Thorin-Oakenpants** [comment] 2017-11-06 04:17
> P.S.: the site has been restored! Right now it requires

Yeah. I guess that change was just for Halloween. I cannot replicate your results.

In a brand new FF profile
- Default nilla: NOTE: There is a slideshow box with left/right arrows and 6 dots to indicate slideshow position on the HOME landing page - this is not filled in and remains blank, even in a nilla FF. It does fill with text when you click a category from the menu on the left.
- I am looking at the images that load underneath that, and images in a category (tvs) and even images on a product (and the mouse over shows all images and the slideshow works if you pop that up)
- no IDB was created

tests (reset in between each one)
- 1. set IDB=false = same result
- 2. set dom.workers.enabled => false = same result
- 3. set dom.serviceWorkers.enabled => fasle = same result
- 4. dom.webnotifications.enabled => false = same result
- 5. ***set dom.webnotifications.serviceworker.enabled => false = same result***
- 6. denied the site a cookie and reset = same result
Conclusion: workers have nothing to do with the images being loaded

Lastly
 - 7. set dom.storage.enabled = false = **pics broken**

**Comment by Just-me-ghacks** [comment] 2017-11-06 04:57
> I guess that change was just for Halloween.

Maybe they are A/B testing something. 

Right now it requires only `user_pref("dom.storage.enabled", true);` to display images.
`user_pref("dom.webnotifications.enabled", true);` is not required.

**Comment by Thorin-Oakenpants** [comment] 2017-12-08 02:09
closing this, fell free to reopen if more info comes to light

**Closed by Thorin-Oakenpants** 2017-12-08 02:09 UTC
