### ISSUE TITLE
Disable privacy.resistFingerprinting.letterboxing by default

### ISSUE THREAD

**Issue by ivankra** [ghacksuserjs/ghacks-user.js#748] opened 2019-06-19 20:05 UTC
I've recently upgraded from FF 66 to 67 and started observing this behavior:
https://www.reddit.com/r/firefox/comments/brb2h0/updating_to_firefox_67_and_i_got_this_problem/

Bisected it to privacy.resistFingerprinting.letterboxing which came from your repo which I'm tracking and updating independently of my browser and so I didn't catch the moment that flag was enabled here and didn't connect it to the breakage I saw.

The behavior makes the browser basically so ugly to the point of being unusable. Please don't surprise your users and disable this by default.

**Comment by claustromaniac** [comment] 2019-06-19 21:35
Duplicate of #728

**Closed by claustromaniac** 2019-06-19 21:35 UTC
