### ISSUE TITLE
Two issues in one :gift:

### ISSUE THREAD

**Issue by Aeriem** [ghacksuserjs/ghacks-user.js#774] opened 2019-08-17 21:24 UTC
This started out as an issue about preference 2805, and then turned into an open investigation I'm submitting to Pants' class.

First, the preference issue:

> I noticed that it had been a while since pref 2805 bugged and created a second window when I open Firefox.
> So, I decided to test it: it turns out that the bug is fixed for `privacy.clearOnShutdown.openWindows` but not for `privacy.cpd.openWindows`.
> No second window will appear when starting Firefox, but one will do when you manually clean your profile (Ctrl-Shift-Del).
> 
> Therefore, I suggest we correct the warning about this bug.

Now, I also wanted to suggest uncommenting the two prefs, as they used to be able to clean something that would not get cleared any other way, therefore enhancing privacy:

STR:

1. On a new profile, go to https://garlandtools.org/db/.
2. Add the OpenSearch search engine using the magnifying glass in the search bar.
3. In Garland Tools Database, open a few items or change some settings such as the language.
4. Toogle the `clearOnShutdown` prefs used in the template user.js.
5. Close Firefox, then reopen it.
6. This time, go to Garland Tools **through the OpenSearch shortcut in your search bar**: click on the magnifying glass, a list of your search engines will appear, click on Garland Tools.
7. On the page you land to, click on Garland Data.

Expected results:
Your items and settings were cleared.

Actual results:
Your items and settings were saved.

Fix: (The following fix used to work, I used it for a year, but it is no longer valid.)
Toogling `privacy.clearOnShutdown.openWindows` and `privacy.cpd.openWindows` to `true` clears this remaining data.
I do not know of another way to clear it, besides (maybe, didn't test) removing the OpenSearch search engine and readding it.

Now, I still suggest uncommenting those two prefs as they might still be able to clear data that isn't removed when using the current template user.js (extra privacy), and they no longer are as much of an issue as they used to be.
But discovering that this fix is no longer valid (I stopped using it for a few months.) made me wonder what was actually happening.
Should anyone have any insights, please share them with us! :)

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 05:26
Have you tested this on all platforms?

**Comment by Aeriem** [comment] 2019-08-21 06:58
I tested it on Windows, I can test on Linux too if you want. :)

Following the STR precisely is important to experience the issue.

I do not know where they are saved, this is why I submitted this issue, but maybe Bugzilla would be more appropriate, I don't want to burden you!
This happens even when setting all clearing prefs to true, though I also tested with only specific ones enabled. I can't delete this data.

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 07:14
IIRC, there were different outcomes on different platforms.

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 11:36
So I don't have to look it up again: https://bugzilla.mozilla.org/show_bug.cgi?id=1334945

**Comment by earthlng** [comment] 2019-08-21 11:48
Good catch @Aeriem ! Thanks for reporting it

I tested this on FF68 and, following your STR, was able to reproduce the problem. But adding the search engine seems unrelated because I was also able to reproduce it by just loading the page again after a FF restart.
Then I tested it with a recent FF70 nightly and it DID NOT reproduce there.
Then tested it with FF69beta14 and the problem DID NOT reproduce there either ie it's apparently fixed in FF69+.

Knowing all that, I tried to find the bugzilla where they fixed it in FF69 by looking through [all the tickets fixed in 69](https://bugzilla.mozilla.org/buglist.cgi?j_top=OR&f1=target_milestone&o3=equals&v3=Firefox 69&o1=equals&resolution=FIXED&o2=anyexact&query_format=advanced&f3=target_milestone&f2=cf_status_firefox69&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&v1=mozilla69&v2=fixed%2Cverified&limit=0) and the most likely candidate I could find was [1556093](https://bugzilla.mozilla.org/show_bug.cgi?id=1556093)

Since there's only 2 weeks until FF69 Release, I doubt that they'd uplift that patch to FF68.x even if you'd ask them but you can always try if you like.

Maybe you can test it yourself with a FF69beta portable to confirm that it's indeed fixed in FF69+?

Seems like a pretty terrible oversight by mozilla, privacy-wise, that localstorage doesn't get cleared on shutdown and nobody noticed it in all this time since FF68 release (or maybe it was broken in earlier versions too?). 

Temporary Containers to the rescue! (as it so often does) :)

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 11:53
I actually did some quick and dirty tests (for the two windows on a restart) in nightly and couldn't get that to happen - so at least for Windows, maybe that isn't an annoying issue any more

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 11:57
>  I doubt that they'd uplift that patch to FF68.x even if you'd ask them but you can always try if you like.

Hmm, so it's local storage then? Saves me some work

@earthlng Tell me if this affects Tor Browser (based on 68) with how they clear persistent data, and if it's an issue, I think know a few people who would really want that fixed

**Comment by earthlng** [comment] 2019-08-21 12:01
I didn't actually touch any of the openWindows prefs in my testing but trusted what @Aeriem said, in that it used to fix that problem in the past but no longer does in FF68.
Starting in FF69 you don't need these 2 prefs for localstorage (and others?) to be cleared correctly again on shutdown.

**Comment by earthlng** [comment] 2019-08-21 12:03
I doubt that this affects TB because they don't store anything to begin with ie PB-mode-always

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 12:04
Yeah, there's two issues here
- what I just did a quick test for: the double window on restarts (it used to happen to me on windows way back, I think, I'm sure: not sure if it happens on Linux, but PK's repo has an issue)
- the actual data sanitizing

TB: But localStorage is still used in PB mode!! isn't that where you said the problem is?

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 12:17
PPS: I'm going to take a break .. and I'm super tired. But something just struck me here. Is my 68 not clearing localStorage like it should? If that's the case, it would have to be fixed for ESR because that's a rather large f$%^king gaping hole.

Did the issue just happen for 68? Someone give me some simple STR (without a search engine), and I will test all my portable FFs for you

**Comment by earthlng** [comment] 2019-08-21 12:17
> localStorage is still used in PB mode!!

what makes you say that? The whole purpose of PB is to NOT store anything, isn't it? If what you say is true then that would be a pretty big issue and something that I'm pretty sure somebody would have noticed by now.

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 12:22
PB Mode uses lots of things, and some things it doesn't. It disables IDB and SWs for example, because they can't be cleared by host (I still don't see why they can't clear IDB by origin attributes: like containers). But it absolutely allows cookies, which in turn allows local and session storage

open your TB and hit up [this](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#cookies)
![TB](https://user-images.githubusercontent.com/16656956/63431458-62578580-c40e-11e9-837a-7da2c5a30bcc.png)

**Comment by earthlng** [comment] 2019-08-21 12:28
STR I used:

1. new profile with just the latest ghacks-user.js
2. load https://garlandtools.org/db/ and change some settings fe language and/or open 1 of the page's content menu (fe click on `5.0` then `Achievements` and `1-100`) 
3. restart FF and load https://garlandtools.org/db/ again

expected result: settings should have been reset to english language and no open "menu"
actual result: settings were restored ie language and open menu are remembered

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 12:31
STR ^^ OK, I'll be back in a few hours and will test for when it started failing in FF versions. And then I'll get Tom Ritter & Co. onto it, because this affects TB probably (not sure what else they do for sanitizing: I think they delete the files rather than vacuum them?), but it certainly affects ESR68 and that can't be allowed to happen for the next 8 releases - it's a privacy issue: so they have to get it fixed.

**Comment by earthlng** [comment] 2019-08-21 12:36
> It disables IDB and SWs for example, because they can't be cleared by host

actually AFAIK PB-mode disables IDB not because they can't be cleared by host but because they don't have session-only (ie memory-only) IDB support.

> The whole purpose of PB is to NOT store anything **permanently (session only)**

well, since this STR involves a restart I'm pretty sure that Tor Browser should be fine by not storing anything "permanently" ie nothing is ever written to disk, ergo nothing can ever be restored

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 12:52
> since this STR involves a restart I'm pretty sure that Tor Browser should be fine

Tor Browser > New Identity. Not sure if that's a restart or not. Who said nothing is written to disk? Not everything is memory only? Never heard that. They avoid disk writes if possible, especially outside the application: and they make some things memory only (certs?). Wasn't aware they made everything memory only!

So is everything in PB Mode memory-only? Is there some sort of up to date design doc on PB Mode. I understand that something could happen to leave data on disk (FF crash, power outage), and this is why it must be memory only?

**Comment by earthlng** [comment] 2019-08-21 13:08
https://2019.www.torproject.org/projects/torbrowser/design/#disk-avoidance

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 14:44
nevermind .. that's Tor Browser's design document, not Mozilla's PB Mode. But it doesn't matter - we all learn something new every day: whether that is that PB mode allows localStorage or that PB Mode relies on memory-only (to eliminate instances where disk data can survive) - I'm still not sure that is the case: not to the extent that TB does.

**Comment by Thorin-Oakenpants** [comment] 2019-08-21 17:49
Do you want the good news or the bad news or the really bad news. I have done some provisional testing in FF67, 68, 69 and 70: I will go back further

🔹 settings
 - FF Nillas, clear everything on close (and in ctrl-shift-del, for all time): i.e the eight checkboxes in the UI. I am not using the two `openWindows` settings

🔹 test sites
- A: https://garlandtools.org/db/
   * all you have to do is change the language
- B: https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html
   * don't do anything: it will set entries for localStorage and IDB

🔹 test
- open browser, clear all data
   * options> privacy> manage data -> should be empty
   * inspect `profile\storage\default` -> should be empty of web content (IDB)
   * inspect `profile\webappsstore.sqlite` -> should be empty (localStorage)
- open Site A (garland) and change the language
- open Site B (TZP) in a **new tab**
 - if you want, check options> privacy> manage data but it doesn't matter
   * manage data doesn't seem to show or take localStorage into account
- close the browser

🔹 check
- inspect `profile\storage\default` for the TZP `ghacksuserjs.github.io` files
- inspect `profile\webappsstore.sqlite` for the two sites' data
   * TZP is a random matching key+value string
   * garland is the `gro.sloot` thing

![localStorage](https://user-images.githubusercontent.com/16656956/63453708-cbec8980-c438-11e9-99c7-c3183d999eec.png)

🔹 test continued
- open browser
- revisit garland, check the language
- close all tabs, but not the browser, clear everything manually if you want, close browser
- re-inspect the persistent storage, it should be gone

🔹 results

This gets a bit messy, because I think I have found a quirk or bug. I did this exercise about 100 times over the 4 releases, because it got whacky! I checked the sqlites, or used ctrl-shift-del vs close/restart or reloaded the garland test page: doesn't matter: all methods are effective at checking the state of the persistent data. I'll start with 67

FF67.0.4 + FF68.0.2
- tabs are left open: **both** localStorage and IDB are not cleared for open tabs
- tabs are closed: initially the first test in 68 was fine, but in 67 I couldn't clear the data, so I retested 68 and found the same
   * the second part (test continued) continually failed to clear **localStorage**
   * tried browsing some sites so FF knew it had things to clear
   * tried waiting in case sessionStore or something needed to kick in
   * always made sure I did not have the sqlite open when closing or clearing manually
   * always made sure the FF exe had closed from task manager
- finally got the persistent data to clear, but not sure how. Then I tested again, and couldn't clear it, again!

FF69.0b15:
- tabs are left open:  **both** localStorage and IDB are not cleared for open tabs
- I'll have to recheck the sanitizing when tabs are closed

FF70
- tabs are left open: tried a dozen times to make sure: partially changed
   - localStorage is cleared
   - IDB is NOT cleared

🔹 some notes

So I'm not sure what to make of this. Is this by design? Did the behavior just change and it's always been this way. Is it an actual bug? If sessionRestore = off , then I say it's a bug. If sessionRestore is on, I say it's intended behavior. Note: all FF versions did not have session restore

Haven't tested with the two `openWindows` prefs, so I should do that to make sure that they always clear the data. But this might fuck up sessionRestore (for those that use it). And does the double window on restart still happen?

**Comment by Thorin-Oakenpants** [comment] 2019-08-22 05:40
> I will go back further

So I did some more tests. Each release: multiple tests, multiple sites, all sorts of persistent data (cookies, localStorage, IDB). Results for open tabs: what was cleared? note: I start every test with everything cleared & checked (physically have the storage folder open, and I check the sqlite databases). Tests sites were mainly garland and TZP, but I threw in some youtube (which sets IDB as well)

🔹 results

ESR60.8.0 - all data always cleared
FF60.0.2  - intermittently IDB doesn't clear (2 times in 10 tests)
FF61.0.2  - all data always cleared

so far, *probably* so good (looking at you 60.0.2, whats up with that?). now it gets whacky

FF62.0.3
 - test 1: LS=no , IDB=no
 - test 2: LS=no , IDB=yes
 - test 3: LS=partially cleared (fails to clear TZP, clears garland), IDB=yes
 - test 4: see 3
 - test 5+6+7+8: see 2

FF63.0.3
 - test 1+2: LS=partially cleared (fails to clear TZP, clears garland which had focus), IDB=yes
 - test 3: LS=no (TZP had focus), IDB=yes
 - test 4: after test 3, re-opened browser (no web content open), did ctrl-shft-del & failed to clear LS: closed browser and failed to clear LS. Managed to clear it by repeating this
 - and then I gave up

---

And at this point I stopped testing. I think from 62+ there is something fundamentally wrong with sanitizing (and this is only for sites that set a cookie: what about sites that don't, but do store LS or IDB: this has not been tested yet: saw a bugzilla about this in the last 6 months I think).

I don't know if it's a timing issue. One of the times YT's IDB wasn't removed, YT was still loading - but a repeat test of that, and it was. Maybe sometimes the IDB is locked or immutable or whatever? It seems IDB is usually sanitized and the bulk of the problems are with LS.

LS seems whacky as well: a lot of the time I got a partial clearance: where it removed one site but not the other. The one that seemed to always be kept in these instances, was TZP. Probably can't read too much into that.

I'm not sure what to do here, or how to explain this to someone at Mozilla. Given previous tests, maybe 70 fixed LS but there is still an issue with IDB intermittently not being cleared (and it can clear one host but not another: yup, seen partial sanitizing here as well)

**Comment by Thorin-Oakenpants** [comment] 2019-08-22 16:30
@earthlng can you reproduce? I'm a bit knackered right now. I'll try tomorrow to test more with no open tabs. The `openWindows` prefs are probably a red herring in my opinion: I think they only pertain to session restore data.

I won't present anything to baku or johann until I get all my testing data in order and can actually confirm there's an issue here.

**Comment by earthlng** [comment] 2019-08-23 12:25
I'm not going to try to reproduce all that. I've tested 68, 69b14 and nightly and the results are still the same as I posted above; 68 is broken, 69b14 + nightly are fine for me.
I've quickly tested IDB with TZP in 69b14 and the storage/default folder was empty after I closed FF

**Comment by Thorin-Oakenpants** [comment] 2019-08-23 12:56
You only need to reproduce in one release: e.g 68, that LS and IDB intermittently fail or partially fail to get cleared. In 62 and 63 it was over half the time. I stopped at that point because the same issue seems to persist all the way to 68 and probably 69. And even 70 didn't clear IDB on my first test.

Anyway, thanks for the help

**Comment by Thorin-Oakenpants** [comment] 2019-08-23 12:58
^^ it probably helps that I can run these tests super quick with dual monitors, portable FF versions and nillas set up, multi tabs explorer windows, bookmarked sqlite entry entries in my sqlite db viewer etc

**Comment by Thorin-Oakenpants** [comment] 2019-08-24 22:43
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1334945

My nilla's were all set up to sanitizeOnShutdown (`2802`) with everything in the UI ticked, and for cpd (manual): i.e. UI options available in `2803` and `2804`. There's nothing to sanitize btw, and I didn't load any web pages.

🔹 TEST1: privacy.clearOnShutdown.openWindows was set to true as well
Windows:
- ESR60, FF60-66
   - the first window opens and then gets replaced by a second window (i.e the first window is closed)
- FF67-70: the problem is fixed

🔹 TEST2: privacy.cpd.openWindows was set to true (and privacy.clearOnShutdown.openWindows was reset)
Windows:
- ESR60, FF60-70: when running Ctrl-Shift-Del = opens a second window

**Comment by Thorin-Oakenpants** [comment] 2019-08-28 12:54
https://ghacksuserjs.github.io/TorZillaPrint/sanitizing.html

So this makes it easier to test: but it's not definitive: I think timing has something to do with it. I'm opening, testing, and closing my browser pretty quickly. In the code there's stuff about doing a cleanup on startup (if shutdown cleanup didn't finish? or idb was inaccessible? a bit over my head) -> this is what the dual windows was on start - something like that. The ticket that most fixed the dual windows on start in 67 -> [1554167 see comment 26](https://bugzilla.mozilla.org/show_bug.cgi?id=1554167#c26). Anyway, `cpd` is a red herring. They're not needed to clear the data (if it works as it's meant to)

So in my previous tests, I was flicking open two or three sites: and sometimes I got all possible variations of what data was cleared or not between localStorage and IDB, including partialy (some from one site but not the other). Cookies were never a problem

So I've done some MOAR testing now I just flicked the test page up. I don;t seem to have any issues with IDB (or cookies, never did with cookies). But localStorage fails consistently, like almost every time, in FF62, 67, 68 **and 69**. It all seems fixed in F70.

Here's dev FF69
![sanitize](https://user-images.githubusercontent.com/16656956/63857217-d5bf4100-c992-11e9-8727-25bf5939a0dc.png)

This is only for shutting down. I don;t seem to have any issues with manually clearing.

**Comment by Thorin-Oakenpants** [comment] 2019-08-31 14:21
Hah ... so it's `dom.storage.next_gen` which is false in 69 and true in 70

**Comment by Thorin-Oakenpants** [comment] 2019-08-31 16:21
IDK anymore: I give up: Here's Nightly 70 with NG enabled
![i-give-up](https://user-images.githubusercontent.com/16656956/64066556-d82bd000-cc0a-11e9-82b5-61ed79b498e8.png)

I only wanted to say something I noticed several days ago: that deleting "Offline Website Data" also clears "Cookies" regardless if the cookies checkbox is ticked or not: but now I don't know if that's because of NG or not. I opened Nightly to get look at something and noticed it hadn't cleared localStorage.

**Comment by Thorin-Oakenpants** [comment] 2019-08-31 16:40
^^ And now I can't replicate that in Nightly 70

**Closed** 2019-09-01 14:49 UTC
