### ISSUE TITLE
where's the dummies version?

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#607] opened 2018-12-22 19:39 UTC
i'm working on a 'for dummies' version of my [FF guide](https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs) - i know there's been discussion here about a 'lite' version of the user.js - anybody done anything with that?

if not, i'm gonna get started

**Comment by Thorin-Oakenpants** [comment] 2018-12-22 21:05
> anybody done anything with that

Of course not.

---

up to, and including, section 4600 (RFP alts) there are 428 prefs (excl. parrots) - 96 are inactive. Leaving 332. Of these 24 are noted as enforcing default (and there are some others, let's say at least 8 more). That leaves 300 prefs we're *changing* on people (as a really rough estimate)

https://github.com/ghacksuserjs/ghacks-user.js/issues/605 shows us what people are changing (albeit a very small group of users), what causes web breakage, what alters chrome behavior, what impacts performance, backed up by our knowledge (e.g troubleshooter info, existing tags). The list is pretty comprehensive and there are about 70 items (the green active lot, IDK how many prefs exactly that would be, maybe 90) that if removed from the user.js would provide a dummies version that probably breaks absolutely nothing. There are already 38 `[SETUP` tags in the js, so it's over halfway there.

That 70 items can be trimmed down, I'm partway thru a local copy of splitting it up into ignore, already tagged, and todo. I'm already on my way to making a "relaxed" (and "hardened") overrides list for further review.

I think you'd be duplicating work in this issue re a "lite"/"relaxed" version. Where I'm at now is refining the items for "newbies" to ignore (so all videos work, so copy/paste of FB works, so the urlbar works, so best practice happens (eg auto-update), etc), and then it's a case of
- making sure that info is the user.js with `[SETUP*` tags (we already have 38 of them)
  * then the user.js itself has a built in relaxed/hardened mode (everything in one offline file)
  * not 100% sure on hardened tags, probably not, and it's only about 10 items IMO
  * painfully aware that I do not wish to overwhelm the js with setup tags
  * painfully aware that e.g. 60 setup tags is not ultra user friendly for babies
- probably provide a "relaxed" sticky with a js overrides for all those setup tags, with some info, broken into perf, web, chrome
   * this would be the easy-as-fuck for newbie baby dummies bit :)
   * painfully aware that this would then be another thing for us to maintain
- with the amount of changes we do here, I do not wish to maintain multiple branches

Need zzzzzz :kiss:

**Comment by Thorin-Oakenpants** [comment] 2018-12-22 22:43
We've already discussed all of this to death in some old topic, which lead to a request for overrides, which lead to the aforementioned issue I opened several days ago.

First we need to actually create a list and see how big it is. Then we had split views on building it into the user.js (either tags, or a separate overrides section at the end - see we already discussed this!! :trollface: ) or provide a relaxed-overrides.js file, or create a sticky, or some combination of all of these.

I'm quite against adding a relaxed overrides one-switch char section - it undermines/duplicates the purpose of the setup tags which is actually a very awesome thing overdodactyls's real time project can leverage, and it takes away the onus on the end user to do some reading and put some thought into it. I get it, you want a `complete and utter noob` aspect, but that doesn't exactly fit given how complex the whole thing is. The only way I see this aspect, is a relaxed sticky to save any babies having to F3 thru the setup tags

**Comment by bogachenko** [comment] 2018-12-22 22:55
noobs are unlikely to think about privacy.

my parents only need to quickly download, and to understand what and how they will not work.
I directly see as people who are far from privacy sit and open domains in umatrix or there configure firefox in about: config
so

**Comment by Thorin-Oakenpants** [comment] 2018-12-24 14:39
> noobs are unlikely to think about privacy.

If someone takes the time and trouble to find this repo, then are already concerned about privacy. And lets give people some credit - they're not computer illiterate. Just because it's new to them, doesn't mean we should exclude them. At one time, this was all new to me as well.

It also doesn't get much easier than locating your profile, making a backup, and using a text based file. The problem is the information is overwhelming - and that goes for *everyone*. Unless you're constantly living inside the Firefox world of code, changes, web tech, etc - it's just too much to take in. And even then, it's still **too much**.

---

I will add this though, before I close this issue (because I already have an issue open), is that doing something "half assed" can be misleading - and by that I mean, when we create a overrides sticky (or whatever) that undoes a bunch of settings, then the end user needs to made **super aware** that they are trading privacy etc for compat, and can undo a lot of the other hard work => a false sense of privacy.
 
Lets say a user disables FPI because it screws up some cross domain logins they just gotta have. To them it's probably just one pref, but the ramifications of not using FPI are huge. So many aspects and prefs don't work in isolation, and there are many ways to skin a cat (sorry :cat2: , it's just a [saying](https://en.wiktionary.org/wiki/there's_more_than_one_way_to_skin_a_cat)).

All I'm saying is that privacy IMO does not have really have a slider. Either you lock it down and be private, or the whole lot is compromised (it's a bit more complex than that)

/end of rambling. Time to catch Satan nicking my cookies

**Closed by Thorin-Oakenpants** 2018-12-24 14:39 UTC
