### ISSUE TITLE
Container Tab Settings won't enable

### ISSUE THREAD

**Issue by AnneKeck** [ghacksuserjs/ghacks-user.js#882] opened 2020-01-15 18:23 UTC
Using only the three suggested preferences 1701-1704 the Container Tab Settings won't enable, but if I use the user.js as given it works. What preference(s) am I missing?

**Comment by Thorin-Oakenpants** [comment] 2020-01-15 21:39
Are you in Private Browsing mode? Containers don't work in PB Windows

**Comment by crssi** [comment] 2020-01-16 20:58
I cannot reproduce here.
What about closing Firefox and deleting everything inside `%appdata%\Mozilla` folder... and start FF, then try those prefs 1701-1704 again.

NOTE: this will delete your profile... if you need it, make a backup before deletion.

**Comment by AnneKeck** [comment] 2020-01-17 14:30
Yes, that work! Thank you for your help.
I'm sorry to bother you. I just have one question left and figured you guys might know. What are the privacy threats caused by the address bar? I don't quit get why I should disable autocomplete and suggestions. I tried to find more information about this on the internet, but was left quit unsatisfied.

**Comment by Thorin-Oakenpants** [comment] 2020-01-17 22:20
Almost everything you need to know is in the 0800 section. Read it :)

---

Because the address bar doubles as a search bar, you don't always want to leak things you type in there to search engines in two ways
- `0801` : if you did a typo: e.g you typed `secret place.com` (it's not meant to have the space, but you bumped your space bar) - and you hit enter .. instead of going to your website, you would instead be asking your default search engine to search for it
- `0807` : real time search suggestions: and I don't know if this is the case anymore. It used to be that as you typed, suggestions would start to be suggested from your default search engine - the implications of this are vague
   - because you probably intend to search anyway, it's no big deal - but what if you starting to type `how to kill myself` but then decided not to search: too late, the search engine already knows. Now you might be profiled as suicidal
   - what if the search you typed was meant to be used by a different search engine
   - what if you're typing an address: `secretplace.com` not meant to be searched

The real-time search suggestions are only a problem if they still exist: **I don't know** if this depends on the search engine since I don't use it at all. If you use a trusted default search engine (e.g one that doesn't keep records etc) and/or it doesn't do suggestions, and/or you're behind a VPN, then you can mitigate most/all of it

---

There's a few more: such as speculative connections (`0810`) and domain guessing (`0802`)

**Comment by Thorin-Oakenpants** [comment] 2020-01-19 03:50
closing .. feel free to keep asking questions

**Closed by Thorin-Oakenpants** 2020-01-19 03:50 UTC
