### ISSUE TITLE
Uploaded images are white

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#921] opened 2020-04-06 13:24 UTC
Whenever I try and upload an image to a site, the image displayed is just white. Sometimes I'll get a site specific error along the lines of "unable to upload image" etc and the image wont upload at all.

On some sites uploading images works as expected but I don't know why. I tried running the scratchpad script but it couldn't narrow it down (on one of the checks the site stopped working altogether, so I couldn't see if the problem was still there).

Ran a fresh FF profile without ghacks, problem was gone. Ran with ghacks, same problem occurred.

**Comment by atomGit** [comment] 2020-04-06 13:32
there's info in the wiki about this, but i do it a little differently - still, it can be a bit of a tedious process of elimination...

[Troubleshooting Firefox preferences](https://12bytes.org/articles/tech/firefox/firefox-tweaks-and-fixes-and-things#Troubleshooting_Firefox_preferences)

**Comment by Thorin-Oakenpants** [comment] 2020-04-06 13:46
> Before you proceed...
>   - Issues will be closed as invalid if you do not [troubleshoot](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting), including
>      - confirming the problem is caused by the `user.js`
>      - searching the `[Setup` tags in the `user.js`

The cause might be different depending on the site. Without STR (steps to reproduce) I can't even try and pinpoint the pref. Also, you didn't fully troubleshoot very far. Have you tried flipping some of the setup-web prefs?

By my own rules, I'm closing as invalid, sorry. But if anyone else wants to help, go ahead.

**Comment by Thorin-Oakenpants** [comment] 2020-04-06 13:46
PS: white images => sounds like canvas => sounds like RFP

**Closed by Thorin-Oakenpants** 2020-04-06 13:46 UTC

**Comment by Thorin-Oakenpants** [comment] 2020-04-16 06:31
FYI: Here's something similar: [reddit: Posts to instagram are only white blank images](https://old.reddit.com/r/firefox/comments/g1xerq/posts_to_instagram_are_only_white_blank_images/)

> fixed by noticing the popup about html5 canvas fingerprinting and allowing that
