### ISSUE TITLE
[FYI, 1551592]: RFP causes blur in pdf.js

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/ghacks-user.js#725] opened 2019-05-14 15:34 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1551592

**Comment by ArchangeGabriel** [comment] 2019-05-14 15:39
Not new, duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1428331.

**Comment by KOLANICH** [comment] 2019-05-14 15:49
Thank you for the info. IMHO not quite a duplicate - it is easier to solve this issue for pdf.js only (I mean browser component, not a library) than to every website.

**Comment by Thorin-Oakenpants** [comment] 2019-05-14 15:51
don't forget
- https://bugzilla.mozilla.org/show_bug.cgi?id=1533787
- https://bugzilla.mozilla.org/show_bug.cgi?id=1532859

**Closed by Thorin-Oakenpants** 2019-05-14 15:51 UTC

**Comment by Thorin-Oakenpants** [comment] 2019-05-14 15:53
its a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1537955
