### ISSUE TITLE
privacy.resistFingerprinting causes odd signon.autofillForms suggestion position

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#29] opened 2017-02-23 00:32 UTC
when log-on autocomplete is off, you can click in the user name input to reveal a menu with the user names that are stored for that site - click on the name and the password is filled in

with this user.js, when i click on the name field the menu is usually above the input instead of below it (it's never below it) and sometimes it's way off to left - kind of funny actually

been buggin' me for a while, but this is another pref i haven't yet isolated

**Comment by Atavic** [comment] 2017-02-23 01:36
What's this site? Wordpress again?

**Comment by atomGit** [comment] 2017-02-23 01:51
any site that i've tried so far where you can log-on, but yes, WordPress is one - Ting is another: https://ting.com/account/login - when i click in the email input, the menu appears off to the left - same with ProtonMail - https://mail.protonmail.com/login

wherever the menu appears for a given site seems to be where it will always appear for that site

**Comment by Atavic** [comment] 2017-02-23 02:06
`user_pref("signon.autofillForms", false);`

because
```
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
```
clear cookies, close browser, tr again.

**Comment by Roman-Nopantski** [comment] 2017-02-23 04:36
This behavior started with this FF51, and I haven't had time to track it down properly.  @Atavic - that's solves the UI issue, but removes the security aspect of having the pref in the first place. I've been using `signon.autofillForms` for a long time - it only just got the quirk, and I think the real answer may be a bug, or some other setting.

To those who don't follow. (You have a saved login, password for site X)

- signon.autofillForms -> true
I go to site X, and the fields Login and Password and auto-filled in
-  signon.autofillForms -> false (old behavior)
I go to site X and the fields Login and Password remain empty. As soon as I start to start my Login name, a dropdown appears with showing my saved login name, and when I click it, both fields are filled in
-  signon.autofillForms -> false (new behavior)
Same as the old behavior, but now the dropdown suggestion is always (for me) approx 250pixels up and 250 pixels to the left

**Comment by earthlng** [comment] 2017-02-23 10:07
Try `privacy.resistFingerprinting;false`

**Comment by atomGit** [comment] 2017-02-23 11:36
and we have a winner - that's it @earthlng - `privacy.resistFingerprinting;false` is causing the problem, perhaps indirectly

not sure i should close the ticket so i'll let that up to someone else

**Comment by earthlng** [comment] 2017-02-23 11:47
yeeeeah, what did I win? please tell me it's 100 virgins in the afterlife! or 200??
I think I deserve 200, at least xD

**Comment by earthlng** [comment] 2017-02-23 11:57
https://github.com/ghacksuserjs/ghacks-user.js/issues/7
for future reference in that meta-ticket, makes it easy to find this again. Let's see if this works....

**Comment by earthlng** [comment] 2017-02-23 12:04
Is this a fitting title?

**Comment by Roman-Nopantski** [comment] 2017-02-23 12:17
@fmarier Could you please file a ticket for Arthur Edelstein [:arthuredelstein] 

privacy.resistFingerprinting causes odd signon.autofillForms suggestion position.

To reproduce:
- Have a saved password for a site
- privacy.resistFingerprinting -> true
- go to the site and logout, then go to the login page
- click/type in the account field
- behavior: the stored login is displayed out of position
- expected behavior, it should be in line with and underneath the account field

Attached image:
![autofillforms](https://cloud.githubusercontent.com/assets/16656956/23258594/cc374cf4-fa2d-11e6-9365-7a638866c7d6.png)

**Comment by Roman-Nopantski** [comment] 2017-02-23 12:21
Well done guys (and ladies!!) :1st_place_medal:

**Comment by earthlng** [comment] 2017-02-23 12:22
I don't think we should bother our resident Security Expert with those kinds of things.
I'm sure he has better things to do than to file a ticket for us just because we are too lazy.

**Comment by Roman-Nopantski** [comment] 2017-02-23 12:25
@earthlng @fmarier Well I'm not doing it, and I want it to be worded and tagged right so it get Arthur's attention. Whoever files it, feel free to use the image. Francois has some downtime :) Either he does or he doesn't. It's not like we will be finding bugs very often, this may be the only one.

**Comment by atomGit** [comment] 2017-02-23 13:21
just a note that apparently this may affect all inputs for which suggestions are available, such as a search input for a web page

**Comment by fmarier** [comment] 2017-02-23 21:57
Did you test it on Firefox 52?

It sounds very similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1320801.

**Comment by Atavic** [comment] 2017-02-23 22:18
Maybe ResistFingerprinting blocks the input field to be populated?
`user_pref("privacy.clearOnShutdown.sessions", false); // active logins`
`user_pref("privacy.clearOnShutdown.siteSettings", false);`

**Comment by Roman-Nopantski** [comment] 2017-02-24 18:48
I don't have a portable FF52, but I did test it on a FF53a2, and the problem does not exist there. That bugzilla 1320801 we knew about back at ghacks and Aintar's info is making me look a little deeper. He found it was a combination of `privacy.resistFingerprinting` and e10s, and his issue sounds slightly different. This may also explain that issue with checkboxes (i.e co-ordinates). He was talking about back these back in July 2016 ( http://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings/#comment-3934501 ). I've only seen this (i.e our issue, not Ainatar's) since FF51. I'm also not e10s, the portable 53a2 Dev is, but I can flip it, so I'll have to test some more.

**Comment by earthlng** [comment] 2017-02-24 19:03
It's only a annoyance anyway, nothing breaks; we identified the pref causing it, referenced this issue in the meta-ticket and mozilla already fixed the problem for a future release. Let's close this issue.

@fmarier, thanks for pointing us to that bugzilla

**Comment by Roman-Nopantski** [comment] 2017-03-07 17:00
confirmed fixed in 52 stable

**Closed by Roman-Nopantski** 2017-03-07 17:00 UTC
Labels: bug
