### ISSUE TITLE
[RESOLVED] v57: uBo settings affected by clearing Offline Website Data on close.

### ISSUE THREAD

**Issue by grauenwolfe** [ghacksuserjs/ghacks-user.js#273] opened 2017-11-18 01:07 UTC
## Issue Resolved by deleting and reinstalling v57. No idea what happened...

I have always had Offline Website Data checked (value = true) for both `privacy.cpd.offlineApps` & `privacy.clearOnShutdown.offlineApps`. Since v57 this causes uBo to lose it's settings just as it was doing before adding an exception in v56.

Additionally, I get this in Preferences. Notice the **Site Data** info. It permanently reads "Calculating" and the options are unavailable. 

![fu ff](https://user-images.githubusercontent.com/25858089/32975078-59ad4724-cbc9-11e7-80c5-6341d8486c09.png)

I do NOT want to start allowing a bunch of BS to get stored in order for extensions to work like they have all the years before.

Anyone else getting this? I imagine we all have relatively similar settings.

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 04:34
Terms
- local storage = storage.sqlite and/or extensions using storage api where I think they store this stuff elsewhere in extension folders eg "browser-extension-data" dire (this is not IDB)
- IDB = OWD = not local storage in my words below
- I am treating these two items separately

---
- I'm still on **FF56** and clearing OWD on close or manually doesn't affect uMatrix or uBo's IDB
- We better do a user.js patch and turn these two prefs to inactive with a note (FYI see  [1416219](https://bugzilla.mozilla.org/show_bug.cgi?id=1416219) )
- @grauenwolfe - We need to clarify this
  - so this removes the IDB entries? or just the localStorage?
  - if you clear OWD and NOT cookies what happens to `profile/storage/default/moz-extension+++UUID` dirs and `profile/browser-extension-data/Ext-ID` dir contents (this is not the UUID, eg see `uBlock0@raymondhill.net` folder)
      * my `uBlock0@raymondhill.net` storage is 45.5kb
  - same dirs to watch, but this time also clear cookies

Comment 5 suggests that "localStorage" will be cleared, and I assume this means the `profile/browser-extension-data/Ext-ID` folder

Note: I haven't got a 57, but I am intrigued as to whether or not this requires clearing cookies (which I don't as per the user.js) - because I thought clearing cookies cleared the localStorage

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 04:49
The prefs UI changes / section - in FF56->57 diffs we are looking at the storage thing

```js
pref("browser.storageManager.enabled", true); // prev: false 2706 1399398
pref("dom.storageManager.enabled", true); // prev: false 2706
```

We currently have them in 56 and lower as disabled. In 57+ we will make them inactive. Suggest you do the same and reset them in about:config. For starters it then shows some extra settings in the prefs UI. I am not entirely sure exactly which new UI stuff is added.

I am not worried about the actual storage (we control that via numerous other means), and I am almost certain that the new Storage API is used a lot and being disabled might have side-effects.

PS: I am almost out of time and will be gone for the next week, back on the 26th

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 05:14
see - https://github.com/ghacksuserjs/ghacks-user.js/commit/7ae034a23c7d1cfd2edcd7f5bfcdab7a08d3fcf7

I too (in FF56) get a non-stop "calculating" and the settings and clear all data buttons are disabled. We will have to figure out what is stopping that - might be something to do with `browser.cache.offline.enable` (1004)

---
Side Note: from the other bit in your pic, AFAIK (cannot find tickets in a hurry) - the cached web content **quota** is broken and has been years regards limiting amount and asking for permission (i.e i think it was limited to 5mb per domain and it had to ask for more = broken). I do not know anymore where this data is - maybe it refers to OWD

something I think to do with 2450a+b
- offline-apps.allow_by_default
 - browser.offline-apps.notify

These two prefs should probably be tied move from the 2400s and moved to the new storage section or to cache section - IDK

**Comment by grauenwolfe** [comment] 2017-11-18 07:25
Made a new profile from scratch, not one thing was imported, and have gone through implementing the changes I have always had, item by item. Still a problem on new profile. 

It seems that data from extensions is treated no differently than offline website data. Either Prefences>Cached Web Content -or- Offline Website Data on close is clearing extension data, uBo at least. Adding exceptions makes no difference anymore. Maybe something unique to only uBo? Universal? Shit.

---

> if you clear OWD and NOT cookies what happens to profile/storage/default/moz-extension+++UUID dirs and profile/browser-extension-data/Ext-ID dir contents (this is not the UUID, eg see uBlock0@raymondhill.net folder)...

Not clearing cookies at all, Cookies + Site Preferences are left unchecked, not cleared. Interesting to note that **profile/browser-extension-data/uBlock0@raymondhill.net/storage.js** has a creation time of a few minutes ago, 13:05. While New Tab Override's storage.js file shows creation at 8:09, when I created a new profile.

---

> pref("browser.storageManager.enabled", true);
> pref("dom.storageManager.enabled", true);

These are both enabled so we can rule that out.

---

> might be something to do with browser.cache.offline.enable

This is my hunch as well. About to try more things out. What a f'ing mess, again. I genuinely may just go back to v56. Three days of using v57 and nothing is better or faster, only slightly more broken and glitchy, to be expected though I guess.

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 07:37
^^ Yeah, I will not move to 57 until I am ready. I can of course do a FF57 portable using my current profile as a secondary - but only when I get back. First I want NoScript and probably several weeks of that in the wild for serious bugs to be fixed.

Meanwhile, this extension data getting wiped is a problem - not moving until I know how to stop it, and the ramifications of any changes to stop it.

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 07:41
@grauenwolfe - see https://github.com/ghacksuserjs/ghacks-user.js/issues/254#issuecomment-345425166 and previous comment by earthlng

enforce the two storage prefs in 2706 to false and test again

**Comment by grauenwolfe** [comment] 2017-11-18 20:54
I'm 99.9% sure this is caused by clearing Offline Website Data. What I'm not at all sure of is if it's an issue only with uBo or if it is universal. 

Below configuration solves the issue. Bad solution.

`privacy.clearOnShutdown.offlineApps` = false
`privacy.cpd.offlineApps` = false

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 21:10
^^ didn't we already confirm that (it also says it in that bugzilla ticket)

My Q was
- if you make the two storage api prefs in 2706 false does it still happen
- also, I am still no closer to knowing if it removes extension local storage and/or IDB storage

I haven't had time to test myself yet and am about to head out the door

**Comment by claustromaniac** [comment] 2017-11-18 21:10
I have both privacy.clearOnShutdown.offlineApps and privacy.cpd.offlineApps set to true and I'm not experiencing this on FF 57 stable. :confused:

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 21:11
@claustromaniac - so I assume you have the 2706 prefs enforced and active at false

**Comment by claustromaniac** [comment] 2017-11-18 21:14
@Thorin-Oakenpants Yup. It must be that.

**Comment by grauenwolfe** [comment] 2017-11-18 21:55
> My Q was

    if you make the two storage api prefs in 2706 false does it still happen
    also, I am still no closer to knowing if it removes extension local storage and/or IDB storage

Shit man, I'm sorry, you're talking about:

`dom.storageManager.enabled` + `browser.storageManager.enabled`

OK, they were set to true. Switched them to false so we'll see what happens.

PS - If you're still talking about different entries than this then just tell me specifically. :)

Have fun wherever you're headed to.

**Comment by earthlng** [comment] 2017-11-19 09:04
I've tested a fresh new profile with only my user.js and a new install of the latest uBO and clearing offlineApps on shutdown (or manually) doesn't remove my uBlock config in 57 stable. IDK what to tell you, must be something on your end. Am still trying to figure out the "Calculating" part.

**Comment by earthlng** [comment] 2017-11-19 11:03
Ok, so ... the "Calculating" part is because of `browser.cache.offline.enable=false`.
Changing it to true creates a new folder OfflineCache which can also be seen under about:cache -> appcache -> location: profile\OfflineCache. Keeping it on `true` and setting `browser.cache.offline.capacity = 0` changes that "location" to "none, only stored in memory" in about:cache for appcache. However then the Site Data UI thingy also doesn't work, `.capacity` needs to be at least =1. 

from nightly's [sanitize.js](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/sanitize.js#289):

offlineApps now clears:
* AppCache - which seems to be what's stored under profile/OfflineCache
-> I've tested the [IDB testpage](https://static.raymondcamden.com/demos/2014/feb/7/index.html#/home) and about:cache still said "storage in use: 0 KiB" - IDK which API is used for this AppCache stuff

* LocalStorage - (or DOM Storage as Pants likes to call it) which I think is what's stored in webappstore.sqlite
-> API: window.localStorage (sometimes also used in Webextensions)

* ServiceWorkers

* QuotaManager stuff - which is IDB and presumabely other stuff stored in profile/storage/...

When I tested the [IDB testpage](https://static.raymondcamden.com/demos/2014/feb/7/index.html#/home) the Site Date Preferences UI now reads
"Your stored site data is currently using 48.0 KB of disk space" and the domain is listed under "Settings..."

"Clear All Data" deletes it, as expected, HOWEVER manually clearing "Offline Website Data" does not remove it!?! WTF?!

console shows:
```
Error sanitizing offlineApps Exception { name: "NS_ERROR_ILLEGAL_VALUE", message: "Component returned failure code: 0x…", result: 2147942487, filename: "chrome://browser/content/sanitize.js", lineNumber: 336, columnNumber: 0, data: null, stack: "clear/</</<@chrome://browser/conten…", location: XPCWrappedNative_NoHelper }  sanitize.js:152
Error: Error sanitizing  sanitize.js:184:13
```

At least Quantum is fast, right? LOL :facepalm:

Also didn't clear it on shutdown - good stuff

**Comment by earthlng** [comment] 2017-11-19 12:15
I suggest we do the following changes for 57:
```js
user_pref("browser.cache.offline.capacity", 1);
user_pref("browser.cache.offline.enable", true);
user_pref("browser.storageManager.enabled", true);
user_pref("dom.storageManager.enabled", true);
user_pref("privacy.firstparty.isolate", false);
```
Then the new Site Data UI works and offlineApps (Offline Website Data) clearing on shutdown or manually works correctly. A bit sad to disable FPI but IDK what else to do. What do you guys think?

**Comment by grauenwolfe** [comment] 2017-11-19 20:33
_PREFACE:_
As a matter of respect and efficiency I try my best to convey only relevant info, in as few words as possible. None of it is extraneous so please be sure to read and consider every word. I only say this because (a) it's a long post and (b) I'm guilty of first jumping to bullet points, screen shots, etc.

Now, on with the show...

---

I spent all night trying to isolate this. I toggled more settings in one night than anyone ever should but in the end the **only single thing that mattered was clearing OWD**. Either via History>Clear Recent History or via clear on close, it didn't matter. I toggled these one off one on, back and forth, etc. and just as you may expect they had the same effect individually or paired. When both clear OWD settings are off, everything is fine. No progress there - only confirmed what I already knew. 

## Issue 1


Setting `browser.preferences.offlineGroup.enabled` = true, adds this to the Privacy & Security UI:

![offlinegoup](https://user-images.githubusercontent.com/25858089/32994021-ee7aef7e-cd26-11e7-88b8-94d7700eeb2a.png)

It shows _"using 0 bytes of disk space"_. So I changed some extension settings, visited a few sites, and refreshed the Privacy page to see if it changed. It didn't, still _"0 bytes"_. Yet when I clicked the "Clear Now" button, uBo settings are wiped clean - even though it says there's nothing there to clear.

## Issue 2


Within Privacy & Security UI, three seperate references for storage show the following:
* Cached Web Content = 0 bytes
* Site Data = 0 bytes
* Offline Web Content and User Data = 0 bytes

However, at the very same time:

![ubopermissions](https://user-images.githubusercontent.com/25858089/32994077-ecfe6030-cd27-11e7-9160-a2ac58cace17.png)

You can clearly see Offline Storage is 30.9 MB. Add to this that clicking either the "Clear Now" (via Offline Website Content UI) or the "Clear Storage" (via Permissions Manager UI) buttons had the same effect on the same data even though they show inconsistant values. 

Can I also just say that I have never been asked to allow a site storage permission. Not one time.

----

Quickie reminder points:
* This issue started with v57 on a profile which I have used trouble free since v53 or 54.
* Issue persists on new profile from scratch without importing a single item from the previous profile to eliminate chance of corruption.

**Comment by grauenwolfe** [comment] 2017-11-19 20:56
@earthlng I read your posts, not dismissing them, I just had a post ready to go.

Aside from my minor problem, it seeming like there's still some funky issues with storage overall. I read through some bugzilla tickets regarding storage last night and it quickly become apparent that sometimes the devs themselves are unsure about data storage - what gets stored, where, or what gets cleared and by what means.

I'll get back on this later today and of course post any progress made.

**Comment by earthlng** [comment] 2017-11-19 21:28
First of all LOL at the preface xD It wasn't *that* long of a post. Maybe for today's youth it is because they won't read a tweet if it's longer than 1 sentence but that's another problem entirely ;)
2ndly just forget about `browser.preferences.offlineGroup.enabled`! That's old and probably won't work correctly anymore or could even interfere with the new "Site Data" UI. Reset it to false and see if that changes anything. 3rdly I also didn't have to change any permissions for uBlock and I can clear cookies, OWD, and everything else for that matter and it still retains uBlock's config.
Regarding the "0 bytes" throughout that's the same here. I think storage used for extensions is not included in "Site Data"'s counter.
I assume you're using the latest version of uBlock? Have you tried making a couple screenshots of the settings and copying the filters and rules and completely remove and reinstall the latest version and then re-configure it?
@claustromaniac couldn't reproduce your issue and neither could I, maybe it's a Mac problem IDK.

**Comment by grauenwolfe** [comment] 2017-11-20 01:58
@earthlng Before starting this post I implemented the recommended changes so after posting this I'll restart FF and see where it goes (which may end up making this post pointless then).

> claustromaniac couldn't reproduce your issue and neither could I, maybe it's a Mac problem IDK.

I understand that it's more than likely an issue for only me or maybe very few, but it's not been a problem before as I've cleared OWD for as far back as I can remember. Certain settings are sort of second nature for me at this point. It started immediately after updating to v57. From some tickets I read last night and this one[ 1416219](https://bugzilla.mozilla.org/show_bug.cgi?id=1416219) referenced by Pants, I know it's at least real even if contained.

> I assume you're using the latest version of uBlock?

Using v1.14.18 - latest as far as I know.

> Have you tried [...] completely remove and reinstall the latest version and then re-configure it?

Yes. I tried a number of things before posting and this was the second thing I did, actually. It didn't help so the next step was creating a new profile. It also didn't help.

> 3rdly I also didn't have to change any permissions for uBlock and I can clear cookies, OWD, and everything else for that matter and it still retains uBlock's config.

(Assuming this excludes permissions asked for on install) you haven't granted any permissions or added any exceptions? Would be nice if that was only necessary for v56.

Couple of quick questions for anyone:
1. Is your uBo data in profile/storage/default -or- profile/storage/permanent?
2. Did you update or clean install v57?
3. Do you have anything in your profile folder named webappsstore2

**Comment by claustromaniac** [comment] 2017-11-20 02:07
@grauenwolfe 

1. `profile/storage/default`.
2. I updated to v57, but I had previously clean-installed v56 if I remember correctly. It might be relevant.
3. No.

**Comment by earthlng** [comment] 2017-11-20 08:11
> (Assuming this excludes permissions asked for on install) you haven't granted any permissions or added any exceptions?

No, but I use `network.cookie.cookieBehavior;1` because I don't need any permanent cookies (and I clear them on shutdown). So perhaps you still need cookie-exceptions if you block them with that pref IDK.

1. same as @claustromaniac 
2. clean install (portableApps)
3. no profile folder with that name. webappsstore2 is the name of the database table in the file webappsstore.sqlite. That bugzilla is about problems with extensions that still use the window.localStorage API but I'm pretty sure uBlock doesn't use that anymore. The new storage API that WE's should use is browser.local.storage which creates the files in profile/browser-extension-data/extension-name/storage.js. uBlock also stores some of its data in IndexedDBs in the folder profile/storage/default/extension-UUID/...

**Comment by grauenwolfe** [comment] 2017-11-21 04:53
> 3. No. EDIT: Wait. Was that a typo? I do have webappsstore.sqlite, for whatever it's worth.

Not a typo, webappsstore2 is correct but @earthlng cleared this up. Just me grasping at straws.

---

> No, but I use network.cookie.cookieBehavior;1

Same here.

> 3. no profile folder with that name. webappsstore2 is the name of the database table in the file webappsstore.sqlite.

Ohhhh, ok. Got it.

---

## Unfixable for now
As a **final** test I tried this once more:

1. created new profile via command-line, set as default
2. launched Firefox with new profile
3. immediately to AMO and installed uBlock0
4. opened uBlock0 dashboard  and updated default lists
5. cleared History (default checkmarks) - settings remain
6. cleared History (default checkmarks + OWD) - settings gone

So it's time to call it on this issue.

Maybe something got off when updating? Don't know, could be a million things. Having an untouched, pristine profile still do it - it's beyond me. Maybe I'll just reinstall from scratch at some point. I'll deal with it but ultimately just wanted to understand the issue more than anything.

**Comment by 2glops** [comment] 2017-11-21 08:56
@grauenwolfe 
1. default/storage/default/
2. update from my old regular profile
3. webappsstore.sqlite, webappsstore.sqlite-shm, webappsstore.sqlite-wal

No issue wit uBO.

**Comment by Thorin-Oakenpants** [comment] 2017-11-24 03:37
from @grauenwolfe 's ridiculously excessively long post xD .. issue 2 .. site permissions for OWD are obsolete (the pic provided is showing permissions for moz-extension, but all the bugzillas are referring to domains, so maybe but I doubt it, moz-ext* is different, but highly unlikely) - they have been removed in 58, and for years the whole thing has been broken. If I get time I will dig up some tickets. They're littered around in this repo under all the IDB, storage, strategy issues we've got (closed and open). I think the oldest ticket is 8 years old. I was tracking around 20+ tickets on OWD (it gets really confusing! - I don't really want to track them down again).

Re "site" permissions on a moz-extension: personally I would expect it to clear if you asked, because you EXPLICITLY asked to clear it. That's a big diff to clearing OWD manually from recent history or on close - that should really only be web content, and AFAIK that has been fixed.

Just got back - sunburnt too. Am sporting a super-secksie bikini line now. Will take me a few days to catch up. I can't even remember what this issue was about.

PS: I already saw earthlng's comment moaning about being overworked and to wake him up when ESR52 is EOL .. xD

**Comment by Thorin-Oakenpants** [comment] 2017-11-24 03:38
> @claustromaniac couldn't reproduce your issue and neither could I, maybe it's a Mac problem IDK

and I couldn't repro either

**Comment by Thorin-Oakenpants** [comment] 2017-11-24 03:41
> window.localStorage API but I'm pretty sure uBlock doesn't use that anymore.

I think it does, as a fallback, when cookies are denied (and thus IDB is denied) ask @gorhill - he implemented this so settings are not lost for those in PB mode

**Comment by Thorin-Oakenpants** [comment] 2017-11-24 03:46
From the wee bit I have digested in the last half hour eg your unfixable for now test, this seems like a MAC problem BUT

1. created new profile via command-line, set as default
2. launched Firefox with new profile
    * so cookies are allowed by default
3. immediately to AMO and installed uBlock0
4. opened uBlock0 dashboard and updated default lists
   * add some filters (just make them up), change your default * settings in the dropdown
5. cleared History (default checkmarks) - settings remain
6. cleared History (default checkmarks + OWD) - settings gone
   * did ALL settings vanish - not just lists back at default

**Comment by grauenwolfe** [comment] 2017-11-24 09:15
> from @grauenwolfe 's ridiculously excessively long post xD .. 

And I tried so hard ... :)

> so cookies are allowed by default

Yes. That list is verbatim and literal. 1. Launched FF and 2. immediately went to AMO. No setting prefs or anthing else in-between the steps posted.

> did ALL settings vanish - not just lists back at default

Wednesday night I deleted FF thoroughly and installed v57. Fresh install is still doing it, sort of. My filters, rules, etc., are fine but it still won't keep uB0's dashboard settings. **This is minor although annoying.** For example, if I collapse a filter group it will stay collapsed indefinitely until OWD is cleared. So I'm still kind of left wondering what's going on. I would think if anything that _maybe_ clearing "Site Preferences" would be responsible, not OWD. Examples screen shots below.

---

Dashboard set like this:

![screenshot](https://user-images.githubusercontent.com/25858089/33202097-bee2995e-d0c0-11e7-9d44-2ee101e30630.png)

Reverts to this after OWD is cleared:

![screenshot 1](https://user-images.githubusercontent.com/25858089/33202121-d669546e-d0c0-11e7-9207-a5acdd9e40dc.png)

So, that's where it stands as of now. Just cosmetic really and I can completely live with this. Still annoys the piss out of me though since I can't figure out why.

**Comment by Thorin-Oakenpants** [comment] 2017-11-24 10:12
Just some more relevant tickets: https://bugzilla.mozilla.org/show_bug.cgi?id=832660 <-- about the site preferences and OWD and how it doesn't/didn't read data properly etc (see comment 0 and it's attachment pic). There are other tickets about prompts for saving data not working and limits being ignored. This has been closed since I was away in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1102808 which says **"This bug explicitly does not track cases where data clearing is overzealous"** so that's not going to help us since this is clearing some Ext data (? is anything actually being lost? I am still not sure on this becuase we talking at cross purposes sometimes - but only because the whole storage thing is complex and a mess right now what with FPI, OA, WE, etc).

**Comment by grauenwolfe** [comment] 2017-11-26 03:14
_PREFACE - PART II:_
This is mostly a rant. No, it's entiely a rant, actually. So incredibly frustrated with Firefox and although I know better than to email or post when angry, I'm doing it anyway.

---

Thorin, I agree with you entirely and I'm done.

Storage management is broken / implementated to poorly to be of any use. In a number of those tickets, the devs themselves are often confused by this monster they've created, what hope have I then? I've seen enough tickets, enough contradictions, and enough of Mozilla's amateur hour hackshow. I don't think answering your follow-up questions will matter since I don't think there's anything for us to figure out, it's broken. Think of Jack Skellington doing all of his tests and experiments trying to figure out Christmas...

I'll leave you with this:
To solidify my feeling that 'managing storage' in Firefox is a sham, I disabled every storage, cache, disk, capacity, you-name-it, option. Set them all to off, disable, 0 value, etc., and guess what, none of it mattered, not one damn bit. Defying belief, data was still stored and data was still there to be deleted. So, either there are dozens of hidden preferences or it really is just a facade and sham.

Even with me clearly saying "No Firefox, don't do this." Firefox just looked at me and said "What? You mean this?" as it continued to store and cache away.

A full week dedicated to this only to find that settings don't mean shit. Best guess: it's unfixable and probably because it has never _really_  been properly implemented to begin with.

**Comment by Thorin-Oakenpants** [comment] 2017-11-26 03:46
I think you need a hug brother :hugs: 

I am still on 56. I do not think persistent web data has gotten WORSE in 57 - I think it's manageable (but everyone has different mileage)

- Default deny cookies FFS and set site exceptions - this stops all that local storage & IDB crap
   - You may also need to allow exceptions for cookies in uMatrix depending on your default rules
   - Site exceptions should be session only as much as possible - there is no need to clear cookies on close unless you want to. Keep cookies for auto-logins = you're tracked on that site anyway
   - Do **NOT** use a cookie extension (well not yet) - they are f**ked when it comes to FPI
- Deny all workers as I know you do grauenwolfe because that too can set persistent data (dont ask me where, I have seen IDB entries but there must be more
- Kill that storage API (its still being debated in #281) - the two prefs in 2706 - the UI is useless
- Use FPI - it covers way more than just persistent data
- Until the FPI + IDB clearing issue is solved, just run a script to wipe all IDB folders in storage/default except the moz-extension ones
   - personally, my mileage with my massive 8 allowed cookies means I never get any

I currently have zero issues with controlling storage with my methodology. That said, some sites require all that shit to function - so good luck. Persevere brother. I shall drink a dozen beers tonight for you.

**Comment by gorhill** [comment] 2017-11-26 10:24
This is a long thread, I don't know if this was clear so I will just state it here:

> Reverts to this after OWD is cleared

These UI settings are saved uBO's `window.locaStorage`.
The filter lists' contents and their compiled versions are saved into `window.indexedDB`.
The rest goes into WebExtensions `brower.storage.local` (what is saved when backing up uBO settings).

**Comment by Thorin-Oakenpants** [comment] 2017-11-26 21:17
@gorhill 

- These UI settings are saved uBO's window.locaStorage.
   * `profile\browser-extension-data\uMatrix@raymondhill.net` :question: 
- The filter lists' contents and their compiled versions are saved into uBO's window.indexedDB.
   * `profile\storage\default\moz-extension-UUID` :white_check_mark: 
- The rest goes into WebExtensions browser.storage.local (what is saved when backing up uBO settings).
   * :question:

**Comment by earthlng** [comment] 2017-11-26 21:36
`profile\browser-extension-data\uMatrix@raymondhill.net` is browser.storage.local and window.localStorage is in webappsstore.sqlite

**Comment by Thorin-Oakenpants** [comment] 2017-11-26 21:56
Makes sense now that @grauenwolfe is having UI setting issues because its stored in webappstore.sqlite which is where website localStorage is also stashed. Just looked in mine. I see (besides 4 entries for websites) 58 entries for 3 specific moz-extension `scopes` - but the strings do not match up with UUID or Extension IDs (as seen in about:debugging). I can recognize one from the keys and values as being Stylus. I guess the other two must come from uM, uBo, ViolentMonkey?

**Comment by grauenwolfe** [comment] 2017-11-27 00:55
@gorhill Hey, the man himself.

> This is a long thread, I don't know if this was clear ...


It's pretty long so probably best to ask you this:

What about:config prefs need to be left alone or are "off-limits" for uBO to function perfectly as designed? Anything like dom.indexedDB, browser.cache.offline, dom.storage, any other storage, any particular caches or anything else along these lines that uBO must have acces to? Or does it get access to everything it needs through asking for permissions when installed?

Maybe this is just a temporary condition with v57, I don't know, but uBO is an incredibly important extension for me so if there's anything you suggest, it'll be done.

**Comment by Thorin-Oakenpants** [comment] 2017-11-27 01:06
^ you need to allow a cookie exception at minimum (for now) else WE have no access to storage
^ you need to allow IDB else WE cannot use it
^ pretty sure dom.storage would be needed (we've never disabled that in the js)

Everything else, AFAIK, would be just items that interfere/supplement eg referer settings, various ua prefs, tracking protection & safe browsing etc

**Comment by Thorin-Oakenpants** [comment] 2017-11-30 01:20
@grauenwolfe 

Can I confirm that on FF57Mac with latest uBo, that you are **NOT** losing any settings - that is, your lists are kept up to date (stored in IDB), and your changes to options in the dashboard are not lost, and that your personal filters and rules are not lost

In other words, the only thing you are experiencing is the dashboard collapsing/expanding the filter lists shenanigans?

**Comment by grauenwolfe** [comment] 2017-11-30 03:57
Yes, correct. Since deleting and fresh installing 57 from scratch, filter list display issue now only. It doesn't affect uBO's functionality, just a minor annoyance.

uBO is working great since reinstalling, conveyed in post [346779584](https://github.com/ghacksuserjs/ghacks-user.js/issues/273#issuecomment-346779584), maybe not clearly enough.

> Wednesday night I deleted FF thoroughly and installed v57. Fresh install is still doing it, sort of. My filters, rules, etc., are fine but it still won't keep uB0's dashboard settings. **This is minor although annoying.** For example...

Before that (installed update from 56) was a complete nightmare. Updating filter lists over and over, 3p scripts enforced/not enforced randomly, wierd stuff and probably something funky during the update process, not sure.

**Comment by Thorin-Oakenpants** [comment] 2017-11-30 04:10
sounds exciting :aren't-u-the-lucky-one: ... I am still on 56 here, hope I have no upgrade issues

I'll close this, but maybe you could post an issue on the uBo repo - @gorhill has anyone mentioned this - scroll up to the two pics [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/273#issuecomment-346779584)

**Comment by Thorin-Oakenpants** [comment] 2017-11-30 06:50
> I am still on 56 here, hope I have no upgrade issues

OK .. **now** I have zero legacy extensions and can upgrade .. might pull the trigger tomorrow, running outta time

**Comment by Thorin-Oakenpants** [comment] 2017-11-30 09:52
@grauenwolfe I updated to 57, I have no issues with my uBo UI on windows (and I do not lose any data)

Should we close this?

**Comment by earthlng** [comment] 2017-11-30 17:41
@grauenwolfe can you please update your original post with the solution (did you only have to re-install FF or also start a new profile?), and a note that this happened on a Mac. You can link to this comment https://github.com/ghacksuserjs/ghacks-user.js/issues/273#issuecomment-345508296 re: the "calculating part". And then please close this issue. Thanks

**Comment by grauenwolfe** [comment] 2017-12-01 02:02
@earthlng Sure, good idea.

**Closed** 2017-12-01 02:08 UTC

**Comment by Thorin-Oakenpants** [comment] 2017-12-03 00:58
@grauenwolfe - see `https://github.com/gorhill/uMatrix/issues/863#issuecomment-348732013` and feel free to elaborate after gorhill responds

**Comment by Thorin-Oakenpants** [comment] 2017-12-04 01:25
@grauenwolfe - did u see gorhill's reply?

> Of course, forcing a reload of the "3rd-party filters" pane was necessary

**Comment by grauenwolfe** [comment] 2018-01-07 07:10
@Thorin-Oakenpants Only just now, way late (notifications were off in my git profile...)

Am I correct in understanding that gorhill experienced exactly what I was dealing with? The UI resetting and 3P filters needing reloading?

Still resetting the UI but at least 3P filters are stable and retained.

**Comment by Thorin-Oakenpants** [comment] 2018-01-07 07:56
> Am I correct in understanding that gorhill experienced exactly what I was dealing with

No idea. The issue was about something else but seemed similar, so I asked on your behalf re the UI expand/collapse and gorhill replied. As long as your actual settings aren't wiped, don't worry about it

His quote of `forcing a reload of the "3rd-party filters" pane was necessary` is simply that you need to refresh the page (and IF your expand/collapse UI is stuck, on a refresh they will be reset). I've never bothered to clear data with the panel open - I think I missed that detail in it's entirety. Weird quirk maybe, simple fix - refresh the panel
