### ISSUE TITLE
discussion: section persistent [web] storage items

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#235] opened 2017-09-13 04:13 UTC
Just an idea: section all persistent storage items - just re-purpose the current 2700: COOKIES & DOM STORAGE section

I read a [long article](https://queue.acm.org/detail.cfm?id=3136953) yesterday and it re-enforced to me how we should look at things - in other words, instead of lumping stuff together under "conventional" or current rules, let's define the problem.

This would cover them under one umbrella <sup>1</sup> : a "solution" to a "problem" (did I miss anything?)
- Cookies
   * :x: Limited Control:
     * not accessible in PB mode
     * not accessible with FPI
     * no access to system cookies (eg GA for SB) - WONTFIX
- Local DOM Storage
   * :x: Little Control:
     * not accessible in PB mode?
     * Extensions (not legacy) - not accessible by host (yet) but coming
     * FPI may cause access permission problems for extensions
- IndexedDB (Offline Website Data)
   * :x: No or LIttle Control: 
     * 56+57 have various fixes plus new permissions UI coming
     * Extensions (not legacy) - not accessible by host (yet) but coming
     * FPI may cause access permission problems for extensions
     * settings to force sites to ask for permission are broken (also 50mb limit is ignored I think) - these are being looked at
- Storage API
   * No Idea: Lets just assume everything is broken!

This would also allow a section header with comments that make sense
- FPI effects
- PB Mode effects
- Container effects
- Overall strategies
- The killer extension <sup>2</sup>

Especially as the WE APIs are fixed/expanded: eg opening up access to FPI objects, IDB access. Some items are intertwined (eg cookies and local dom, something going on with IDB+FPI?/StorageAPI?) and we should consolidate. I also see something like C-AD becoming a killer recommended Extension to cover all these. It just makes sense to me

<sup>1</sup> To be clear, by persistent storage, I mean set by websites, not FF "internals" such as various histories, cache, CA's, session data etc. Keep it simple: items like workers using storage would stay under workers section

<sup>2</sup> ***It's not a question of if, but when*** - If not C-AD expanding in time, there will be others. Without looking up the tickets/names, there is one guy (Thomas Wisniewski) pushing a lot of change in these areas and even doing some of the tickets for Mozilla (pretty sure he's not a zilla employee) and he wants to create this killer extension to cover all the above as well as serviceWorkers, cacheStorage and applicationCache. He's currently landing a patch for by domain access to IDB.

**Comment by Atavic** [comment] 2017-09-14 16:20
**NOTE**: [C-AD](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) is Cookie AutoDelete (a webextension).

**Comment by Thorin-Oakenpants** [comment] 2017-09-18 07:04
Edited the first post: might add some zilla ticket links later. No wonder I have had cookies ( and thus local dom storage) default deny and IDB disabled for years. WHAT a mess!

**Comment by crssi** [comment] 2017-09-18 07:31
Those persistent cookie are typically stored in IndexedDB, which can be effectively cleaned by [Cookies Exterminator](https://addons.mozilla.org/en-US/firefox/addon/cookies-exterminator/) addon.
Note: Cookies Exterminator will work until FF 57+, after that we can hope mozilla will resolve the APIs, which [Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) or [CookiErazor](https://addons.mozilla.org/en-US/firefox/addon/cookierazor/) can use to deal with those.
In the past (before FF 55 or 54... can't remember now) SDC dealt perfectly with those, but is obsolete now.

**Comment by Thorin-Oakenpants** [comment] 2017-09-18 07:57
Lets not discuss legacy addons! Cut that sh*t out bro!. The issues with ESR are not present (FPI is not ready for ESR 52) or will not change (PB mode) or can already be handled (legacy addons work in ESR) etc. ESR is dead to me! :grin: Focus on ~~stable and~~ 57+, because that is where we are headed

**Comment by crssi** [comment] 2017-09-18 08:04
Sure... I have mention the working solution at this point for anyone interested (IMHO it is worth to mention) and elaborated further in the "Note" section of my response.

Now I will hide my head in the sand. ;)

**Comment by Thorin-Oakenpants** [comment] 2017-09-18 11:10
Some examples of persistent storage issues

- IDB? - [1400582](https://bugzilla.mozilla.org/show_bug.cgi?id=1400582) Deleting all history still leaves some traces 
- [1398303](https://bugzilla.mozilla.org/show_bug.cgi?id=1398303) Local Storage not cleared by Clear Recent History
- [1047098](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098) Clear Recent History' with 'Cache' or 'Offline Website Data' doesn't clear QuotaManager storage (indexedDB, asm.js cache)
- [527667](https://bugzilla.mozilla.org/show_bug.cgi?id=527667) DOM Storage (localStorage, sessionStorage) data is not cleared when "Clear Recent History" is used with Time range not "Everything"
- [1077986](https://bugzilla.mozilla.org/show_bug.cgi?id=1077986) offline storage permission setting not working correctly

the list goes on - persistent storage and access to it is horribly broken

**Comment by earthlng** [comment] 2017-09-18 15:18
* 1398303 Local Storage not cleared by Clear Recent History

the example site weather.com uses IDB and the 5. step in his steps to reproduce is "Go to weather.com again and wait a little bit." - "wait a little bit" most likely because it restores the locations from the IDB and stores it in LocalStorage again. Local Storage is most definitely cleared by clearing recent history (cookies is enough actually) - you can check the webappsstore.sqlite file if you don't believe me.

**Comment by Thorin-Oakenpants** [comment] 2017-09-18 16:22
Well that's good to know. "Everything" time range works. See, we always have the best settings

**Comment by Thorin-Oakenpants** [comment] 2017-09-18 18:03
Anyway, we know there are lots of issues with clearing and access to persistent storage - my issue was... and still is ... should we create a persistent [web/content] storage section :question:  No-one has commented on that in 6 days since I proposed it

**Comment by earthlng** [comment] 2017-09-18 18:28
> should we create a persistent [web/content] storage section :question:  No-one has commented on that in 6 days since I proposed it

yeah sorry about that. Sure, I am not against that but with all these issues at the moment maybe it would be better to wait for a while. Otherwise there would need to be a lot of text and it could easily end up being way too confusing.

**Comment by Thorin-Oakenpants** [comment] 2017-09-18 19:39
Its not hard to move those few items into 2700 and rename it. BTW I didn't mean that the section header had to list any issues, well, not all of em, maybe none to start with

- cookies control local dom storage
- PB cookies are protected [1 zilla]
- Mozilla internal cookies are protected [1 zilla]
- FPI applies to all windows including PB
- FPI storage is protected [1 zilla]
- offline storage settings do not work [1 zilla]
- IDB is fukked [10 zillas]
- Clearing history not by everything has issues [2+ zillas]
- Forget this site is poked
- Containers have issues

^^ OK .. ok ... too many issues (I can think of another 5). Is that what you meant by all these issues? That is so depressing I almost feel like going back to ESR

**Comment by 2glops** [comment] 2017-09-18 21:30
A persistent "storage and memory" section is a good idea.
Many issues there, but the actual main goal of that section should be identify and group all items related to browser storage.

**Comment by Thorin-Oakenpants** [comment] 2017-09-19 09:51
> A persistent "storage and memory" section is a good idea.

Noooo! Not memory. I see memory/cache as an internal Firefox thing (and we have a dedicated 1000 section) - same with session store, histories (browsing, download, form), CA's etc

This proposed section is for data set ***BY*** websites - although there will always be some overlap

**Comment by mazesy** [comment] 2017-09-24 12:00
Concerning LocalStorage I read [here](https://superuser.com/questions/629525/how-to-control-websites-use-of-localstorage-in-firefox) the developer of the Firefox Cookie Controller add-on state:

> Lastly, there is a limit on the amount of storage that can be used by each web page. By default this is 5MB but you can change it, potentially to zero. However, web pages don't always handle overflowing this quota very well so you might cause problems by changing it.

The setting for this is `dom.storage.default_quota`

1- I'd like to know your opinion regarding the fact _web pages don't always handle overflowing this quota very well_.
2- Would it be pertinent to add to section
```
/* 2705: disable DOM (Document Object Model) Storage
 * [WARNING] This will break a LOT of sites' functionality.
 * You are better off using an extension for more granular control ***/
   // user_pref("dom.storage.enabled", false);
```
the following setting:
// amount of storage that can be used by each web page
// user_pref("dom.storage.default_quota", 0);// Default=5120 (5MB)

Of course it's possible to use a dedicated add-on (or even as I used to, a dedicated _Custom Button_) but this requires a per-site user intervention since Firefox doesn't handle this on per-site. On another hand setting `dom.storage.enabled` to false is indeed problematic. I'm trying right now with the above dom storage quota set to 0, testing here and there sites I know that use LocalStorage, and no problem. YouTube for instance stored nothing when otherwise it does.

**Comment by Thorin-Oakenpants** [comment] 2017-09-24 12:54
May be good info to add when we revamp this section which is going to be a mess until all the IDB/OWD/Clear-history/OAs/extension-access and a dozen other broken things are fixed - eg did u know that warnings for OWD (offline website data = IDB) are broken and it never prompts and does does it anyway.

`dom.storage.default_quota` may be ok to add somewhere, but I it is a bit pointless (depends on your strategy maybe???). Cookies control access to local dom storage - this is the major factor. A cookie extension (when FPI etc OA's are fixed) will simply clear on demand, on close, on domain close. How much data is stored is immaterial IMO (unless it is used to trigger eg a prompt). I fail to see how much is stored has any implications for tracking - limiting it may even cause web site breakage/issues

**Comment by mazesy** [comment] 2017-09-24 13:34
Yeah, the IndexedDB odyssey, the fact of visiting a site such as bostonglobe.com with cookies set to site and session only and notice in the Page Info / Permissions / Maintain Offline Storage filled with 48kB of data, removing it and blocking the site, reopening the site to notice the 48kB are back: yeps I experienced that as we all. Ghacks has a dedicated article on this.

I managed a work-around by associating two add-ons : _Permit Cookie 2_ (legacy add-on) and _Cookie Autodelete_. I've uninstalled _Self-Destructing Cookies_ add-on not because it is a legacy add-on but because _Cookie Autodelete_ being a Webextension it will run its cookie management database seperately, and that can be an advantage:

I've set `network.cookie.cookieBehavior` to 2 (=disallow all)
From there on Cookie Autodelete has nothing to perform ... except if a site either requires a cookie to simply open (few, but some do!) either because I need to login.
If cookie required, I make a session exception for that site with _Permit Cookie 2_ 
- without setting that site's cookie permission in _Cookie Autodelete_ if I wish not the cookie to be kept once the site closed,
- by adding a cookie permission (session or keep) in _Cookie Autodelete_ otherwise.

All this rather than only Cookie Autodelete only because whatever site, if cookies are not blocked (blocked for that site anyway) are at this time enabled to lay their data in my profile / storage folder, and I refuse that. 

The LocalStorage is less problematic in that the storage will be persistent only if the site is allowed to use a persistent cookie. In my scheme I face a site laying IndexedDB data in my storage folder only if I've set a cookie exception (session or persistent) and that the site is an IndexedDB aficionado.

Not to mention that blocking all cookies with exceptions is a pleasure when visiting sites that install cookies for no valid reason, and even edit them live as bostonglobe.com does : listen, I still use an add-on called 'Noise' and it includes two Event topics (via addObserver), the cookie-rejected and cookie-changed events : I check these two events for testing, visit a site such as bostonglobe and hear the cookie(s) modified as I scroll! The site is actually updating live its cookieon every line I scroll!.

So, altogether, this combination of two add-ons, one (legacy) handling cookie exceptions on Firefox's level, the other, Webextension, handling cookies' exceptions within its own database, allows to fine tune cookies and therefore storage, globally since all seems to depend of the cookies behavior permission. That's how I do it until Mozilla gets things in order.

**Comment by mazesy** [comment] 2017-09-26 11:39
I've been experiencing with:
```
user_pref("dom.storage.enabled", true); // Default=true
user_pref("dom.storage.default_quota", 0); // Default=5120
```
Quite nice. Many sites block with `dom.storage.enabled` set to false but not with `dom.storage.default_quota` set to 0, especially those which don't actually write Web Storage data but require nevertheless storage as enabled. Youtube for instance does write Local and Session storage but runs fine with the quota set to 0. Userstyles.org as well except that it won't handle the screen display functionality (two top-right buttons) with quota set to 0. Even ProtonMail runs OK: it displays a message stating dom storage is required but runs nevertheless fine!

For whome may be interested to know what Local and Session storage is used by a site, there's the [localStorage inspector bookmarklet](http://potch.me/ls/) which delivers that information flawlessly.

Indeed, as mentioned in the user.js concerning `dom.storage.enabled`, 

> You are better off using an extension for more granular control

but the point is, if controlling with an extension (or with a dedicated _Custom Button_ as I do) the dom storage feature, switching `dom.storage.default_quota` from 5120 to 0 seems to be far more practical then switching `dom.storage.enabled` from true to false, given many sites won't block systematically.

**Comment by crssi** [comment] 2017-09-26 13:47
Just FYI

With
```js
user_pref("dom.storage.default_quota", 0);
```
videos on imdb.com does not work.
But they work when set with a little as 1.

**Comment by mazesy** [comment] 2017-09-26 14:11
I am considering `dom.storage.default_quota` as `dom.storage.enabled` is considered in our user.js, that is to either keep the default value either to tune on a per-site basis with an extension. I'm evoking the quota=0 as a replacement value to its default 5120 in the context of a per-site permission to switch back to 5120.

Example: 
- I've set `dom.storage.default_quota` to 0
- I've installed a toolbar button crafted with the Custom Buttons add-on to toggle the above quota between 0 and 5120
- I know the few sites which require quota=5120 and I click the button accordingly to toggle back to 5120. I toggle back to 0 once I've left the site.

Of course it would be as an aberration to set the quota to 0 for everywhere as it is to set the dom storage to disabled ... unless granular control is made available.

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 15:41
> unless granular control is made available

Why do you make everything so complicated, extra clicks, dozens of extra extensions :)

Cookies control local storage. So you can block all and set a site exception ("allow" or "allow for session"). The "no 3rd party cookie" setting also blocks 3rd party access to "3rd party Web Storage, IndexedDB, Cache API and Service Worker Cache" <sup>1</sup> . Additionally FPI also protects from 3rd party. You can also wipe cookies and local storage on close (so same as allow for session only). 

So at WORST, a 1st party can detect a subsequent visit (and if you;re like me and only allow cookies for sites you LOG INTO, then it's a bit of a moot point). And last but not least, once local dom ***by host*** is allowed (bugzilla are almost there), then an extension can even remove this by auto-deleting on domain close.

<sup>1</sup> [click me](https://www.fxsitecompat.com/en-CA/docs/2015/web-storage-indexeddb-cache-api-now-obey-third-party-cookies-preference/)

**Comment by mazesy** [comment] 2017-09-26 16:07
My point is to replace what was performed with the Self-Destructing Cookies legacy add-on but not handled by a Webextension : remove what has been set in the users localStorage once the site is closed, as performed with non whitelisted cookies. Cookies is easy, the Cookie Autodelete webextension does it, but doesn't handle the localStorage.

Nothing complicated in fact, unless to consider that the aim of clearing DOM storage set by a site is excessive given that DOM storage won't be readable by a 3rd-party site if 3rd-cookies are forbidden, that sessionStorage vanishes and that localStorage is persistent only if a site has been set in the user's cookie whitelist.

My aim is to have the DOM storage set by a site cleared once the site is closed. The aim is arguable but the way to achieve it (now that Webextensions cannot) seems to me interesting, and I happened to believe that squeezing privacy concerns was the very lot of our common concern here.

**Comment by Thorin-Oakenpants** [comment] 2017-09-26 16:20
> My point is to replace what was performed with the Self-Destructing Cookies legacy add-on but not handled by a Webextension

I've never understood the BS fixation with allowing cookies, period. Anyway, not my fault SDC broke in 55. Extensions ***will*** be able to handle local dom storage, including those with FPI and containerID OAs (orign attributes), maybe even PB OAs. But not internal cookies (such as the GA one with SB). Extensions will also be able to handle IDB. Hopefully by 58. Until then, if you used my strategy of default deny cookies (and even using one off PB windows as needed) then there is no need to clear anything. You're just making it harder on yourself :)

**Comment by crssi** [comment] 2017-09-26 16:37
> But they work when set with a little as 1

This is just observation notice, I am using default. ;)

**Comment by mazesy** [comment] 2017-09-26 19:32
> if you used my strategy of default deny cookies (and even using one off PB windows as needed) then there is no need to clear anything. 

I deny cookies as well (`network.cookie.cookieBehavior` = 2) but some sites won't even open if cookies are denied (for them since globally) ... that means such sites need at least a session cookie exception. OK. From there on an extension such as _Cookie Autodelete_  will delete the cookie once the site is closed. OK. Problem is sites with cookie not forbidden (session or allow) have the ability to store IndexedDB data in the user's profile storage subfolder (I take the example of bostonglobe.com but truth is not many sites jymp on that possibility) and that forbidding offline storage for such sites will have been the issue until coming Firefox 56.

Concerning DOM storage looks like I've mistaked, indeed. No point in emphasizing on a no-problem.
I have gotten saturated with non-controlled storage and the way of dealing with it. Looking forwards to these issues announced as resolved in Firefox 56/57.

**Comment by Thorin-Oakenpants** [comment] 2017-09-28 06:23
FYI:
- IDB: resolved fixed in 57+ [1333050](https://bugzilla.mozilla.org/show_bug.cgi?id=1333050) clearing of IndexedDB in browsingData API
    - not sure if this is granular (filter by time and hostname)
    - also not sure if it covers "cache API + SW cache and asm.js"
- LOCAL DOM: resolved fixed in 58+  [1388428](https://bugzilla.mozilla.org/show_bug.cgi?id=1388428) delete local dom storage ***by host** (I do not know if this is affected by OAs such as FPI)
- COOKIES: unresolved and complicated [1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197) OA (OriginAttribute) cookies issues (FPI, PM, Container)
   - note: internal cookies such as GA with SB will not be included => WONTFIX

Hopefully by 58/59 we will be able to have an extension that covers all in one hit:
- covers all of `cookies + localdom + IDB + SW cache + cache + asm`
- by `host + time`
- regardless of OA such as `firstpartyisolate + pbmode + containerID`

**Comment by Thorin-Oakenpants** [comment] 2017-11-07 08:23
good news everybody - [1047098](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098) - IDB & clear recent history back-ported to ESR (4 hrs ago) .. enjoy all you ESR laggards :grin:

**Comment by Thorin-Oakenpants** [comment] 2017-11-10 14:58
semi related (more to do with extensions and storage) but I'll dump it here since this is an open ticket

https://bugzilla.mozilla.org/show_bug.cgi?id=1416219

> - Load about:preferences#privacy in a tab
> - In the History section choose 
>   "Firefox will use custom settings for history"
> - Check “Clear history when Firefox closes”
> 
> All the extensions localStorage data is dropped when Firefox is closed.

It does not say what **settings** are used for clearing. I suspect it is the "cookie" setting

**Comment by Thorin-Oakenpants** [comment] 2017-11-18 05:37
Note to self: 2706 storage API also toggles UI section in "privacy&security/site data". This does nothing because we're blocking it - I think this is due to `browser.cache.offline.enable` (1004) - not sure. If it is then this 1004 should be moved to the new revamped section

Also 2450* ( offline-apps.allow_by_default, browser.offline-apps.notify) should be in this section

**Comment by Thorin-Oakenpants** [comment] 2017-12-08 01:56
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1406675 - WebExtensions requiring cookies for IDB should be fixed in FF59

**Comment by Thorin-Oakenpants** [comment] 2017-12-27 07:05
The last thing I want to do here, is to reorder the section a little, now that everything is in there. I am not interested at this stage in outlining all the issues (Ext+IDB, FPI, Containers, PB Mode, and all the sanitize inconsistencies, and more) - maybe we can revisit it when 60 lands (in a new issue)

proposal
- cookies: `2700's` : 2701, 2702, 2703, 2704, 2708
- localStorage: `2710's`: 2705, 2707
- IDB: `2720's`: 2710
- appCache: `2730's`: 2720, 2721, 2723
- service workers: `2740's`: 2715
- storageAPI: `2750's`: 2706

Not adding any subheaders, just renumbering. **Any objections?**

**Comment by Thorin-Oakenpants** [comment] 2017-12-27 07:16
see https://github.com/ghacksuserjs/ghacks-user.js/pull/322 and check it out. If no one speaks up, I shall merge it in 3, 2, 1...

**Closed** 2017-12-27 23:03 UTC
Labels: discussion, enhancement
